# generated by datamodel-codegen:
#   filename:  inference.yaml

from __future__ import annotations

from enum import StrEnum
from typing import Annotated

from pydantic import BaseModel, ConfigDict, Field, RootModel


class Code(StrEnum):
    INVALID_ARGUMENT = 'INVALID_ARGUMENT'
    CAPACITY_EXHAUSTED = 'CAPACITY_EXHAUSTED'
    PROFILE_UNQUALIFIED = 'PROFILE_UNQUALIFIED'
    DEPENDENCY_UNAVAILABLE = 'DEPENDENCY_UNAVAILABLE'


class Error(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    code: Code
    message: Annotated[str, Field(max_length=512)]
    requestId: Annotated[
        str,
        Field(max_length=128, min_length=1, pattern='^[A-Za-z0-9][A-Za-z0-9._:-]*$'),
    ]
    retryable: bool


class ErrorEnvelope(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    error: Error


class ComputeIdentity(BaseModel):
    """
    Task identity Knowledge binds the computation to; never a business identity.
    """

    model_config = ConfigDict(
        extra='forbid',
    )
    taskId: Annotated[
        str,
        Field(max_length=128, min_length=1, pattern='^[A-Za-z0-9][A-Za-z0-9._:-]*$'),
    ]
    generation: Annotated[str, Field(pattern='^(0|[1-9][0-9]{0,19})$')]
    profileId: Annotated[
        str,
        Field(max_length=128, min_length=1, pattern='^[A-Za-z0-9][A-Za-z0-9._:-]*$'),
    ]


class InputKind(StrEnum):
    query = 'query'
    passage = 'passage'


class Input(RootModel[str]):
    root: Annotated[str, Field(max_length=32768, min_length=1)]


class EmbeddingRequest(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    compute: ComputeIdentity
    inputKind: InputKind
    inputs: Annotated[list[Input], Field(max_length=128, min_length=1)]
    inputDigest: Annotated[str, Field(pattern='^sha256:[0-9a-f]{64}$')]


class Indice(RootModel[int]):
    root: Annotated[int, Field(ge=0)]


class SparseVector(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    indices: Annotated[list[Indice], Field(max_length=8192)]
    values: Annotated[list[float], Field(max_length=8192)]


class ModelId(StrEnum):
    bge_m3 = 'bge-m3'


class EmbeddingResponse(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    modelId: ModelId
    modelRevision: Annotated[str, Field(max_length=128, min_length=1)]
    dimensions: Annotated[int, Field(ge=1)]
    inputDigest: Annotated[str, Field(pattern='^sha256:[0-9a-f]{64}$')]
    dense: list[list[float]]
    sparse: list[SparseVector]


class Candidate(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    candidateId: Annotated[
        str,
        Field(max_length=128, min_length=1, pattern='^[A-Za-z0-9][A-Za-z0-9._:-]*$'),
    ]
    text: Annotated[str, Field(max_length=32768, min_length=1)]


class RerankRequest(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    compute: ComputeIdentity
    query: Annotated[str, Field(max_length=8192, min_length=1)]
    candidates: Annotated[list[Candidate], Field(max_length=256, min_length=1)]
    inputDigest: Annotated[str, Field(pattern='^sha256:[0-9a-f]{64}$')]


class ModelId1(StrEnum):
    bge_reranker_v2_m3 = 'bge-reranker-v2-m3'


class Score(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    candidateId: Annotated[
        str,
        Field(max_length=128, min_length=1, pattern='^[A-Za-z0-9][A-Za-z0-9._:-]*$'),
    ]
    score: float


class RerankResponse(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    modelId: ModelId1
    modelRevision: Annotated[str, Field(max_length=128, min_length=1)]
    inputDigest: Annotated[str, Field(pattern='^sha256:[0-9a-f]{64}$')]
    scores: list[Score]
