// Package modelproxyapi provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.8.0 DO NOT EDIT.
package modelproxyapi

import (
	"bytes"
	"compress/flate"
	"context"
	"encoding/base64"
	"encoding/json"
	"fmt"
	"io"
	"net/http"
	"net/url"
	"path"
	"strings"

	"github.com/getkin/kin-openapi/openapi3"
	"github.com/oapi-codegen/runtime"
)

// Defines values for ErrorEnvelopeErrorCode.
const (
	BUDGETEXHAUSTED       ErrorEnvelopeErrorCode = "BUDGET_EXHAUSTED"
	DEPENDENCYUNAVAILABLE ErrorEnvelopeErrorCode = "DEPENDENCY_UNAVAILABLE"
	EFFECTUNCERTAIN       ErrorEnvelopeErrorCode = "EFFECT_UNCERTAIN"
	FORBIDDEN             ErrorEnvelopeErrorCode = "FORBIDDEN"
	IDEMPOTENCYCONFLICT   ErrorEnvelopeErrorCode = "IDEMPOTENCY_CONFLICT"
	INVALIDARGUMENT       ErrorEnvelopeErrorCode = "INVALID_ARGUMENT"
	NOTFOUND              ErrorEnvelopeErrorCode = "NOT_FOUND"
	PROFILEUNQUALIFIED    ErrorEnvelopeErrorCode = "PROFILE_UNQUALIFIED"
	STALEEXECUTION        ErrorEnvelopeErrorCode = "STALE_EXECUTION"
	UNAUTHENTICATED       ErrorEnvelopeErrorCode = "UNAUTHENTICATED"
)

// Valid indicates whether the value is a known member of the ErrorEnvelopeErrorCode enum.
func (e ErrorEnvelopeErrorCode) Valid() bool {
	switch e {
	case BUDGETEXHAUSTED:
		return true
	case DEPENDENCYUNAVAILABLE:
		return true
	case EFFECTUNCERTAIN:
		return true
	case FORBIDDEN:
		return true
	case IDEMPOTENCYCONFLICT:
		return true
	case INVALIDARGUMENT:
		return true
	case NOTFOUND:
		return true
	case PROFILEUNQUALIFIED:
		return true
	case STALEEXECUTION:
		return true
	case UNAUTHENTICATED:
		return true
	default:
		return false
	}
}

// Defines values for MessageRole.
const (
	Assistant MessageRole = "assistant"
	System    MessageRole = "system"
	Tool      MessageRole = "tool"
	User      MessageRole = "user"
)

// Valid indicates whether the value is a known member of the MessageRole enum.
func (e MessageRole) Valid() bool {
	switch e {
	case Assistant:
		return true
	case System:
		return true
	case Tool:
		return true
	case User:
		return true
	default:
		return false
	}
}

// Defines values for ModelCallState.
const (
	ModelCallStateAdmitting ModelCallState = "admitting"
	ModelCallStateCanceled  ModelCallState = "canceled"
	ModelCallStateDenied    ModelCallState = "denied"
	ModelCallStateFailed    ModelCallState = "failed"
	ModelCallStateSending   ModelCallState = "sending"
	ModelCallStateSucceeded ModelCallState = "succeeded"
	ModelCallStateUnknown   ModelCallState = "unknown"
)

// Valid indicates whether the value is a known member of the ModelCallState enum.
func (e ModelCallState) Valid() bool {
	switch e {
	case ModelCallStateAdmitting:
		return true
	case ModelCallStateCanceled:
		return true
	case ModelCallStateDenied:
		return true
	case ModelCallStateFailed:
		return true
	case ModelCallStateSending:
		return true
	case ModelCallStateSucceeded:
		return true
	case ModelCallStateUnknown:
		return true
	default:
		return false
	}
}

// Defines values for StreamFrameOutcome.
const (
	StreamFrameOutcomeCanceled  StreamFrameOutcome = "canceled"
	StreamFrameOutcomeFailed    StreamFrameOutcome = "failed"
	StreamFrameOutcomeSucceeded StreamFrameOutcome = "succeeded"
	StreamFrameOutcomeUnknown   StreamFrameOutcome = "unknown"
)

// Valid indicates whether the value is a known member of the StreamFrameOutcome enum.
func (e StreamFrameOutcome) Valid() bool {
	switch e {
	case StreamFrameOutcomeCanceled:
		return true
	case StreamFrameOutcomeFailed:
		return true
	case StreamFrameOutcomeSucceeded:
		return true
	case StreamFrameOutcomeUnknown:
		return true
	default:
		return false
	}
}

// Defines values for StreamFrameType.
const (
	StreamFrameTypeAdmitted StreamFrameType = "admitted"
	StreamFrameTypeDone     StreamFrameType = "done"
	StreamFrameTypeError    StreamFrameType = "error"
	StreamFrameTypeText     StreamFrameType = "text"
	StreamFrameTypeToolCall StreamFrameType = "tool_call"
	StreamFrameTypeUsage    StreamFrameType = "usage"
)

// Valid indicates whether the value is a known member of the StreamFrameType enum.
func (e StreamFrameType) Valid() bool {
	switch e {
	case StreamFrameTypeAdmitted:
		return true
	case StreamFrameTypeDone:
		return true
	case StreamFrameTypeError:
		return true
	case StreamFrameTypeText:
		return true
	case StreamFrameTypeToolCall:
		return true
	case StreamFrameTypeUsage:
		return true
	default:
		return false
	}
}

// Digest defines model for Digest.
type Digest = string

// ErrorEnvelope defines model for ErrorEnvelope.
type ErrorEnvelope struct {
	Error struct {
		Code      ErrorEnvelopeErrorCode `json:"code"`
		Message   string                 `json:"message"`
		RequestId Id                     `json:"requestId"`
		Retryable bool                   `json:"retryable"`
	} `json:"error"`
}

// ErrorEnvelopeErrorCode defines model for ErrorEnvelope.Error.Code.
type ErrorEnvelopeErrorCode string

// ExecutionBinding defines model for ExecutionBinding.
type ExecutionBinding struct {
	AttemptId      Id       `json:"attemptId"`
	ExecutionEpoch Sequence `json:"executionEpoch"`
	InstanceId     *Id      `json:"instanceId,omitempty"`
	OperationId    Id       `json:"operationId"`
	TenantId       Id       `json:"tenantId"`
}

// Id defines model for Id.
type Id = string

// Message One message of the history. `toolCalls` belongs to assistant messages (the calls the model made); `toolCallId` belongs to tool messages (the result of exactly one earlier assistant tool call). The Proxy refuses either member on another role and a tool message that answers no earlier call.
type Message struct {
	Content    string             `json:"content"`
	Role       MessageRole        `json:"role"`
	ToolCallId *Id                `json:"toolCallId,omitempty"`
	ToolCalls  *[]MessageToolCall `json:"toolCalls,omitempty"`
}

// MessageRole defines model for Message.Role.
type MessageRole string

// MessageToolCall One tool call an assistant message made, replayed to the model as the round trip the model produced; `arguments` is the JSON object text of the tool_call frame.
type MessageToolCall struct {
	Arguments  string `json:"arguments"`
	Name       string `json:"name"`
	ToolCallId Id     `json:"toolCallId"`
}

// ModelCall defines model for ModelCall.
type ModelCall struct {
	CallId          Id             `json:"callId"`
	CreatedAt       Timestamp      `json:"createdAt"`
	DispatchId      Id             `json:"dispatchId"`
	ErrorCode       *string        `json:"errorCode,omitempty"`
	NativeReference *string        `json:"nativeReference,omitempty"`
	RouteId         Id             `json:"routeId"`
	State           ModelCallState `json:"state"`
	UpdatedAt       Timestamp      `json:"updatedAt"`
	Usage           *Usage         `json:"usage,omitempty"`
}

// ModelCallState defines model for ModelCall.State.
type ModelCallState string

// ModelCallRequest defines model for ModelCallRequest.
type ModelCallRequest struct {
	Binding          ExecutionBinding  `json:"binding"`
	CallId           Id                `json:"callId"`
	Deadline         Timestamp         `json:"deadline"`
	EvidenceRef      *string           `json:"evidenceRef,omitempty"`
	MaxExposure      Money             `json:"maxExposure"`
	MaxOutputTokens  int               `json:"maxOutputTokens"`
	Messages         []Message         `json:"messages"`
	RequestDigest    Digest            `json:"requestDigest"`
	RouteId          Id                `json:"routeId"`
	SupersedesCallId *Id               `json:"supersedesCallId,omitempty"`
	Tools            *[]ToolDefinition `json:"tools,omitempty"`
}

// Money defines model for Money.
type Money struct {
	Amount   string `json:"amount"`
	Currency string `json:"currency"`
}

// Sequence defines model for Sequence.
type Sequence = string

// StreamFrame One SSE `data` payload; `sequence` is monotonic per call and bounded by the route profile.
type StreamFrame struct {
	CallId    Id                  `json:"callId"`
	ErrorCode *string             `json:"errorCode,omitempty"`
	Outcome   *StreamFrameOutcome `json:"outcome,omitempty"`
	Sequence  Sequence            `json:"sequence"`
	Text      *string             `json:"text,omitempty"`
	ToolCall  *struct {
		Arguments       *string `json:"arguments,omitempty"`
		ArgumentsDigest Digest  `json:"argumentsDigest"`
		Name            string  `json:"name"`
		ToolCallId      Id      `json:"toolCallId"`
	} `json:"toolCall,omitempty"`
	Type  StreamFrameType `json:"type"`
	Usage *Usage          `json:"usage,omitempty"`
}

// StreamFrameOutcome defines model for StreamFrame.Outcome.
type StreamFrameOutcome string

// StreamFrameType defines model for StreamFrame.Type.
type StreamFrameType string

// Timestamp defines model for Timestamp.
type Timestamp = string

// ToolDefinition defines model for ToolDefinition.
type ToolDefinition struct {
	Description       *string `json:"description,omitempty"`
	InputSchemaDigest Digest  `json:"inputSchemaDigest"`
	Name              string  `json:"name"`
}

// Usage defines model for Usage.
type Usage struct {
	CachedInputUnits Sequence `json:"cachedInputUnits"`
	InputUnits       Sequence `json:"inputUnits"`
	OutputUnits      Sequence `json:"outputUnits"`
	ReasoningUnits   Sequence `json:"reasoningUnits"`
}

// Error defines model for Error.
type Error = ErrorEnvelope

// CreateModelCallJSONRequestBody defines body for CreateModelCall for application/json ContentType.
type CreateModelCallJSONRequestBody = ModelCallRequest

// RequestEditorFn is the function signature for the RequestEditor callback function
type RequestEditorFn func(ctx context.Context, req *http.Request) error

// Doer performs HTTP requests.
//
// The standard http.Client implements this interface.
type HttpRequestDoer interface {
	Do(req *http.Request) (*http.Response, error)
}

// Client which conforms to the OpenAPI3 specification for this service.
type Client struct {
	// The endpoint of the server conforming to this interface, with scheme,
	// https://api.deepmap.com for example. This can contain a path relative
	// to the server, such as https://api.deepmap.com/dev-test, and all the
	// paths in the swagger spec will be appended to the server.
	Server string

	// Doer for performing requests, typically a *http.Client with any
	// customized settings, such as certificate chains.
	Client HttpRequestDoer

	// A list of callbacks for modifying requests which are generated before sending over
	// the network.
	RequestEditors []RequestEditorFn
}

// ClientOption allows setting custom parameters during construction
type ClientOption func(*Client) error

// Creates a new Client, with reasonable defaults
func NewClient(server string, opts ...ClientOption) (*Client, error) {
	// create a client with sane default values
	client := Client{
		Server: server,
	}
	// mutate client and add all optional params
	for _, o := range opts {
		if err := o(&client); err != nil {
			return nil, err
		}
	}
	// ensure the server URL always has a trailing slash
	if !strings.HasSuffix(client.Server, "/") {
		client.Server += "/"
	}
	// create httpClient, if not already present
	if client.Client == nil {
		client.Client = &http.Client{}
	}
	return &client, nil
}

// WithHTTPClient allows overriding the default Doer, which is
// automatically created using http.Client. This is useful for tests.
func WithHTTPClient(doer HttpRequestDoer) ClientOption {
	return func(c *Client) error {
		c.Client = doer
		return nil
	}
}

// WithRequestEditorFn allows setting up a callback function, which will be
// called right before sending the request. This can be used to mutate the request.
func WithRequestEditorFn(fn RequestEditorFn) ClientOption {
	return func(c *Client) error {
		c.RequestEditors = append(c.RequestEditors, fn)
		return nil
	}
}

// The interface specification for the client above.
type ClientInterface interface {

	// CreateModelCallWithBody performs a POST /model-calls (the `CreateModelCall` operationId) request,
	// with any type of body and a specified content type.
	//
	// Opens a model call and streams frames. The response is Server-Sent Events; the final frame is `done` or `error`. A lost response is queried by callId, never resent.
	CreateModelCallWithBody(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error)

	// CreateModelCall performs a POST /model-calls (the `CreateModelCall` operationId) request.
	// Takes a body of the `application/json` content type.
	//
	// Opens a model call and streams frames. The response is Server-Sent Events; the final frame is `done` or `error`. A lost response is queried by callId, never resent.
	CreateModelCall(ctx context.Context, body CreateModelCallJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error)

	// GetModelCall performs a GET /model-calls/{callId} (the `GetModelCall` operationId) request.
	//
	// Queries the original call outcome and usage; querying never sends again.
	GetModelCall(ctx context.Context, callId Id, reqEditors ...RequestEditorFn) (*http.Response, error)

	// CancelModelCall performs a POST /model-calls/{callId}/cancellations (the `CancelModelCall` operationId) request.
	//
	// Expresses cancel intent; already incurred usage stays in the ledger.
	CancelModelCall(ctx context.Context, callId Id, reqEditors ...RequestEditorFn) (*http.Response, error)
}

// CreateModelCallWithBody performs a POST /model-calls (the `CreateModelCall` operationId) request,
// with any type of body and a specified content type.
//
// Opens a model call and streams frames. The response is Server-Sent Events; the final frame is `done` or `error`. A lost response is queried by callId, never resent.
func (c *Client) CreateModelCallWithBody(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewCreateModelCallRequestWithBody(c.Server, contentType, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

// CreateModelCall performs a POST /model-calls (the `CreateModelCall` operationId) request.
// Takes a body of the `application/json` content type.
//
// Opens a model call and streams frames. The response is Server-Sent Events; the final frame is `done` or `error`. A lost response is queried by callId, never resent.
func (c *Client) CreateModelCall(ctx context.Context, body CreateModelCallJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewCreateModelCallRequest(c.Server, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

// GetModelCall performs a GET /model-calls/{callId} (the `GetModelCall` operationId) request.
//
// Queries the original call outcome and usage; querying never sends again.
func (c *Client) GetModelCall(ctx context.Context, callId Id, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewGetModelCallRequest(c.Server, callId)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

// CancelModelCall performs a POST /model-calls/{callId}/cancellations (the `CancelModelCall` operationId) request.
//
// Expresses cancel intent; already incurred usage stays in the ledger.
func (c *Client) CancelModelCall(ctx context.Context, callId Id, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewCancelModelCallRequest(c.Server, callId)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

// NewCreateModelCallRequest calls the generic CreateModelCall builder with application/json body
func NewCreateModelCallRequest(server string, body CreateModelCallJSONRequestBody) (*http.Request, error) {
	var bodyReader io.Reader
	buf, err := json.Marshal(body)
	if err != nil {
		return nil, err
	}
	bodyReader = bytes.NewReader(buf)
	return NewCreateModelCallRequestWithBody(server, "application/json", bodyReader)
}

// NewCreateModelCallRequestWithBody constructs an http.Request for the CreateModelCall method, with any body, and a specified content type
func NewCreateModelCallRequestWithBody(server string, contentType string, body io.Reader) (*http.Request, error) {
	var err error

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/model-calls")
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest(http.MethodPost, queryURL.String(), body)
	if err != nil {
		return nil, err
	}

	req.Header.Add("Content-Type", contentType)

	return req, nil
}

// NewGetModelCallRequest constructs an http.Request for the GetModelCall method
func NewGetModelCallRequest(server string, callId Id) (*http.Request, error) {
	var err error

	var pathParam0 string

	pathParam0, err = runtime.StyleParamWithOptions("simple", false, "callId", callId, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationPath, Type: "string", Format: ""})
	if err != nil {
		return nil, err
	}

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/model-calls/%s", pathParam0)
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest(http.MethodGet, queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

// NewCancelModelCallRequest constructs an http.Request for the CancelModelCall method
func NewCancelModelCallRequest(server string, callId Id) (*http.Request, error) {
	var err error

	var pathParam0 string

	pathParam0, err = runtime.StyleParamWithOptions("simple", false, "callId", callId, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationPath, Type: "string", Format: ""})
	if err != nil {
		return nil, err
	}

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/model-calls/%s/cancellations", pathParam0)
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest(http.MethodPost, queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

func (c *Client) applyEditors(ctx context.Context, req *http.Request, additionalEditors []RequestEditorFn) error {
	for _, r := range c.RequestEditors {
		if err := r(ctx, req); err != nil {
			return err
		}
	}
	for _, r := range additionalEditors {
		if err := r(ctx, req); err != nil {
			return err
		}
	}
	return nil
}

// ClientWithResponses builds on ClientInterface to offer response payloads
type ClientWithResponses struct {
	ClientInterface
}

// NewClientWithResponses creates a new ClientWithResponses, which wraps
// Client with return type handling
func NewClientWithResponses(server string, opts ...ClientOption) (*ClientWithResponses, error) {
	client, err := NewClient(server, opts...)
	if err != nil {
		return nil, err
	}
	return &ClientWithResponses{client}, nil
}

// WithBaseURL overrides the baseURL.
func WithBaseURL(baseURL string) ClientOption {
	return func(c *Client) error {
		newBaseURL, err := url.Parse(baseURL)
		if err != nil {
			return err
		}
		c.Server = newBaseURL.String()
		return nil
	}
}

// ClientWithResponsesInterface is the interface specification for the client with responses above.
type ClientWithResponsesInterface interface {

	// CreateModelCallWithBodyWithResponse performs a POST /model-calls (the `CreateModelCall` operationId) request,
	// with any type of body and a specified content type.
	//
	// Opens a model call and streams frames. The response is Server-Sent Events; the final frame is `done` or `error`. A lost response is queried by callId, never resent.
	//
	// Returns a wrapper object for the known response body format(s).
	CreateModelCallWithBodyWithResponse(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*CreateModelCallResponse, error)

	// CreateModelCallWithResponse performs a POST /model-calls (the `CreateModelCall` operationId) request.
	// Takes a body of the `application/json` content type, and returns a wrapper object for the known response body format(s).
	//
	// Opens a model call and streams frames. The response is Server-Sent Events; the final frame is `done` or `error`. A lost response is queried by callId, never resent.
	CreateModelCallWithResponse(ctx context.Context, body CreateModelCallJSONRequestBody, reqEditors ...RequestEditorFn) (*CreateModelCallResponse, error)

	// GetModelCallWithResponse performs a GET /model-calls/{callId} (the `GetModelCall` operationId) request.
	//
	// Queries the original call outcome and usage; querying never sends again.
	//
	// Returns a wrapper object for the known response body format(s).
	GetModelCallWithResponse(ctx context.Context, callId Id, reqEditors ...RequestEditorFn) (*GetModelCallResponse, error)

	// CancelModelCallWithResponse performs a POST /model-calls/{callId}/cancellations (the `CancelModelCall` operationId) request.
	//
	// Expresses cancel intent; already incurred usage stays in the ledger.
	//
	// Returns a wrapper object for the known response body format(s).
	CancelModelCallWithResponse(ctx context.Context, callId Id, reqEditors ...RequestEditorFn) (*CancelModelCallResponse, error)
}

type CreateModelCallResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	// JSON400 the response for an HTTP 400 `application/json` response
	JSON400 *Error
	// JSON403 the response for an HTTP 403 `application/json` response
	JSON403 *Error
	// JSON409 the response for an HTTP 409 `application/json` response
	JSON409 *Error
	// JSON429 the response for an HTTP 429 `application/json` response
	JSON429 *Error
	// JSON503 the response for an HTTP 503 `application/json` response
	JSON503 *Error
}

// GetJSON400 returns the response for an HTTP 400 `application/json` response
func (r CreateModelCallResponse) GetJSON400() *Error {
	return r.JSON400
}

// GetJSON403 returns the response for an HTTP 403 `application/json` response
func (r CreateModelCallResponse) GetJSON403() *Error {
	return r.JSON403
}

// GetJSON409 returns the response for an HTTP 409 `application/json` response
func (r CreateModelCallResponse) GetJSON409() *Error {
	return r.JSON409
}

// GetJSON429 returns the response for an HTTP 429 `application/json` response
func (r CreateModelCallResponse) GetJSON429() *Error {
	return r.JSON429
}

// GetJSON503 returns the response for an HTTP 503 `application/json` response
func (r CreateModelCallResponse) GetJSON503() *Error {
	return r.JSON503
}

// GetBody returns the raw response body bytes
func (r CreateModelCallResponse) GetBody() []byte {
	return r.Body
}

// Status returns HTTPResponse.Status
func (r CreateModelCallResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r CreateModelCallResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

// ContentType is a convenience method to retrieve the Content-Type value from the HTTP response headers
func (r CreateModelCallResponse) ContentType() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Header.Get("Content-Type")
	}
	return ""
}

type GetModelCallResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	// JSON200 the response for an HTTP 200 `application/json` response
	JSON200 *ModelCall
	// JSON404 the response for an HTTP 404 `application/json` response
	JSON404 *Error
	// JSON503 the response for an HTTP 503 `application/json` response
	JSON503 *Error
}

// GetJSON200 returns the response for an HTTP 200 `application/json` response
func (r GetModelCallResponse) GetJSON200() *ModelCall {
	return r.JSON200
}

// GetJSON404 returns the response for an HTTP 404 `application/json` response
func (r GetModelCallResponse) GetJSON404() *Error {
	return r.JSON404
}

// GetJSON503 returns the response for an HTTP 503 `application/json` response
func (r GetModelCallResponse) GetJSON503() *Error {
	return r.JSON503
}

// GetBody returns the raw response body bytes
func (r GetModelCallResponse) GetBody() []byte {
	return r.Body
}

// Status returns HTTPResponse.Status
func (r GetModelCallResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r GetModelCallResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

// ContentType is a convenience method to retrieve the Content-Type value from the HTTP response headers
func (r GetModelCallResponse) ContentType() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Header.Get("Content-Type")
	}
	return ""
}

type CancelModelCallResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	// JSON202 the response for an HTTP 202 `application/json` response
	JSON202 *ModelCall
	// JSON404 the response for an HTTP 404 `application/json` response
	JSON404 *Error
	// JSON503 the response for an HTTP 503 `application/json` response
	JSON503 *Error
}

// GetJSON202 returns the response for an HTTP 202 `application/json` response
func (r CancelModelCallResponse) GetJSON202() *ModelCall {
	return r.JSON202
}

// GetJSON404 returns the response for an HTTP 404 `application/json` response
func (r CancelModelCallResponse) GetJSON404() *Error {
	return r.JSON404
}

// GetJSON503 returns the response for an HTTP 503 `application/json` response
func (r CancelModelCallResponse) GetJSON503() *Error {
	return r.JSON503
}

// GetBody returns the raw response body bytes
func (r CancelModelCallResponse) GetBody() []byte {
	return r.Body
}

// Status returns HTTPResponse.Status
func (r CancelModelCallResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r CancelModelCallResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

// ContentType is a convenience method to retrieve the Content-Type value from the HTTP response headers
func (r CancelModelCallResponse) ContentType() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Header.Get("Content-Type")
	}
	return ""
}

// CreateModelCallWithBodyWithResponse performs a POST /model-calls (the `CreateModelCall` operationId) request,
// with any type of body and a specified content type.
//
// Opens a model call and streams frames. The response is Server-Sent Events; the final frame is `done` or `error`. A lost response is queried by callId, never resent.
//
// Returns a wrapper object for the known response body format(s).
func (c *ClientWithResponses) CreateModelCallWithBodyWithResponse(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*CreateModelCallResponse, error) {
	rsp, err := c.CreateModelCallWithBody(ctx, contentType, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseCreateModelCallResponse(rsp)
}

// CreateModelCallWithResponse performs a POST /model-calls (the `CreateModelCall` operationId) request.
// Takes a body of the `application/json` content type, and returns a wrapper object for the known response body format(s).
//
// Opens a model call and streams frames. The response is Server-Sent Events; the final frame is `done` or `error`. A lost response is queried by callId, never resent.
func (c *ClientWithResponses) CreateModelCallWithResponse(ctx context.Context, body CreateModelCallJSONRequestBody, reqEditors ...RequestEditorFn) (*CreateModelCallResponse, error) {
	rsp, err := c.CreateModelCall(ctx, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseCreateModelCallResponse(rsp)
}

// GetModelCallWithResponse performs a GET /model-calls/{callId} (the `GetModelCall` operationId) request.
//
// Queries the original call outcome and usage; querying never sends again.
//
// Returns a wrapper object for the known response body format(s).
func (c *ClientWithResponses) GetModelCallWithResponse(ctx context.Context, callId Id, reqEditors ...RequestEditorFn) (*GetModelCallResponse, error) {
	rsp, err := c.GetModelCall(ctx, callId, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseGetModelCallResponse(rsp)
}

// CancelModelCallWithResponse performs a POST /model-calls/{callId}/cancellations (the `CancelModelCall` operationId) request.
//
// Expresses cancel intent; already incurred usage stays in the ledger.
//
// Returns a wrapper object for the known response body format(s).
func (c *ClientWithResponses) CancelModelCallWithResponse(ctx context.Context, callId Id, reqEditors ...RequestEditorFn) (*CancelModelCallResponse, error) {
	rsp, err := c.CancelModelCall(ctx, callId, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseCancelModelCallResponse(rsp)
}

// ParseCreateModelCallResponse parses an HTTP response from a CreateModelCallWithResponse call
func ParseCreateModelCallResponse(rsp *http.Response) (*CreateModelCallResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &CreateModelCallResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 400:
		var dest Error
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON400 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 403:
		var dest Error
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON403 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 409:
		var dest Error
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON409 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 429:
		var dest Error
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON429 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 503:
		var dest Error
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON503 = &dest

	}

	return response, nil
}

// ParseGetModelCallResponse parses an HTTP response from a GetModelCallWithResponse call
func ParseGetModelCallResponse(rsp *http.Response) (*GetModelCallResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &GetModelCallResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest ModelCall
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 404:
		var dest Error
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON404 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 503:
		var dest Error
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON503 = &dest

	}

	return response, nil
}

// ParseCancelModelCallResponse parses an HTTP response from a CancelModelCallWithResponse call
func ParseCancelModelCallResponse(rsp *http.Response) (*CancelModelCallResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &CancelModelCallResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 202:
		var dest ModelCall
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON202 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 404:
		var dest Error
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON404 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 503:
		var dest Error
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON503 = &dest

	}

	return response, nil
}

// Base64 encoded, compressed with deflate, json marshaled OpenAPI spec.
// Stored as a slice of fixed-width chunks rather than one concatenated
// const string: with thousands of chunks the chained `+` fold is several
// times slower for the Go compiler than parsing a slice literal.
var swaggerSpec = []string{
	"zFnvcuO2EX8VDJqZnDuULPlsN5Y/ZHQWfVHqkx1bStPYrg0RKwk5EmAAUGfF1fPkPfJknQVJiaIYW7ym",
	"mX4yRWP/YPeH3R+WzzRQUawkSGto55lqMLGSBtwPX2ul8SFQ0oK0+MjiOBQBs0LJ/Z+MkvjOBDOIGD59",
	"oWFCO/Qv+2ut++l/zb7T5ss5hCoGulwuPcrBBFrEqIx2UnMEshVNiisyYdTdE1MwzoeYWQsaRf5lZuzg",
	"6Lhz22qcsMbk/vn4cPkF9ahdxEA71Fgt5JQuPbppHPfBuUC7LLzSKgZtBe55wkIDHo0Lr54p5GGoIRMo",
	"7syATCLauaX9wffdi37voXv9fvTBHwypR0eD7mj4jT8Y9s+6Q79HPXp+ef2u3+v5A+rRweXw4fxyNMD3",
	"/Z7/4epy6A/O/vlwdjk4v+ifoYJ3o957f/jg//BNd3STargZdi/8B/8H/2w07F+inqvry/P+hf8wGnw3",
	"6l70z/tunX9+7p8NH0aDM/962O3jwp5/5Q96zsZo0P2+27/ovrvw6X1FMCMwhk3d/iL2dAFyame0c9Q+",
	"qFir4ecEjO3z1+DR5+lyqxdsHDrlmbKxUiEwSZeZOqGBY0xdjNfeFG0VFa13oMY/QWC39KT53V7mUf8J",
	"ggQz/k5IjhuqBwKEaRTvvHfIrfmxCmavydzgZmUAKCmksUwGsKsldNId4V0FLEgmd9xIKbor0U2zXiE6",
	"W1uvykWfl/DWPvjKo5GQq99esTDcdhs/ssYvrcbJ/fqx+dBp3P+1skB8WGP6xQxvlqxLCSTDH1ETYmdA",
	"ZsJYpRdN8miVCs9YGJpHMoZQyakhVhFmjMBs2VzQkDcoF+BKpyFSHEISMQ57p2stfb6hBl+XNGgwSWjR",
	"D3higQ0XREkgwHQoQBfsOlE0t9ckwxmQK62eFkTDJDFgCAg7A00iiMagiZKESeXeaBUCYZITtmGc2Bmz",
	"hEnzCbQhUq0MooUm3S6Mq1ZSzGXr8Kujvx1X1Q8VbhRSszAWIurRxIBGFOXbwqQqFVYWrHUMd4R7njlc",
	"LixE5jW5DD7DTNBVSfbUT0WPD1c+Ma3ZYuuMuE16q9hUwb9soD5OV2knTG6j0OHNIxrikC2AO4itsMhS",
	"YGqVSE6sFnHhf7FWPAmAn5JHpqdJhGF5JCKV+PbmckDSTRALTzY/JOjLg/NlolkE2zBZqSoB5eD4oH14",
	"WJFiySIocYNb1vil2/jxPvvbapw8NO6fW97x22qOUA8l5TK3Fs6c8QqbqMwohm+nXJZOUA0gBxqYBd61",
	"ry0figiMZVGMUlyYmNlgtqsV10DPMsZTSNZxdaKsmMM1TEC79lXK71F1EUjszs3NWGY3SgbjkbAWVeGx",
	"kAIwRQbSju5RkwQBAHdvJ0yE7iHAdpo+JvKjVJ9kZWFJYv4Z8U3yTvOSxMgt2uI8OcTykOT73chaMfFF",
	"J1+E4XXKnmqicbxmRi+S/zKTWnr5XnZKKgfGQyGhVpxhLjhi7BomO8EsYk/+U6xMol+180FJWGQyl4mN",
	"EztUH0Hm5UpESbQuVpGQ6Yv2yqiQFqagC2y6dq/Z7DGOfUdCZj/b5Y6zYsfra9RLNrJVtc9eEoM2wMHU",
	"bbe7bx9bYA8mQjqI1uy0q/OT47Z4kjYjVMjMdpo3wVLAZ/URQ7DUvDtEKpHl227j6zetf9+2kdMisX1u",
	"eQcny73KZhYkGuvrotwTsSE+VzbAcqRyBV7uS9XWVreQTTNlN9u/5+aN1cCic51175qU5ubGJ4+cWfZI",
	"YrYIFUMWYjKXHAmJlFRWSRGQOKOkjsKOkckAJ+NFTmwsIJOZiLCCjNQpVLV6oUpsoKJNfvtfdCNTSMau",
	"V0dkZWVXj47eHr/Aj+oiuS6VWwnULVU5B3wt7P87opf5UnVS0hdlVuJy6nLg0RUppjlF8ChXEmiGqmoG",
	"8gdwiRVuMv1V7q8ba6mguBN+uGykDwfrh2H+0Nl6eHN310yf297Jcu/rHytrQ6nQ10PdRrHYgMRh66QK",
	"3ULGib1xAftc3H323aOUmAxV2x5VJWa009iiXNCCGfA+6h9JYU29WdPnSKnEfo6YBmaUFHJaU7IU0ILP",
	"m65sWfC2Y1M5PzQQJFrYhUtPGtTIhtvIo/9Q+iM2JhINL27IG/w5CdWnPaI0MYJDwHTDBCoGTgINHKQV",
	"LDwlEuagCSOJAU0scg7Xt9LXE6U/MY39K4mNa6DYs1wU3LwUmHazkcztmbVxOm8XcqK2XTxT0moVhsCz",
	"K73VTJpYaXddZ3Iuwo/CNtgUpG24FY3YjYze9HqN1lvy268H+7/9euyRd62jvSbB4gjaEKZxNgR3Mt/z",
	"l4ZMxBNw8l6RbmDFXCAe3b7cTEAnxgInLAjAmEYWHOcC+VaNm8Sfg16kPTxgWqOs0x84g18aspoikozd",
	"nRJbmG85cmcII0bIaQiNxADpYhV2VyAy0SoiWSzIGCZKA1ES7mQ8WxgRMDfqwBuFJgYkJ5+EnWWhYhqk",
	"JRqszjc0YWE4ZsFHwoXBKTRvkqtc+iMs0FdhLFEyXNxJIdd+piO5NKtIYNiKq+RVGiOCmeXp7MSckvRK",
	"vXZvrLjzQ6PzWsyZBZLfhbwMQxpsomU66AmY5ALviAatC0NMoicsALQ/0eoXkAg5ctVunxJhU68CDBQL",
	"7J00KtFOr7I4WRJRHAI2Q+AEJI+VkLZ5J6lHrbAh0A7tIqL+LixJ456mZ4U56tE5aJNCs51NqyWLBe3Q",
	"t81W8y11c96ZO2v7KRyDfFYXK2O3AX4Zg0SfU3SvSGAaZJOFMQ18/v0LN3kDeg66cYO59ecgrUnxNBGS",
	"ZYMrXPaIPfoRz/Oja9OPTdIloTJ2Q9nPCWiRMs60764TYUDaZmk83qFn7ga/HhKtrifvFF/8YR/ltm7/",
	"y83aaXUC7kXhs+BBq1WyjwRmHzBEjTSomw6Uu93Wlz/k8WkWyJvCjcBxdqfWI4+Cr6aKaejz87DXRJAc",
	"tlq/t9eV8+knyHT121qrT+qsPqiz+qiGJy5yRcjvP6dYWqKKKVRA/zsHuzRsSoupg647Adndw50ERyJP",
	"HUYXQk4zZGKVM4RNmZDb8HwPtojNmGFOLGhDO7fPVKBtPKU5R+4UJlcb4PJ2BKpj4vevIvEPOAlVAMX3",
	"REOgNM/Qdvin53g/vQWGbnMvVDv/KdZgDBiSChDhonNKWKiB8QUR0t3ts7QTY9nCkKwHhcCnoCuqkVP1",
	"/5Dxgz8r4+tgZ5mHPyH3BWrpwpqSytt7DIRx/SgNd6JD2qH7LBb78zZd3i//MwA=",
}

// decodeSpec returns the embedded OpenAPI spec as raw JSON bytes,
// after base64-decoding and flate-decompressing the embedded blob.
func decodeSpec() ([]byte, error) {
	encoded := strings.Join(swaggerSpec, "")
	compressed, err := base64.StdEncoding.DecodeString(encoded)
	if err != nil {
		return nil, fmt.Errorf("error base64 decoding spec: %w", err)
	}
	zr := flate.NewReader(bytes.NewReader(compressed))
	var buf bytes.Buffer
	if _, err := buf.ReadFrom(zr); err != nil {
		return nil, fmt.Errorf("read flate: %w", err)
	}
	if err := zr.Close(); err != nil {
		return nil, fmt.Errorf("close flate reader: %w", err)
	}

	return buf.Bytes(), nil
}

var rawSpec = decodeSpecCached()

// a naive cache of the decoded OpenAPI spec
func decodeSpecCached() func() ([]byte, error) {
	data, err := decodeSpec()
	return func() ([]byte, error) {
		return data, err
	}
}

// Constructs a synthetic filesystem for resolving external references when loading openapi specifications.
func PathToRawSpec(pathToFile string) map[string]func() ([]byte, error) {
	res := make(map[string]func() ([]byte, error))
	if len(pathToFile) > 0 {
		res[pathToFile] = rawSpec
	}

	return res
}

// GetSpec returns the OpenAPI specification corresponding to the generated
// code in this file. External references in the spec are resolved through
// PathToRawSpec; externally-referenced files must be embedded in their
// corresponding Go packages (via the import-mapping feature). URL-based
// external refs are not supported.
func GetSpec() (swagger *openapi3.T, err error) {
	resolvePath := PathToRawSpec("")

	loader := openapi3.NewLoader()
	loader.IsExternalRefsAllowed = true
	loader.ReadFromURIFunc = func(loader *openapi3.Loader, url *url.URL) ([]byte, error) {
		pathToFile := url.String()
		pathToFile = path.Clean(pathToFile)
		getSpec, ok := resolvePath[pathToFile]
		if !ok {
			err1 := fmt.Errorf("path not found: %s", pathToFile)
			return nil, err1
		}
		return getSpec()
	}
	var specData []byte
	specData, err = rawSpec()
	if err != nil {
		return
	}
	swagger, err = loader.LoadFromData(specData)
	if err != nil {
		return
	}
	return
}

// GetSpecJSON returns the raw JSON bytes of the embedded OpenAPI
// specification: decompressed but not unmarshaled. External references
// are not resolved here; the bytes are the spec exactly as embedded by
// codegen. The result is cached at package init time, so repeated calls
// are cheap.
func GetSpecJSON() ([]byte, error) {
	return rawSpec()
}

// GetSwagger returns the OpenAPI specification corresponding to the
// generated code in this file.
//
// Deprecated: GetSwagger predates kin-openapi renaming openapi3.Swagger
// to openapi3.T. Use [GetSpec] instead. This wrapper is retained for
// backwards compatibility.
func GetSwagger() (*openapi3.T, error) {
	return GetSpec()
}
