/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/model-calls": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** @description Opens a model call and streams frames. The response is Server-Sent Events; the final frame is `done` or `error`. A lost response is queried by callId, never resent. */
        post: operations["createModelCall"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/model-calls/{callId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description Queries the original call outcome and usage; querying never sends again. */
        get: operations["getModelCall"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/model-calls/{callId}/cancellations": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** @description Expresses cancel intent; already incurred usage stays in the ledger. */
        post: operations["cancelModelCall"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        Id: string;
        Digest: string;
        Sequence: string;
        Timestamp: string;
        Money: {
            currency: string;
            amount: string;
        };
        ErrorEnvelope: {
            error: {
                /** @enum {string} */
                code: "INVALID_ARGUMENT" | "UNAUTHENTICATED" | "FORBIDDEN" | "NOT_FOUND" | "IDEMPOTENCY_CONFLICT" | "BUDGET_EXHAUSTED" | "STALE_EXECUTION" | "PROFILE_UNQUALIFIED" | "EFFECT_UNCERTAIN" | "DEPENDENCY_UNAVAILABLE";
                message: string;
                requestId: components["schemas"]["Id"];
                retryable: boolean;
            };
        };
        ExecutionBinding: {
            tenantId: components["schemas"]["Id"];
            operationId: components["schemas"]["Id"];
            attemptId: components["schemas"]["Id"];
            instanceId?: components["schemas"]["Id"];
            executionEpoch: components["schemas"]["Sequence"];
        };
        Message: {
            /** @enum {string} */
            role: "system" | "user" | "assistant" | "tool";
            content: string;
            toolCallId?: components["schemas"]["Id"];
        };
        ToolDefinition: {
            name: string;
            description?: string;
            inputSchemaDigest: components["schemas"]["Digest"];
        };
        ModelCallRequest: {
            callId: components["schemas"]["Id"];
            binding: components["schemas"]["ExecutionBinding"];
            routeId: components["schemas"]["Id"];
            requestDigest: components["schemas"]["Digest"];
            messages: components["schemas"]["Message"][];
            tools?: components["schemas"]["ToolDefinition"][];
            maxOutputTokens: number;
            maxExposure: components["schemas"]["Money"];
            deadline: components["schemas"]["Timestamp"];
            supersedesCallId?: components["schemas"]["Id"];
            evidenceRef?: string;
        };
        Usage: {
            inputUnits: components["schemas"]["Sequence"];
            outputUnits: components["schemas"]["Sequence"];
            reasoningUnits: components["schemas"]["Sequence"];
            cachedInputUnits: components["schemas"]["Sequence"];
        };
        /** @description One SSE `data` payload; `sequence` is monotonic per call and bounded by the route profile. */
        StreamFrame: {
            callId: components["schemas"]["Id"];
            sequence: components["schemas"]["Sequence"];
            /** @enum {string} */
            type: "admitted" | "text" | "tool_call" | "usage" | "done" | "error";
            text?: string;
            toolCall?: {
                toolCallId: components["schemas"]["Id"];
                name: string;
                argumentsDigest: components["schemas"]["Digest"];
                arguments?: string;
            };
            usage?: components["schemas"]["Usage"];
            /** @enum {string} */
            outcome?: "succeeded" | "failed" | "canceled" | "unknown";
            errorCode?: string;
        };
        ModelCall: {
            callId: components["schemas"]["Id"];
            routeId: components["schemas"]["Id"];
            /** @enum {string} */
            state: "admitting" | "denied" | "sending" | "succeeded" | "failed" | "canceled" | "unknown";
            dispatchId: components["schemas"]["Id"];
            usage?: components["schemas"]["Usage"];
            nativeReference?: string;
            errorCode?: string;
            createdAt: components["schemas"]["Timestamp"];
            updatedAt: components["schemas"]["Timestamp"];
        };
    };
    responses: {
        /** @description Error envelope. */
        Error: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ErrorEnvelope"];
            };
        };
    };
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    createModelCall: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ModelCallRequest"];
            };
        };
        responses: {
            /** @description SSE frames (StreamFrame per event, `id` is the frame sequence). */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "text/event-stream": string;
                };
            };
            400: components["responses"]["Error"];
            403: components["responses"]["Error"];
            409: components["responses"]["Error"];
            429: components["responses"]["Error"];
            503: components["responses"]["Error"];
        };
    };
    getModelCall: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                callId: components["schemas"]["Id"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Call record. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ModelCall"];
                };
            };
            404: components["responses"]["Error"];
            503: components["responses"]["Error"];
        };
    };
    cancelModelCall: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                callId: components["schemas"]["Id"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Cancellation recorded. */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ModelCall"];
                };
            };
            404: components["responses"]["Error"];
            503: components["responses"]["Error"];
        };
    };
}
