// Scoped artifact transfer and acceptance (DD-02 §6). Trusted flows receive an
// object-scoped capability; candidates receive only an opaque handle. Finalize
// verifies the actual object version, bytes, size and hash outside DB locks.

// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             (unknown)
// source: anvilkit/control/v1/artifact.proto

package controlv1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	ArtifactService_BeginTransfer_FullMethodName    = "/anvilkit.control.v1.ArtifactService/BeginTransfer"
	ArtifactService_ResolveHandle_FullMethodName    = "/anvilkit.control.v1.ArtifactService/ResolveHandle"
	ArtifactService_FinalizeTransfer_FullMethodName = "/anvilkit.control.v1.ArtifactService/FinalizeTransfer"
	ArtifactService_GetTransfer_FullMethodName      = "/anvilkit.control.v1.ArtifactService/GetTransfer"
)

// ArtifactServiceClient is the client API for ArtifactService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type ArtifactServiceClient interface {
	BeginTransfer(ctx context.Context, in *BeginTransferRequest, opts ...grpc.CallOption) (*BeginTransferResponse, error)
	// Resolves an opaque handle to a scoped capability for a trusted caller only.
	ResolveHandle(ctx context.Context, in *ResolveHandleRequest, opts ...grpc.CallOption) (*ResolveHandleResponse, error)
	FinalizeTransfer(ctx context.Context, in *FinalizeTransferRequest, opts ...grpc.CallOption) (*FinalizeTransferResponse, error)
	GetTransfer(ctx context.Context, in *GetTransferRequest, opts ...grpc.CallOption) (*GetTransferResponse, error)
}

type artifactServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewArtifactServiceClient(cc grpc.ClientConnInterface) ArtifactServiceClient {
	return &artifactServiceClient{cc}
}

func (c *artifactServiceClient) BeginTransfer(ctx context.Context, in *BeginTransferRequest, opts ...grpc.CallOption) (*BeginTransferResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(BeginTransferResponse)
	err := c.cc.Invoke(ctx, ArtifactService_BeginTransfer_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *artifactServiceClient) ResolveHandle(ctx context.Context, in *ResolveHandleRequest, opts ...grpc.CallOption) (*ResolveHandleResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ResolveHandleResponse)
	err := c.cc.Invoke(ctx, ArtifactService_ResolveHandle_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *artifactServiceClient) FinalizeTransfer(ctx context.Context, in *FinalizeTransferRequest, opts ...grpc.CallOption) (*FinalizeTransferResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(FinalizeTransferResponse)
	err := c.cc.Invoke(ctx, ArtifactService_FinalizeTransfer_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *artifactServiceClient) GetTransfer(ctx context.Context, in *GetTransferRequest, opts ...grpc.CallOption) (*GetTransferResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetTransferResponse)
	err := c.cc.Invoke(ctx, ArtifactService_GetTransfer_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ArtifactServiceServer is the server API for ArtifactService service.
// All implementations must embed UnimplementedArtifactServiceServer
// for forward compatibility.
type ArtifactServiceServer interface {
	BeginTransfer(context.Context, *BeginTransferRequest) (*BeginTransferResponse, error)
	// Resolves an opaque handle to a scoped capability for a trusted caller only.
	ResolveHandle(context.Context, *ResolveHandleRequest) (*ResolveHandleResponse, error)
	FinalizeTransfer(context.Context, *FinalizeTransferRequest) (*FinalizeTransferResponse, error)
	GetTransfer(context.Context, *GetTransferRequest) (*GetTransferResponse, error)
	mustEmbedUnimplementedArtifactServiceServer()
}

// UnimplementedArtifactServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedArtifactServiceServer struct{}

func (UnimplementedArtifactServiceServer) BeginTransfer(context.Context, *BeginTransferRequest) (*BeginTransferResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method BeginTransfer not implemented")
}
func (UnimplementedArtifactServiceServer) ResolveHandle(context.Context, *ResolveHandleRequest) (*ResolveHandleResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ResolveHandle not implemented")
}
func (UnimplementedArtifactServiceServer) FinalizeTransfer(context.Context, *FinalizeTransferRequest) (*FinalizeTransferResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method FinalizeTransfer not implemented")
}
func (UnimplementedArtifactServiceServer) GetTransfer(context.Context, *GetTransferRequest) (*GetTransferResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetTransfer not implemented")
}
func (UnimplementedArtifactServiceServer) mustEmbedUnimplementedArtifactServiceServer() {}
func (UnimplementedArtifactServiceServer) testEmbeddedByValue()                         {}

// UnsafeArtifactServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ArtifactServiceServer will
// result in compilation errors.
type UnsafeArtifactServiceServer interface {
	mustEmbedUnimplementedArtifactServiceServer()
}

func RegisterArtifactServiceServer(s grpc.ServiceRegistrar, srv ArtifactServiceServer) {
	// If the following call panics, it indicates UnimplementedArtifactServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&ArtifactService_ServiceDesc, srv)
}

func _ArtifactService_BeginTransfer_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(BeginTransferRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ArtifactServiceServer).BeginTransfer(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ArtifactService_BeginTransfer_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ArtifactServiceServer).BeginTransfer(ctx, req.(*BeginTransferRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ArtifactService_ResolveHandle_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ResolveHandleRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ArtifactServiceServer).ResolveHandle(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ArtifactService_ResolveHandle_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ArtifactServiceServer).ResolveHandle(ctx, req.(*ResolveHandleRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ArtifactService_FinalizeTransfer_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(FinalizeTransferRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ArtifactServiceServer).FinalizeTransfer(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ArtifactService_FinalizeTransfer_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ArtifactServiceServer).FinalizeTransfer(ctx, req.(*FinalizeTransferRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ArtifactService_GetTransfer_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetTransferRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ArtifactServiceServer).GetTransfer(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ArtifactService_GetTransfer_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ArtifactServiceServer).GetTransfer(ctx, req.(*GetTransferRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// ArtifactService_ServiceDesc is the grpc.ServiceDesc for ArtifactService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var ArtifactService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "anvilkit.control.v1.ArtifactService",
	HandlerType: (*ArtifactServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "BeginTransfer",
			Handler:    _ArtifactService_BeginTransfer_Handler,
		},
		{
			MethodName: "ResolveHandle",
			Handler:    _ArtifactService_ResolveHandle_Handler,
		},
		{
			MethodName: "FinalizeTransfer",
			Handler:    _ArtifactService_FinalizeTransfer_Handler,
		},
		{
			MethodName: "GetTransfer",
			Handler:    _ArtifactService_GetTransfer_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "anvilkit/control/v1/artifact.proto",
}
