// Scoped artifact transfer and acceptance (DD-02 §6). Trusted flows receive an
// object-scoped capability; candidates receive only an opaque handle. Finalize
// verifies the actual object version, bytes, size and hash outside DB locks.
//
// Every transfer is scoped: begun under a tenant (and, when bound, an
// operation and attempt with their current execution and recovery epochs),
// read and resolved only inside that scope, and finalized only while the
// scope's epochs and deadlines are current. The capability is a short-lived
// upload authorization for exactly the declared bytes under an object key
// only Control knows; the key never appears on this surface.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        (unknown)
// source: anvilkit/control/v1/artifact.proto

package controlv1

import (
	_ "buf.build/gen/go/bufbuild/protovalidate/protocolbuffers/go/buf/validate"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ArtifactClass int32

const (
	ArtifactClass_ARTIFACT_CLASS_UNSPECIFIED ArtifactClass = 0
	ArtifactClass_ARTIFACT_CLASS_PROMPT      ArtifactClass = 1
	ArtifactClass_ARTIFACT_CLASS_BRIEF       ArtifactClass = 2
	ArtifactClass_ARTIFACT_CLASS_SOURCE      ArtifactClass = 3
	ArtifactClass_ARTIFACT_CLASS_STAGE       ArtifactClass = 4
	ArtifactClass_ARTIFACT_CLASS_RESULT      ArtifactClass = 5
	ArtifactClass_ARTIFACT_CLASS_EVIDENCE    ArtifactClass = 6
	ArtifactClass_ARTIFACT_CLASS_ANSWER      ArtifactClass = 7
	ArtifactClass_ARTIFACT_CLASS_ARGUMENT    ArtifactClass = 8
	// The build deliverables of a certified component (DD-04 §2, P10): the
	// npm tarball, the browser ES module and a stylesheet, each a finalized
	// transfer an accepted validator stage binds by exact digest and size.
	ArtifactClass_ARTIFACT_CLASS_NPM     ArtifactClass = 9
	ArtifactClass_ARTIFACT_CLASS_BROWSER ArtifactClass = 10
	ArtifactClass_ARTIFACT_CLASS_CSS     ArtifactClass = 11
)

// Enum value maps for ArtifactClass.
var (
	ArtifactClass_name = map[int32]string{
		0:  "ARTIFACT_CLASS_UNSPECIFIED",
		1:  "ARTIFACT_CLASS_PROMPT",
		2:  "ARTIFACT_CLASS_BRIEF",
		3:  "ARTIFACT_CLASS_SOURCE",
		4:  "ARTIFACT_CLASS_STAGE",
		5:  "ARTIFACT_CLASS_RESULT",
		6:  "ARTIFACT_CLASS_EVIDENCE",
		7:  "ARTIFACT_CLASS_ANSWER",
		8:  "ARTIFACT_CLASS_ARGUMENT",
		9:  "ARTIFACT_CLASS_NPM",
		10: "ARTIFACT_CLASS_BROWSER",
		11: "ARTIFACT_CLASS_CSS",
	}
	ArtifactClass_value = map[string]int32{
		"ARTIFACT_CLASS_UNSPECIFIED": 0,
		"ARTIFACT_CLASS_PROMPT":      1,
		"ARTIFACT_CLASS_BRIEF":       2,
		"ARTIFACT_CLASS_SOURCE":      3,
		"ARTIFACT_CLASS_STAGE":       4,
		"ARTIFACT_CLASS_RESULT":      5,
		"ARTIFACT_CLASS_EVIDENCE":    6,
		"ARTIFACT_CLASS_ANSWER":      7,
		"ARTIFACT_CLASS_ARGUMENT":    8,
		"ARTIFACT_CLASS_NPM":         9,
		"ARTIFACT_CLASS_BROWSER":     10,
		"ARTIFACT_CLASS_CSS":         11,
	}
)

func (x ArtifactClass) Enum() *ArtifactClass {
	p := new(ArtifactClass)
	*p = x
	return p
}

func (x ArtifactClass) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ArtifactClass) Descriptor() protoreflect.EnumDescriptor {
	return file_anvilkit_control_v1_artifact_proto_enumTypes[0].Descriptor()
}

func (ArtifactClass) Type() protoreflect.EnumType {
	return &file_anvilkit_control_v1_artifact_proto_enumTypes[0]
}

func (x ArtifactClass) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ArtifactClass.Descriptor instead.
func (ArtifactClass) EnumDescriptor() ([]byte, []int) {
	return file_anvilkit_control_v1_artifact_proto_rawDescGZIP(), []int{0}
}

type TransferState int32

const (
	TransferState_TRANSFER_STATE_UNSPECIFIED TransferState = 0
	TransferState_TRANSFER_STATE_BEGUN       TransferState = 1
	TransferState_TRANSFER_STATE_FINALIZED   TransferState = 2
	TransferState_TRANSFER_STATE_REJECTED    TransferState = 3
	TransferState_TRANSFER_STATE_EXPIRED     TransferState = 4
)

// Enum value maps for TransferState.
var (
	TransferState_name = map[int32]string{
		0: "TRANSFER_STATE_UNSPECIFIED",
		1: "TRANSFER_STATE_BEGUN",
		2: "TRANSFER_STATE_FINALIZED",
		3: "TRANSFER_STATE_REJECTED",
		4: "TRANSFER_STATE_EXPIRED",
	}
	TransferState_value = map[string]int32{
		"TRANSFER_STATE_UNSPECIFIED": 0,
		"TRANSFER_STATE_BEGUN":       1,
		"TRANSFER_STATE_FINALIZED":   2,
		"TRANSFER_STATE_REJECTED":    3,
		"TRANSFER_STATE_EXPIRED":     4,
	}
)

func (x TransferState) Enum() *TransferState {
	p := new(TransferState)
	*p = x
	return p
}

func (x TransferState) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (TransferState) Descriptor() protoreflect.EnumDescriptor {
	return file_anvilkit_control_v1_artifact_proto_enumTypes[1].Descriptor()
}

func (TransferState) Type() protoreflect.EnumType {
	return &file_anvilkit_control_v1_artifact_proto_enumTypes[1]
}

func (x TransferState) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use TransferState.Descriptor instead.
func (TransferState) EnumDescriptor() ([]byte, []int) {
	return file_anvilkit_control_v1_artifact_proto_rawDescGZIP(), []int{1}
}

type Transfer struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	TransferId     string                 `protobuf:"bytes,1,opt,name=transfer_id,json=transferId,proto3" json:"transfer_id,omitempty"`
	Handle         string                 `protobuf:"bytes,2,opt,name=handle,proto3" json:"handle,omitempty"`
	Class          ArtifactClass          `protobuf:"varint,3,opt,name=class,proto3,enum=anvilkit.control.v1.ArtifactClass" json:"class,omitempty"`
	ExpectedDigest string                 `protobuf:"bytes,4,opt,name=expected_digest,json=expectedDigest,proto3" json:"expected_digest,omitempty"`
	ExpectedSize   string                 `protobuf:"bytes,5,opt,name=expected_size,json=expectedSize,proto3" json:"expected_size,omitempty"`
	State          TransferState          `protobuf:"varint,6,opt,name=state,proto3,enum=anvilkit.control.v1.TransferState" json:"state,omitempty"`
	Deadline       *timestamppb.Timestamp `protobuf:"bytes,7,opt,name=deadline,proto3" json:"deadline,omitempty"`
	ObjectVersion  *string                `protobuf:"bytes,8,opt,name=object_version,json=objectVersion,proto3,oneof" json:"object_version,omitempty"`
	ReasonCode     *string                `protobuf:"bytes,9,opt,name=reason_code,json=reasonCode,proto3,oneof" json:"reason_code,omitempty"`
	TenantId       string                 `protobuf:"bytes,10,opt,name=tenant_id,json=tenantId,proto3" json:"tenant_id,omitempty"`
	OperationId    *string                `protobuf:"bytes,11,opt,name=operation_id,json=operationId,proto3,oneof" json:"operation_id,omitempty"`
	AttemptId      *string                `protobuf:"bytes,12,opt,name=attempt_id,json=attemptId,proto3,oneof" json:"attempt_id,omitempty"`
	MediaType      string                 `protobuf:"bytes,13,opt,name=media_type,json=mediaType,proto3" json:"media_type,omitempty"`
	// The epochs the transfer was begun under; finalization requires them to
	// be current for a bound transfer.
	ExecutionEpoch string                 `protobuf:"bytes,14,opt,name=execution_epoch,json=executionEpoch,proto3" json:"execution_epoch,omitempty"`
	RecoveryEpoch  string                 `protobuf:"bytes,15,opt,name=recovery_epoch,json=recoveryEpoch,proto3" json:"recovery_epoch,omitempty"`
	CreatedAt      *timestamppb.Timestamp `protobuf:"bytes,16,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	FinalizedAt    *timestamppb.Timestamp `protobuf:"bytes,17,opt,name=finalized_at,json=finalizedAt,proto3,oneof" json:"finalized_at,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *Transfer) Reset() {
	*x = Transfer{}
	mi := &file_anvilkit_control_v1_artifact_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Transfer) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Transfer) ProtoMessage() {}

func (x *Transfer) ProtoReflect() protoreflect.Message {
	mi := &file_anvilkit_control_v1_artifact_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Transfer.ProtoReflect.Descriptor instead.
func (*Transfer) Descriptor() ([]byte, []int) {
	return file_anvilkit_control_v1_artifact_proto_rawDescGZIP(), []int{0}
}

func (x *Transfer) GetTransferId() string {
	if x != nil {
		return x.TransferId
	}
	return ""
}

func (x *Transfer) GetHandle() string {
	if x != nil {
		return x.Handle
	}
	return ""
}

func (x *Transfer) GetClass() ArtifactClass {
	if x != nil {
		return x.Class
	}
	return ArtifactClass_ARTIFACT_CLASS_UNSPECIFIED
}

func (x *Transfer) GetExpectedDigest() string {
	if x != nil {
		return x.ExpectedDigest
	}
	return ""
}

func (x *Transfer) GetExpectedSize() string {
	if x != nil {
		return x.ExpectedSize
	}
	return ""
}

func (x *Transfer) GetState() TransferState {
	if x != nil {
		return x.State
	}
	return TransferState_TRANSFER_STATE_UNSPECIFIED
}

func (x *Transfer) GetDeadline() *timestamppb.Timestamp {
	if x != nil {
		return x.Deadline
	}
	return nil
}

func (x *Transfer) GetObjectVersion() string {
	if x != nil && x.ObjectVersion != nil {
		return *x.ObjectVersion
	}
	return ""
}

func (x *Transfer) GetReasonCode() string {
	if x != nil && x.ReasonCode != nil {
		return *x.ReasonCode
	}
	return ""
}

func (x *Transfer) GetTenantId() string {
	if x != nil {
		return x.TenantId
	}
	return ""
}

func (x *Transfer) GetOperationId() string {
	if x != nil && x.OperationId != nil {
		return *x.OperationId
	}
	return ""
}

func (x *Transfer) GetAttemptId() string {
	if x != nil && x.AttemptId != nil {
		return *x.AttemptId
	}
	return ""
}

func (x *Transfer) GetMediaType() string {
	if x != nil {
		return x.MediaType
	}
	return ""
}

func (x *Transfer) GetExecutionEpoch() string {
	if x != nil {
		return x.ExecutionEpoch
	}
	return ""
}

func (x *Transfer) GetRecoveryEpoch() string {
	if x != nil {
		return x.RecoveryEpoch
	}
	return ""
}

func (x *Transfer) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *Transfer) GetFinalizedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.FinalizedAt
	}
	return nil
}

// TransferCapability is the scoped upload authorization for one transfer:
// one request of the given method to the URL, carrying exactly the listed
// headers, with the declared bytes; it expires at expires_at and never
// outlives the transfer's deadline. It names no bucket, key or credential
// beyond what the signed URL itself carries, and it is never returned to
// candidate code.
type TransferCapability struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Url           string                 `protobuf:"bytes,1,opt,name=url,proto3" json:"url,omitempty"`
	Method        string                 `protobuf:"bytes,2,opt,name=method,proto3" json:"method,omitempty"`
	Headers       map[string]string      `protobuf:"bytes,3,rep,name=headers,proto3" json:"headers,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	ExpiresAt     *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=expires_at,json=expiresAt,proto3" json:"expires_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TransferCapability) Reset() {
	*x = TransferCapability{}
	mi := &file_anvilkit_control_v1_artifact_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TransferCapability) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TransferCapability) ProtoMessage() {}

func (x *TransferCapability) ProtoReflect() protoreflect.Message {
	mi := &file_anvilkit_control_v1_artifact_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TransferCapability.ProtoReflect.Descriptor instead.
func (*TransferCapability) Descriptor() ([]byte, []int) {
	return file_anvilkit_control_v1_artifact_proto_rawDescGZIP(), []int{1}
}

func (x *TransferCapability) GetUrl() string {
	if x != nil {
		return x.Url
	}
	return ""
}

func (x *TransferCapability) GetMethod() string {
	if x != nil {
		return x.Method
	}
	return ""
}

func (x *TransferCapability) GetHeaders() map[string]string {
	if x != nil {
		return x.Headers
	}
	return nil
}

func (x *TransferCapability) GetExpiresAt() *timestamppb.Timestamp {
	if x != nil {
		return x.ExpiresAt
	}
	return nil
}

type BeginTransferRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Command        *CommandIdentity       `protobuf:"bytes,1,opt,name=command,proto3" json:"command,omitempty"`
	Scope          *Scope                 `protobuf:"bytes,2,opt,name=scope,proto3" json:"scope,omitempty"`
	Class          ArtifactClass          `protobuf:"varint,3,opt,name=class,proto3,enum=anvilkit.control.v1.ArtifactClass" json:"class,omitempty"`
	ExpectedDigest string                 `protobuf:"bytes,4,opt,name=expected_digest,json=expectedDigest,proto3" json:"expected_digest,omitempty"`
	ExpectedSize   string                 `protobuf:"bytes,5,opt,name=expected_size,json=expectedSize,proto3" json:"expected_size,omitempty"`
	MediaType      string                 `protobuf:"bytes,6,opt,name=media_type,json=mediaType,proto3" json:"media_type,omitempty"`
	OperationId    *string                `protobuf:"bytes,7,opt,name=operation_id,json=operationId,proto3,oneof" json:"operation_id,omitempty"`
	AttemptId      *string                `protobuf:"bytes,8,opt,name=attempt_id,json=attemptId,proto3,oneof" json:"attempt_id,omitempty"`
	Deadline       *timestamppb.Timestamp `protobuf:"bytes,9,opt,name=deadline,proto3" json:"deadline,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *BeginTransferRequest) Reset() {
	*x = BeginTransferRequest{}
	mi := &file_anvilkit_control_v1_artifact_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BeginTransferRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BeginTransferRequest) ProtoMessage() {}

func (x *BeginTransferRequest) ProtoReflect() protoreflect.Message {
	mi := &file_anvilkit_control_v1_artifact_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BeginTransferRequest.ProtoReflect.Descriptor instead.
func (*BeginTransferRequest) Descriptor() ([]byte, []int) {
	return file_anvilkit_control_v1_artifact_proto_rawDescGZIP(), []int{2}
}

func (x *BeginTransferRequest) GetCommand() *CommandIdentity {
	if x != nil {
		return x.Command
	}
	return nil
}

func (x *BeginTransferRequest) GetScope() *Scope {
	if x != nil {
		return x.Scope
	}
	return nil
}

func (x *BeginTransferRequest) GetClass() ArtifactClass {
	if x != nil {
		return x.Class
	}
	return ArtifactClass_ARTIFACT_CLASS_UNSPECIFIED
}

func (x *BeginTransferRequest) GetExpectedDigest() string {
	if x != nil {
		return x.ExpectedDigest
	}
	return ""
}

func (x *BeginTransferRequest) GetExpectedSize() string {
	if x != nil {
		return x.ExpectedSize
	}
	return ""
}

func (x *BeginTransferRequest) GetMediaType() string {
	if x != nil {
		return x.MediaType
	}
	return ""
}

func (x *BeginTransferRequest) GetOperationId() string {
	if x != nil && x.OperationId != nil {
		return *x.OperationId
	}
	return ""
}

func (x *BeginTransferRequest) GetAttemptId() string {
	if x != nil && x.AttemptId != nil {
		return *x.AttemptId
	}
	return ""
}

func (x *BeginTransferRequest) GetDeadline() *timestamppb.Timestamp {
	if x != nil {
		return x.Deadline
	}
	return nil
}

type BeginTransferResponse struct {
	state    protoimpl.MessageState `protogen:"open.v1"`
	Transfer *Transfer              `protobuf:"bytes,1,opt,name=transfer,proto3" json:"transfer,omitempty"`
	Existing bool                   `protobuf:"varint,2,opt,name=existing,proto3" json:"existing,omitempty"`
	// The upload capability for a transfer that is still begun; the caller
	// (a trusted service) decides whether its own client may receive it.
	Upload        *TransferCapability `protobuf:"bytes,3,opt,name=upload,proto3" json:"upload,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BeginTransferResponse) Reset() {
	*x = BeginTransferResponse{}
	mi := &file_anvilkit_control_v1_artifact_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BeginTransferResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BeginTransferResponse) ProtoMessage() {}

func (x *BeginTransferResponse) ProtoReflect() protoreflect.Message {
	mi := &file_anvilkit_control_v1_artifact_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BeginTransferResponse.ProtoReflect.Descriptor instead.
func (*BeginTransferResponse) Descriptor() ([]byte, []int) {
	return file_anvilkit_control_v1_artifact_proto_rawDescGZIP(), []int{3}
}

func (x *BeginTransferResponse) GetTransfer() *Transfer {
	if x != nil {
		return x.Transfer
	}
	return nil
}

func (x *BeginTransferResponse) GetExisting() bool {
	if x != nil {
		return x.Existing
	}
	return false
}

func (x *BeginTransferResponse) GetUpload() *TransferCapability {
	if x != nil {
		return x.Upload
	}
	return nil
}

// ResolveHandle is the trusted harness's path from a candidate's opaque
// handle to the upload capability: the resolving physical instance must be
// the current instance of the transfer's attempt under the current epochs.
type ResolveHandleRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Handle        string                 `protobuf:"bytes,1,opt,name=handle,proto3" json:"handle,omitempty"`
	InstanceId    string                 `protobuf:"bytes,2,opt,name=instance_id,json=instanceId,proto3" json:"instance_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ResolveHandleRequest) Reset() {
	*x = ResolveHandleRequest{}
	mi := &file_anvilkit_control_v1_artifact_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResolveHandleRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResolveHandleRequest) ProtoMessage() {}

func (x *ResolveHandleRequest) ProtoReflect() protoreflect.Message {
	mi := &file_anvilkit_control_v1_artifact_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResolveHandleRequest.ProtoReflect.Descriptor instead.
func (*ResolveHandleRequest) Descriptor() ([]byte, []int) {
	return file_anvilkit_control_v1_artifact_proto_rawDescGZIP(), []int{4}
}

func (x *ResolveHandleRequest) GetHandle() string {
	if x != nil {
		return x.Handle
	}
	return ""
}

func (x *ResolveHandleRequest) GetInstanceId() string {
	if x != nil {
		return x.InstanceId
	}
	return ""
}

type ResolveHandleResponse struct {
	state    protoimpl.MessageState `protogen:"open.v1"`
	Transfer *Transfer              `protobuf:"bytes,1,opt,name=transfer,proto3" json:"transfer,omitempty"`
	// Scoped capability for the trusted sidecar; never returned to a candidate.
	// capability is the upload URL; upload carries the same URL with the
	// method and headers the request must use.
	Capability    string                 `protobuf:"bytes,2,opt,name=capability,proto3" json:"capability,omitempty"`
	ExpiresAt     *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=expires_at,json=expiresAt,proto3" json:"expires_at,omitempty"`
	Upload        *TransferCapability    `protobuf:"bytes,4,opt,name=upload,proto3" json:"upload,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ResolveHandleResponse) Reset() {
	*x = ResolveHandleResponse{}
	mi := &file_anvilkit_control_v1_artifact_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResolveHandleResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResolveHandleResponse) ProtoMessage() {}

func (x *ResolveHandleResponse) ProtoReflect() protoreflect.Message {
	mi := &file_anvilkit_control_v1_artifact_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResolveHandleResponse.ProtoReflect.Descriptor instead.
func (*ResolveHandleResponse) Descriptor() ([]byte, []int) {
	return file_anvilkit_control_v1_artifact_proto_rawDescGZIP(), []int{5}
}

func (x *ResolveHandleResponse) GetTransfer() *Transfer {
	if x != nil {
		return x.Transfer
	}
	return nil
}

func (x *ResolveHandleResponse) GetCapability() string {
	if x != nil {
		return x.Capability
	}
	return ""
}

func (x *ResolveHandleResponse) GetExpiresAt() *timestamppb.Timestamp {
	if x != nil {
		return x.ExpiresAt
	}
	return nil
}

func (x *ResolveHandleResponse) GetUpload() *TransferCapability {
	if x != nil {
		return x.Upload
	}
	return nil
}

// FinalizeTransfer names the transfer (by id or by handle) and the exact
// object version the uploader wrote; Control reads that version and
// verifies its bytes against the declared size and digest before anything
// is finalized. Caller claims, ETags and upload receipts are insufficient.
type FinalizeTransferRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Command       *CommandIdentity       `protobuf:"bytes,1,opt,name=command,proto3" json:"command,omitempty"`
	TransferId    string                 `protobuf:"bytes,2,opt,name=transfer_id,json=transferId,proto3" json:"transfer_id,omitempty"`
	ObjectVersion string                 `protobuf:"bytes,3,opt,name=object_version,json=objectVersion,proto3" json:"object_version,omitempty"`
	InstanceId    string                 `protobuf:"bytes,4,opt,name=instance_id,json=instanceId,proto3" json:"instance_id,omitempty"`
	Handle        string                 `protobuf:"bytes,5,opt,name=handle,proto3" json:"handle,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FinalizeTransferRequest) Reset() {
	*x = FinalizeTransferRequest{}
	mi := &file_anvilkit_control_v1_artifact_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FinalizeTransferRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FinalizeTransferRequest) ProtoMessage() {}

func (x *FinalizeTransferRequest) ProtoReflect() protoreflect.Message {
	mi := &file_anvilkit_control_v1_artifact_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FinalizeTransferRequest.ProtoReflect.Descriptor instead.
func (*FinalizeTransferRequest) Descriptor() ([]byte, []int) {
	return file_anvilkit_control_v1_artifact_proto_rawDescGZIP(), []int{6}
}

func (x *FinalizeTransferRequest) GetCommand() *CommandIdentity {
	if x != nil {
		return x.Command
	}
	return nil
}

func (x *FinalizeTransferRequest) GetTransferId() string {
	if x != nil {
		return x.TransferId
	}
	return ""
}

func (x *FinalizeTransferRequest) GetObjectVersion() string {
	if x != nil {
		return x.ObjectVersion
	}
	return ""
}

func (x *FinalizeTransferRequest) GetInstanceId() string {
	if x != nil {
		return x.InstanceId
	}
	return ""
}

func (x *FinalizeTransferRequest) GetHandle() string {
	if x != nil {
		return x.Handle
	}
	return ""
}

type FinalizeTransferResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Transfer      *Transfer              `protobuf:"bytes,1,opt,name=transfer,proto3" json:"transfer,omitempty"`
	Existing      bool                   `protobuf:"varint,2,opt,name=existing,proto3" json:"existing,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FinalizeTransferResponse) Reset() {
	*x = FinalizeTransferResponse{}
	mi := &file_anvilkit_control_v1_artifact_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FinalizeTransferResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FinalizeTransferResponse) ProtoMessage() {}

func (x *FinalizeTransferResponse) ProtoReflect() protoreflect.Message {
	mi := &file_anvilkit_control_v1_artifact_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FinalizeTransferResponse.ProtoReflect.Descriptor instead.
func (*FinalizeTransferResponse) Descriptor() ([]byte, []int) {
	return file_anvilkit_control_v1_artifact_proto_rawDescGZIP(), []int{7}
}

func (x *FinalizeTransferResponse) GetTransfer() *Transfer {
	if x != nil {
		return x.Transfer
	}
	return nil
}

func (x *FinalizeTransferResponse) GetExisting() bool {
	if x != nil {
		return x.Existing
	}
	return false
}

// GetTransfer reads one transfer (by id or by handle) inside the caller's
// verified scope; a transfer of another tenant is not found.
type GetTransferRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TransferId    string                 `protobuf:"bytes,1,opt,name=transfer_id,json=transferId,proto3" json:"transfer_id,omitempty"`
	Scope         *Scope                 `protobuf:"bytes,2,opt,name=scope,proto3" json:"scope,omitempty"`
	Handle        string                 `protobuf:"bytes,3,opt,name=handle,proto3" json:"handle,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetTransferRequest) Reset() {
	*x = GetTransferRequest{}
	mi := &file_anvilkit_control_v1_artifact_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetTransferRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTransferRequest) ProtoMessage() {}

func (x *GetTransferRequest) ProtoReflect() protoreflect.Message {
	mi := &file_anvilkit_control_v1_artifact_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTransferRequest.ProtoReflect.Descriptor instead.
func (*GetTransferRequest) Descriptor() ([]byte, []int) {
	return file_anvilkit_control_v1_artifact_proto_rawDescGZIP(), []int{8}
}

func (x *GetTransferRequest) GetTransferId() string {
	if x != nil {
		return x.TransferId
	}
	return ""
}

func (x *GetTransferRequest) GetScope() *Scope {
	if x != nil {
		return x.Scope
	}
	return nil
}

func (x *GetTransferRequest) GetHandle() string {
	if x != nil {
		return x.Handle
	}
	return ""
}

type GetTransferResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Transfer      *Transfer              `protobuf:"bytes,1,opt,name=transfer,proto3" json:"transfer,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetTransferResponse) Reset() {
	*x = GetTransferResponse{}
	mi := &file_anvilkit_control_v1_artifact_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetTransferResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTransferResponse) ProtoMessage() {}

func (x *GetTransferResponse) ProtoReflect() protoreflect.Message {
	mi := &file_anvilkit_control_v1_artifact_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTransferResponse.ProtoReflect.Descriptor instead.
func (*GetTransferResponse) Descriptor() ([]byte, []int) {
	return file_anvilkit_control_v1_artifact_proto_rawDescGZIP(), []int{9}
}

func (x *GetTransferResponse) GetTransfer() *Transfer {
	if x != nil {
		return x.Transfer
	}
	return nil
}

type ReadArtifactRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The artifact by handle or by transfer id (one of the two).
	Handle     string `protobuf:"bytes,1,opt,name=handle,proto3" json:"handle,omitempty"`
	TransferId string `protobuf:"bytes,2,opt,name=transfer_id,json=transferId,proto3" json:"transfer_id,omitempty"`
	// The reading operation; the relationship is checked against it.
	OperationId string `protobuf:"bytes,3,opt,name=operation_id,json=operationId,proto3" json:"operation_id,omitempty"`
	// The reading physical instance when the reader is a Job's trusted
	// sidecar; empty for the Workflow's own reads.
	InstanceId    string `protobuf:"bytes,4,opt,name=instance_id,json=instanceId,proto3" json:"instance_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReadArtifactRequest) Reset() {
	*x = ReadArtifactRequest{}
	mi := &file_anvilkit_control_v1_artifact_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReadArtifactRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReadArtifactRequest) ProtoMessage() {}

func (x *ReadArtifactRequest) ProtoReflect() protoreflect.Message {
	mi := &file_anvilkit_control_v1_artifact_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReadArtifactRequest.ProtoReflect.Descriptor instead.
func (*ReadArtifactRequest) Descriptor() ([]byte, []int) {
	return file_anvilkit_control_v1_artifact_proto_rawDescGZIP(), []int{10}
}

func (x *ReadArtifactRequest) GetHandle() string {
	if x != nil {
		return x.Handle
	}
	return ""
}

func (x *ReadArtifactRequest) GetTransferId() string {
	if x != nil {
		return x.TransferId
	}
	return ""
}

func (x *ReadArtifactRequest) GetOperationId() string {
	if x != nil {
		return x.OperationId
	}
	return ""
}

func (x *ReadArtifactRequest) GetInstanceId() string {
	if x != nil {
		return x.InstanceId
	}
	return ""
}

type ReadArtifactResponse struct {
	state    protoimpl.MessageState `protogen:"open.v1"`
	Transfer *Transfer              `protobuf:"bytes,1,opt,name=transfer,proto3" json:"transfer,omitempty"`
	// The scoped download capability of the exact object version (one GET,
	// the listed headers, valid until expires_at).
	Download      *TransferCapability `protobuf:"bytes,2,opt,name=download,proto3" json:"download,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReadArtifactResponse) Reset() {
	*x = ReadArtifactResponse{}
	mi := &file_anvilkit_control_v1_artifact_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReadArtifactResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReadArtifactResponse) ProtoMessage() {}

func (x *ReadArtifactResponse) ProtoReflect() protoreflect.Message {
	mi := &file_anvilkit_control_v1_artifact_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReadArtifactResponse.ProtoReflect.Descriptor instead.
func (*ReadArtifactResponse) Descriptor() ([]byte, []int) {
	return file_anvilkit_control_v1_artifact_proto_rawDescGZIP(), []int{11}
}

func (x *ReadArtifactResponse) GetTransfer() *Transfer {
	if x != nil {
		return x.Transfer
	}
	return nil
}

func (x *ReadArtifactResponse) GetDownload() *TransferCapability {
	if x != nil {
		return x.Download
	}
	return nil
}

var File_anvilkit_control_v1_artifact_proto protoreflect.FileDescriptor

const file_anvilkit_control_v1_artifact_proto_rawDesc = "" +
	"\n" +
	"\"anvilkit/control/v1/artifact.proto\x12\x13anvilkit.control.v1\x1a!anvilkit/control/v1/control.proto\x1a\x1bbuf/validate/validate.proto\x1a\x1fgoogle/protobuf/timestamp.proto\"\xba\x06\n" +
	"\bTransfer\x12\x1f\n" +
	"\vtransfer_id\x18\x01 \x01(\tR\n" +
	"transferId\x12\x16\n" +
	"\x06handle\x18\x02 \x01(\tR\x06handle\x128\n" +
	"\x05class\x18\x03 \x01(\x0e2\".anvilkit.control.v1.ArtifactClassR\x05class\x12'\n" +
	"\x0fexpected_digest\x18\x04 \x01(\tR\x0eexpectedDigest\x12#\n" +
	"\rexpected_size\x18\x05 \x01(\tR\fexpectedSize\x128\n" +
	"\x05state\x18\x06 \x01(\x0e2\".anvilkit.control.v1.TransferStateR\x05state\x126\n" +
	"\bdeadline\x18\a \x01(\v2\x1a.google.protobuf.TimestampR\bdeadline\x12*\n" +
	"\x0eobject_version\x18\b \x01(\tH\x00R\robjectVersion\x88\x01\x01\x12$\n" +
	"\vreason_code\x18\t \x01(\tH\x01R\n" +
	"reasonCode\x88\x01\x01\x12\x1b\n" +
	"\ttenant_id\x18\n" +
	" \x01(\tR\btenantId\x12&\n" +
	"\foperation_id\x18\v \x01(\tH\x02R\voperationId\x88\x01\x01\x12\"\n" +
	"\n" +
	"attempt_id\x18\f \x01(\tH\x03R\tattemptId\x88\x01\x01\x12\x1d\n" +
	"\n" +
	"media_type\x18\r \x01(\tR\tmediaType\x12'\n" +
	"\x0fexecution_epoch\x18\x0e \x01(\tR\x0eexecutionEpoch\x12%\n" +
	"\x0erecovery_epoch\x18\x0f \x01(\tR\rrecoveryEpoch\x129\n" +
	"\n" +
	"created_at\x18\x10 \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x12B\n" +
	"\ffinalized_at\x18\x11 \x01(\v2\x1a.google.protobuf.TimestampH\x04R\vfinalizedAt\x88\x01\x01B\x11\n" +
	"\x0f_object_versionB\x0e\n" +
	"\f_reason_codeB\x0f\n" +
	"\r_operation_idB\r\n" +
	"\v_attempt_idB\x0f\n" +
	"\r_finalized_at\"\x85\x02\n" +
	"\x12TransferCapability\x12\x10\n" +
	"\x03url\x18\x01 \x01(\tR\x03url\x12\x16\n" +
	"\x06method\x18\x02 \x01(\tR\x06method\x12N\n" +
	"\aheaders\x18\x03 \x03(\v24.anvilkit.control.v1.TransferCapability.HeadersEntryR\aheaders\x129\n" +
	"\n" +
	"expires_at\x18\x04 \x01(\v2\x1a.google.protobuf.TimestampR\texpiresAt\x1a:\n" +
	"\fHeadersEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\xd4\x04\n" +
	"\x14BeginTransferRequest\x12F\n" +
	"\acommand\x18\x01 \x01(\v2$.anvilkit.control.v1.CommandIdentityB\x06\xbaH\x03\xc8\x01\x01R\acommand\x128\n" +
	"\x05scope\x18\x02 \x01(\v2\x1a.anvilkit.control.v1.ScopeB\x06\xbaH\x03\xc8\x01\x01R\x05scope\x12D\n" +
	"\x05class\x18\x03 \x01(\x0e2\".anvilkit.control.v1.ArtifactClassB\n" +
	"\xbaH\a\x82\x01\x04\x10\x01 \x00R\x05class\x12E\n" +
	"\x0fexpected_digest\x18\x04 \x01(\tB\x1c\xbaH\x19r\x172\x15^sha256:[0-9a-f]{64}$R\x0eexpectedDigest\x12B\n" +
	"\rexpected_size\x18\x05 \x01(\tB\x1d\xbaH\x1ar\x182\x16^(0|[1-9][0-9]{0,19})$R\fexpectedSize\x12)\n" +
	"\n" +
	"media_type\x18\x06 \x01(\tB\n" +
	"\xbaH\ar\x05\x10\x01\x18\x80\x01R\tmediaType\x120\n" +
	"\foperation_id\x18\a \x01(\tB\b\xbaH\x05r\x03\x18\x80\x01H\x00R\voperationId\x88\x01\x01\x12,\n" +
	"\n" +
	"attempt_id\x18\b \x01(\tB\b\xbaH\x05r\x03\x18\x80\x01H\x01R\tattemptId\x88\x01\x01\x12>\n" +
	"\bdeadline\x18\t \x01(\v2\x1a.google.protobuf.TimestampB\x06\xbaH\x03\xc8\x01\x01R\bdeadlineB\x0f\n" +
	"\r_operation_idB\r\n" +
	"\v_attempt_id\"\xaf\x01\n" +
	"\x15BeginTransferResponse\x129\n" +
	"\btransfer\x18\x01 \x01(\v2\x1d.anvilkit.control.v1.TransferR\btransfer\x12\x1a\n" +
	"\bexisting\x18\x02 \x01(\bR\bexisting\x12?\n" +
	"\x06upload\x18\x03 \x01(\v2'.anvilkit.control.v1.TransferCapabilityR\x06upload\"g\n" +
	"\x14ResolveHandleRequest\x12\"\n" +
	"\x06handle\x18\x01 \x01(\tB\n" +
	"\xbaH\ar\x05\x10\x01\x18\x80\x02R\x06handle\x12+\n" +
	"\vinstance_id\x18\x02 \x01(\tB\n" +
	"\xbaH\ar\x05\x10\x01\x18\x80\x01R\n" +
	"instanceId\"\xee\x01\n" +
	"\x15ResolveHandleResponse\x129\n" +
	"\btransfer\x18\x01 \x01(\v2\x1d.anvilkit.control.v1.TransferR\btransfer\x12\x1e\n" +
	"\n" +
	"capability\x18\x02 \x01(\tR\n" +
	"capability\x129\n" +
	"\n" +
	"expires_at\x18\x03 \x01(\v2\x1a.google.protobuf.TimestampR\texpiresAt\x12?\n" +
	"\x06upload\x18\x04 \x01(\v2'.anvilkit.control.v1.TransferCapabilityR\x06upload\"\x8c\x02\n" +
	"\x17FinalizeTransferRequest\x12F\n" +
	"\acommand\x18\x01 \x01(\v2$.anvilkit.control.v1.CommandIdentityB\x06\xbaH\x03\xc8\x01\x01R\acommand\x12)\n" +
	"\vtransfer_id\x18\x02 \x01(\tB\b\xbaH\x05r\x03\x18\x80\x01R\n" +
	"transferId\x121\n" +
	"\x0eobject_version\x18\x03 \x01(\tB\n" +
	"\xbaH\ar\x05\x10\x01\x18\x80\x02R\robjectVersion\x12)\n" +
	"\vinstance_id\x18\x04 \x01(\tB\b\xbaH\x05r\x03\x18\x80\x01R\n" +
	"instanceId\x12 \n" +
	"\x06handle\x18\x05 \x01(\tB\b\xbaH\x05r\x03\x18\x80\x02R\x06handle\"q\n" +
	"\x18FinalizeTransferResponse\x129\n" +
	"\btransfer\x18\x01 \x01(\v2\x1d.anvilkit.control.v1.TransferR\btransfer\x12\x1a\n" +
	"\bexisting\x18\x02 \x01(\bR\bexisting\"\x9b\x01\n" +
	"\x12GetTransferRequest\x12)\n" +
	"\vtransfer_id\x18\x01 \x01(\tB\b\xbaH\x05r\x03\x18\x80\x01R\n" +
	"transferId\x128\n" +
	"\x05scope\x18\x02 \x01(\v2\x1a.anvilkit.control.v1.ScopeB\x06\xbaH\x03\xc8\x01\x01R\x05scope\x12 \n" +
	"\x06handle\x18\x03 \x01(\tB\b\xbaH\x05r\x03\x18\x80\x02R\x06handle\"P\n" +
	"\x13GetTransferResponse\x129\n" +
	"\btransfer\x18\x01 \x01(\v2\x1d.anvilkit.control.v1.TransferR\btransfer\"\xbc\x01\n" +
	"\x13ReadArtifactRequest\x12 \n" +
	"\x06handle\x18\x01 \x01(\tB\b\xbaH\x05r\x03\x18\x80\x02R\x06handle\x12)\n" +
	"\vtransfer_id\x18\x02 \x01(\tB\b\xbaH\x05r\x03\x18\x80\x01R\n" +
	"transferId\x12-\n" +
	"\foperation_id\x18\x03 \x01(\tB\n" +
	"\xbaH\ar\x05\x10\x01\x18\x80\x01R\voperationId\x12)\n" +
	"\vinstance_id\x18\x04 \x01(\tB\b\xbaH\x05r\x03\x18\x80\x01R\n" +
	"instanceId\"\x96\x01\n" +
	"\x14ReadArtifactResponse\x129\n" +
	"\btransfer\x18\x01 \x01(\v2\x1d.anvilkit.control.v1.TransferR\btransfer\x12C\n" +
	"\bdownload\x18\x02 \x01(\v2'.anvilkit.control.v1.TransferCapabilityR\bdownload*\xd5\x02\n" +
	"\rArtifactClass\x12\x1e\n" +
	"\x1aARTIFACT_CLASS_UNSPECIFIED\x10\x00\x12\x19\n" +
	"\x15ARTIFACT_CLASS_PROMPT\x10\x01\x12\x18\n" +
	"\x14ARTIFACT_CLASS_BRIEF\x10\x02\x12\x19\n" +
	"\x15ARTIFACT_CLASS_SOURCE\x10\x03\x12\x18\n" +
	"\x14ARTIFACT_CLASS_STAGE\x10\x04\x12\x19\n" +
	"\x15ARTIFACT_CLASS_RESULT\x10\x05\x12\x1b\n" +
	"\x17ARTIFACT_CLASS_EVIDENCE\x10\x06\x12\x19\n" +
	"\x15ARTIFACT_CLASS_ANSWER\x10\a\x12\x1b\n" +
	"\x17ARTIFACT_CLASS_ARGUMENT\x10\b\x12\x16\n" +
	"\x12ARTIFACT_CLASS_NPM\x10\t\x12\x1a\n" +
	"\x16ARTIFACT_CLASS_BROWSER\x10\n" +
	"\x12\x16\n" +
	"\x12ARTIFACT_CLASS_CSS\x10\v*\xa0\x01\n" +
	"\rTransferState\x12\x1e\n" +
	"\x1aTRANSFER_STATE_UNSPECIFIED\x10\x00\x12\x18\n" +
	"\x14TRANSFER_STATE_BEGUN\x10\x01\x12\x1c\n" +
	"\x18TRANSFER_STATE_FINALIZED\x10\x02\x12\x1b\n" +
	"\x17TRANSFER_STATE_REJECTED\x10\x03\x12\x1a\n" +
	"\x16TRANSFER_STATE_EXPIRED\x10\x042\x99\x04\n" +
	"\x0fArtifactService\x12f\n" +
	"\rBeginTransfer\x12).anvilkit.control.v1.BeginTransferRequest\x1a*.anvilkit.control.v1.BeginTransferResponse\x12f\n" +
	"\rResolveHandle\x12).anvilkit.control.v1.ResolveHandleRequest\x1a*.anvilkit.control.v1.ResolveHandleResponse\x12o\n" +
	"\x10FinalizeTransfer\x12,.anvilkit.control.v1.FinalizeTransferRequest\x1a-.anvilkit.control.v1.FinalizeTransferResponse\x12`\n" +
	"\vGetTransfer\x12'.anvilkit.control.v1.GetTransferRequest\x1a(.anvilkit.control.v1.GetTransferResponse\x12c\n" +
	"\fReadArtifact\x12(.anvilkit.control.v1.ReadArtifactRequest\x1a).anvilkit.control.v1.ReadArtifactResponseB\xe5\x01\n" +
	"\x17com.anvilkit.control.v1B\rArtifactProtoP\x01ZMgithub.com/ancyloce/anvilkit-agent-contracts/go/anvilkit/control/v1;controlv1\xa2\x02\x03ACX\xaa\x02\x13Anvilkit.Control.V1\xca\x02\x13Anvilkit\\Control\\V1\xe2\x02\x1fAnvilkit\\Control\\V1\\GPBMetadata\xea\x02\x15Anvilkit::Control::V1b\x06proto3"

var (
	file_anvilkit_control_v1_artifact_proto_rawDescOnce sync.Once
	file_anvilkit_control_v1_artifact_proto_rawDescData []byte
)

func file_anvilkit_control_v1_artifact_proto_rawDescGZIP() []byte {
	file_anvilkit_control_v1_artifact_proto_rawDescOnce.Do(func() {
		file_anvilkit_control_v1_artifact_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_anvilkit_control_v1_artifact_proto_rawDesc), len(file_anvilkit_control_v1_artifact_proto_rawDesc)))
	})
	return file_anvilkit_control_v1_artifact_proto_rawDescData
}

var file_anvilkit_control_v1_artifact_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_anvilkit_control_v1_artifact_proto_msgTypes = make([]protoimpl.MessageInfo, 13)
var file_anvilkit_control_v1_artifact_proto_goTypes = []any{
	(ArtifactClass)(0),               // 0: anvilkit.control.v1.ArtifactClass
	(TransferState)(0),               // 1: anvilkit.control.v1.TransferState
	(*Transfer)(nil),                 // 2: anvilkit.control.v1.Transfer
	(*TransferCapability)(nil),       // 3: anvilkit.control.v1.TransferCapability
	(*BeginTransferRequest)(nil),     // 4: anvilkit.control.v1.BeginTransferRequest
	(*BeginTransferResponse)(nil),    // 5: anvilkit.control.v1.BeginTransferResponse
	(*ResolveHandleRequest)(nil),     // 6: anvilkit.control.v1.ResolveHandleRequest
	(*ResolveHandleResponse)(nil),    // 7: anvilkit.control.v1.ResolveHandleResponse
	(*FinalizeTransferRequest)(nil),  // 8: anvilkit.control.v1.FinalizeTransferRequest
	(*FinalizeTransferResponse)(nil), // 9: anvilkit.control.v1.FinalizeTransferResponse
	(*GetTransferRequest)(nil),       // 10: anvilkit.control.v1.GetTransferRequest
	(*GetTransferResponse)(nil),      // 11: anvilkit.control.v1.GetTransferResponse
	(*ReadArtifactRequest)(nil),      // 12: anvilkit.control.v1.ReadArtifactRequest
	(*ReadArtifactResponse)(nil),     // 13: anvilkit.control.v1.ReadArtifactResponse
	nil,                              // 14: anvilkit.control.v1.TransferCapability.HeadersEntry
	(*timestamppb.Timestamp)(nil),    // 15: google.protobuf.Timestamp
	(*CommandIdentity)(nil),          // 16: anvilkit.control.v1.CommandIdentity
	(*Scope)(nil),                    // 17: anvilkit.control.v1.Scope
}
var file_anvilkit_control_v1_artifact_proto_depIdxs = []int32{
	0,  // 0: anvilkit.control.v1.Transfer.class:type_name -> anvilkit.control.v1.ArtifactClass
	1,  // 1: anvilkit.control.v1.Transfer.state:type_name -> anvilkit.control.v1.TransferState
	15, // 2: anvilkit.control.v1.Transfer.deadline:type_name -> google.protobuf.Timestamp
	15, // 3: anvilkit.control.v1.Transfer.created_at:type_name -> google.protobuf.Timestamp
	15, // 4: anvilkit.control.v1.Transfer.finalized_at:type_name -> google.protobuf.Timestamp
	14, // 5: anvilkit.control.v1.TransferCapability.headers:type_name -> anvilkit.control.v1.TransferCapability.HeadersEntry
	15, // 6: anvilkit.control.v1.TransferCapability.expires_at:type_name -> google.protobuf.Timestamp
	16, // 7: anvilkit.control.v1.BeginTransferRequest.command:type_name -> anvilkit.control.v1.CommandIdentity
	17, // 8: anvilkit.control.v1.BeginTransferRequest.scope:type_name -> anvilkit.control.v1.Scope
	0,  // 9: anvilkit.control.v1.BeginTransferRequest.class:type_name -> anvilkit.control.v1.ArtifactClass
	15, // 10: anvilkit.control.v1.BeginTransferRequest.deadline:type_name -> google.protobuf.Timestamp
	2,  // 11: anvilkit.control.v1.BeginTransferResponse.transfer:type_name -> anvilkit.control.v1.Transfer
	3,  // 12: anvilkit.control.v1.BeginTransferResponse.upload:type_name -> anvilkit.control.v1.TransferCapability
	2,  // 13: anvilkit.control.v1.ResolveHandleResponse.transfer:type_name -> anvilkit.control.v1.Transfer
	15, // 14: anvilkit.control.v1.ResolveHandleResponse.expires_at:type_name -> google.protobuf.Timestamp
	3,  // 15: anvilkit.control.v1.ResolveHandleResponse.upload:type_name -> anvilkit.control.v1.TransferCapability
	16, // 16: anvilkit.control.v1.FinalizeTransferRequest.command:type_name -> anvilkit.control.v1.CommandIdentity
	2,  // 17: anvilkit.control.v1.FinalizeTransferResponse.transfer:type_name -> anvilkit.control.v1.Transfer
	17, // 18: anvilkit.control.v1.GetTransferRequest.scope:type_name -> anvilkit.control.v1.Scope
	2,  // 19: anvilkit.control.v1.GetTransferResponse.transfer:type_name -> anvilkit.control.v1.Transfer
	2,  // 20: anvilkit.control.v1.ReadArtifactResponse.transfer:type_name -> anvilkit.control.v1.Transfer
	3,  // 21: anvilkit.control.v1.ReadArtifactResponse.download:type_name -> anvilkit.control.v1.TransferCapability
	4,  // 22: anvilkit.control.v1.ArtifactService.BeginTransfer:input_type -> anvilkit.control.v1.BeginTransferRequest
	6,  // 23: anvilkit.control.v1.ArtifactService.ResolveHandle:input_type -> anvilkit.control.v1.ResolveHandleRequest
	8,  // 24: anvilkit.control.v1.ArtifactService.FinalizeTransfer:input_type -> anvilkit.control.v1.FinalizeTransferRequest
	10, // 25: anvilkit.control.v1.ArtifactService.GetTransfer:input_type -> anvilkit.control.v1.GetTransferRequest
	12, // 26: anvilkit.control.v1.ArtifactService.ReadArtifact:input_type -> anvilkit.control.v1.ReadArtifactRequest
	5,  // 27: anvilkit.control.v1.ArtifactService.BeginTransfer:output_type -> anvilkit.control.v1.BeginTransferResponse
	7,  // 28: anvilkit.control.v1.ArtifactService.ResolveHandle:output_type -> anvilkit.control.v1.ResolveHandleResponse
	9,  // 29: anvilkit.control.v1.ArtifactService.FinalizeTransfer:output_type -> anvilkit.control.v1.FinalizeTransferResponse
	11, // 30: anvilkit.control.v1.ArtifactService.GetTransfer:output_type -> anvilkit.control.v1.GetTransferResponse
	13, // 31: anvilkit.control.v1.ArtifactService.ReadArtifact:output_type -> anvilkit.control.v1.ReadArtifactResponse
	27, // [27:32] is the sub-list for method output_type
	22, // [22:27] is the sub-list for method input_type
	22, // [22:22] is the sub-list for extension type_name
	22, // [22:22] is the sub-list for extension extendee
	0,  // [0:22] is the sub-list for field type_name
}

func init() { file_anvilkit_control_v1_artifact_proto_init() }
func file_anvilkit_control_v1_artifact_proto_init() {
	if File_anvilkit_control_v1_artifact_proto != nil {
		return
	}
	file_anvilkit_control_v1_control_proto_init()
	file_anvilkit_control_v1_artifact_proto_msgTypes[0].OneofWrappers = []any{}
	file_anvilkit_control_v1_artifact_proto_msgTypes[2].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_anvilkit_control_v1_artifact_proto_rawDesc), len(file_anvilkit_control_v1_artifact_proto_rawDesc)),
			NumEnums:      2,
			NumMessages:   13,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_anvilkit_control_v1_artifact_proto_goTypes,
		DependencyIndexes: file_anvilkit_control_v1_artifact_proto_depIdxs,
		EnumInfos:         file_anvilkit_control_v1_artifact_proto_enumTypes,
		MessageInfos:      file_anvilkit_control_v1_artifact_proto_msgTypes,
	}.Build()
	File_anvilkit_control_v1_artifact_proto = out.File
	file_anvilkit_control_v1_artifact_proto_goTypes = nil
	file_anvilkit_control_v1_artifact_proto_depIdxs = nil
}
