// Generation admission and bootstrap (DD-01 §4, DD-02 §2–§3, delivery.md
// P13): the bounded execution queue with its permit that sets the active
// deadline once, the lease the protected supervisor reports (only confirmed
// results reach Control; an unknown renewal never extends known validity and
// a confirmed loss fences new sends for good), the funding of the operation
// from the shared budget pools under a stable occurrence, and the supported
// control commands relayed as tracked Updates. Control never chooses the
// next business action: the Workflow asks, Control decides and records.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        (unknown)
// source: anvilkit/control/v1/generation.proto

package controlv1

import (
	_ "buf.build/gen/go/bufbuild/protovalidate/protocolbuffers/go/buf/validate"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type PermitState int32

const (
	PermitState_PERMIT_STATE_UNSPECIFIED         PermitState = 0
	PermitState_PERMIT_STATE_ACTIVE              PermitState = 1
	PermitState_PERMIT_STATE_RELEASED            PermitState = 2
	PermitState_PERMIT_STATE_EXPIRED_UNCONFIRMED PermitState = 3
)

// Enum value maps for PermitState.
var (
	PermitState_name = map[int32]string{
		0: "PERMIT_STATE_UNSPECIFIED",
		1: "PERMIT_STATE_ACTIVE",
		2: "PERMIT_STATE_RELEASED",
		3: "PERMIT_STATE_EXPIRED_UNCONFIRMED",
	}
	PermitState_value = map[string]int32{
		"PERMIT_STATE_UNSPECIFIED":         0,
		"PERMIT_STATE_ACTIVE":              1,
		"PERMIT_STATE_RELEASED":            2,
		"PERMIT_STATE_EXPIRED_UNCONFIRMED": 3,
	}
)

func (x PermitState) Enum() *PermitState {
	p := new(PermitState)
	*p = x
	return p
}

func (x PermitState) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (PermitState) Descriptor() protoreflect.EnumDescriptor {
	return file_anvilkit_control_v1_generation_proto_enumTypes[0].Descriptor()
}

func (PermitState) Type() protoreflect.EnumType {
	return &file_anvilkit_control_v1_generation_proto_enumTypes[0]
}

func (x PermitState) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use PermitState.Descriptor instead.
func (PermitState) EnumDescriptor() ([]byte, []int) {
	return file_anvilkit_control_v1_generation_proto_rawDescGZIP(), []int{0}
}

// LeaseState is what the protected supervisor confirmed about the source
// lease of a Generation.
type LeaseState int32

const (
	LeaseState_LEASE_STATE_UNSPECIFIED LeaseState = 0
	LeaseState_LEASE_STATE_NONE        LeaseState = 1
	LeaseState_LEASE_STATE_HELD        LeaseState = 2
	LeaseState_LEASE_STATE_LOST        LeaseState = 3
	LeaseState_LEASE_STATE_RELEASED    LeaseState = 4
)

// Enum value maps for LeaseState.
var (
	LeaseState_name = map[int32]string{
		0: "LEASE_STATE_UNSPECIFIED",
		1: "LEASE_STATE_NONE",
		2: "LEASE_STATE_HELD",
		3: "LEASE_STATE_LOST",
		4: "LEASE_STATE_RELEASED",
	}
	LeaseState_value = map[string]int32{
		"LEASE_STATE_UNSPECIFIED": 0,
		"LEASE_STATE_NONE":        1,
		"LEASE_STATE_HELD":        2,
		"LEASE_STATE_LOST":        3,
		"LEASE_STATE_RELEASED":    4,
	}
)

func (x LeaseState) Enum() *LeaseState {
	p := new(LeaseState)
	*p = x
	return p
}

func (x LeaseState) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (LeaseState) Descriptor() protoreflect.EnumDescriptor {
	return file_anvilkit_control_v1_generation_proto_enumTypes[1].Descriptor()
}

func (LeaseState) Type() protoreflect.EnumType {
	return &file_anvilkit_control_v1_generation_proto_enumTypes[1]
}

func (x LeaseState) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use LeaseState.Descriptor instead.
func (LeaseState) EnumDescriptor() ([]byte, []int) {
	return file_anvilkit_control_v1_generation_proto_rawDescGZIP(), []int{1}
}

type ExecutionPermit struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PermitId      string                 `protobuf:"bytes,1,opt,name=permit_id,json=permitId,proto3" json:"permit_id,omitempty"`
	PoolId        string                 `protobuf:"bytes,2,opt,name=pool_id,json=poolId,proto3" json:"pool_id,omitempty"`
	OperationId   string                 `protobuf:"bytes,3,opt,name=operation_id,json=operationId,proto3" json:"operation_id,omitempty"`
	FenceEpoch    string                 `protobuf:"bytes,4,opt,name=fence_epoch,json=fenceEpoch,proto3" json:"fence_epoch,omitempty"`
	State         PermitState            `protobuf:"varint,5,opt,name=state,proto3,enum=anvilkit.control.v1.PermitState" json:"state,omitempty"`
	GrantedAt     *timestamppb.Timestamp `protobuf:"bytes,6,opt,name=granted_at,json=grantedAt,proto3" json:"granted_at,omitempty"`
	ReleasedAt    *timestamppb.Timestamp `protobuf:"bytes,7,opt,name=released_at,json=releasedAt,proto3,oneof" json:"released_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ExecutionPermit) Reset() {
	*x = ExecutionPermit{}
	mi := &file_anvilkit_control_v1_generation_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExecutionPermit) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExecutionPermit) ProtoMessage() {}

func (x *ExecutionPermit) ProtoReflect() protoreflect.Message {
	mi := &file_anvilkit_control_v1_generation_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExecutionPermit.ProtoReflect.Descriptor instead.
func (*ExecutionPermit) Descriptor() ([]byte, []int) {
	return file_anvilkit_control_v1_generation_proto_rawDescGZIP(), []int{0}
}

func (x *ExecutionPermit) GetPermitId() string {
	if x != nil {
		return x.PermitId
	}
	return ""
}

func (x *ExecutionPermit) GetPoolId() string {
	if x != nil {
		return x.PoolId
	}
	return ""
}

func (x *ExecutionPermit) GetOperationId() string {
	if x != nil {
		return x.OperationId
	}
	return ""
}

func (x *ExecutionPermit) GetFenceEpoch() string {
	if x != nil {
		return x.FenceEpoch
	}
	return ""
}

func (x *ExecutionPermit) GetState() PermitState {
	if x != nil {
		return x.State
	}
	return PermitState_PERMIT_STATE_UNSPECIFIED
}

func (x *ExecutionPermit) GetGrantedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.GrantedAt
	}
	return nil
}

func (x *ExecutionPermit) GetReleasedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.ReleasedAt
	}
	return nil
}

type LeaseRecord struct {
	state   protoimpl.MessageState `protogen:"open.v1"`
	State   LeaseState             `protobuf:"varint,1,opt,name=state,proto3,enum=anvilkit.control.v1.LeaseState" json:"state,omitempty"`
	LeaseId string                 `protobuf:"bytes,2,opt,name=lease_id,json=leaseId,proto3" json:"lease_id,omitempty"`
	Fence   string                 `protobuf:"bytes,3,opt,name=fence,proto3" json:"fence,omitempty"`
	// The last confirmed expiry; an unknown renewal never moves it.
	ExpiresAt *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=expires_at,json=expiresAt,proto3,oneof" json:"expires_at,omitempty"`
	// The occurrence of the last confirmed report.
	Occurrence    string `protobuf:"bytes,5,opt,name=occurrence,proto3" json:"occurrence,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LeaseRecord) Reset() {
	*x = LeaseRecord{}
	mi := &file_anvilkit_control_v1_generation_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LeaseRecord) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LeaseRecord) ProtoMessage() {}

func (x *LeaseRecord) ProtoReflect() protoreflect.Message {
	mi := &file_anvilkit_control_v1_generation_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LeaseRecord.ProtoReflect.Descriptor instead.
func (*LeaseRecord) Descriptor() ([]byte, []int) {
	return file_anvilkit_control_v1_generation_proto_rawDescGZIP(), []int{1}
}

func (x *LeaseRecord) GetState() LeaseState {
	if x != nil {
		return x.State
	}
	return LeaseState_LEASE_STATE_UNSPECIFIED
}

func (x *LeaseRecord) GetLeaseId() string {
	if x != nil {
		return x.LeaseId
	}
	return ""
}

func (x *LeaseRecord) GetFence() string {
	if x != nil {
		return x.Fence
	}
	return ""
}

func (x *LeaseRecord) GetExpiresAt() *timestamppb.Timestamp {
	if x != nil {
		return x.ExpiresAt
	}
	return nil
}

func (x *LeaseRecord) GetOccurrence() string {
	if x != nil {
		return x.Occurrence
	}
	return ""
}

// Generation is the admission and bootstrap record of a Generation.
type Generation struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	OperationId    string                 `protobuf:"bytes,1,opt,name=operation_id,json=operationId,proto3" json:"operation_id,omitempty"`
	TenantId       string                 `protobuf:"bytes,2,opt,name=tenant_id,json=tenantId,proto3" json:"tenant_id,omitempty"`
	Brief          *Brief                 `protobuf:"bytes,3,opt,name=brief,proto3" json:"brief,omitempty"`
	Permit         *ExecutionPermit       `protobuf:"bytes,4,opt,name=permit,proto3,oneof" json:"permit,omitempty"`
	ActiveDeadline *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=active_deadline,json=activeDeadline,proto3,oneof" json:"active_deadline,omitempty"`
	// queue_deadline is the original deadline of intake: admission waiting
	// never extends it.
	QueueDeadline *timestamppb.Timestamp `protobuf:"bytes,6,opt,name=queue_deadline,json=queueDeadline,proto3" json:"queue_deadline,omitempty"`
	Lease         *LeaseRecord           `protobuf:"bytes,7,opt,name=lease,proto3" json:"lease,omitempty"`
	Funding       *Money                 `protobuf:"bytes,8,opt,name=funding,proto3,oneof" json:"funding,omitempty"`
	// definition_activation is the reviewed definition the operation runs
	// under; a tracked change_definition command moves it.
	DefinitionActivation string `protobuf:"bytes,9,opt,name=definition_activation,json=definitionActivation,proto3" json:"definition_activation,omitempty"`
	// The reviewed bounds of the profile.
	MaxRepairs         string  `protobuf:"bytes,10,opt,name=max_repairs,json=maxRepairs,proto3" json:"max_repairs,omitempty"`
	CodegenProfileId   string  `protobuf:"bytes,11,opt,name=codegen_profile_id,json=codegenProfileId,proto3" json:"codegen_profile_id,omitempty"`
	ValidatorProfileId string  `protobuf:"bytes,12,opt,name=validator_profile_id,json=validatorProfileId,proto3" json:"validator_profile_id,omitempty"`
	CandidateEffectId  *string `protobuf:"bytes,13,opt,name=candidate_effect_id,json=candidateEffectId,proto3,oneof" json:"candidate_effect_id,omitempty"`
	// The exact subject the operation was accepted for (the lease subject).
	Subject       *OperationSubject `protobuf:"bytes,14,opt,name=subject,proto3" json:"subject,omitempty"`
	ActorId       string            `protobuf:"bytes,15,opt,name=actor_id,json=actorId,proto3" json:"actor_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Generation) Reset() {
	*x = Generation{}
	mi := &file_anvilkit_control_v1_generation_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Generation) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Generation) ProtoMessage() {}

func (x *Generation) ProtoReflect() protoreflect.Message {
	mi := &file_anvilkit_control_v1_generation_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Generation.ProtoReflect.Descriptor instead.
func (*Generation) Descriptor() ([]byte, []int) {
	return file_anvilkit_control_v1_generation_proto_rawDescGZIP(), []int{2}
}

func (x *Generation) GetOperationId() string {
	if x != nil {
		return x.OperationId
	}
	return ""
}

func (x *Generation) GetTenantId() string {
	if x != nil {
		return x.TenantId
	}
	return ""
}

func (x *Generation) GetBrief() *Brief {
	if x != nil {
		return x.Brief
	}
	return nil
}

func (x *Generation) GetPermit() *ExecutionPermit {
	if x != nil {
		return x.Permit
	}
	return nil
}

func (x *Generation) GetActiveDeadline() *timestamppb.Timestamp {
	if x != nil {
		return x.ActiveDeadline
	}
	return nil
}

func (x *Generation) GetQueueDeadline() *timestamppb.Timestamp {
	if x != nil {
		return x.QueueDeadline
	}
	return nil
}

func (x *Generation) GetLease() *LeaseRecord {
	if x != nil {
		return x.Lease
	}
	return nil
}

func (x *Generation) GetFunding() *Money {
	if x != nil {
		return x.Funding
	}
	return nil
}

func (x *Generation) GetDefinitionActivation() string {
	if x != nil {
		return x.DefinitionActivation
	}
	return ""
}

func (x *Generation) GetMaxRepairs() string {
	if x != nil {
		return x.MaxRepairs
	}
	return ""
}

func (x *Generation) GetCodegenProfileId() string {
	if x != nil {
		return x.CodegenProfileId
	}
	return ""
}

func (x *Generation) GetValidatorProfileId() string {
	if x != nil {
		return x.ValidatorProfileId
	}
	return ""
}

func (x *Generation) GetCandidateEffectId() string {
	if x != nil && x.CandidateEffectId != nil {
		return *x.CandidateEffectId
	}
	return ""
}

func (x *Generation) GetSubject() *OperationSubject {
	if x != nil {
		return x.Subject
	}
	return nil
}

func (x *Generation) GetActorId() string {
	if x != nil {
		return x.ActorId
	}
	return ""
}

type GetGenerationRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TenantId      string                 `protobuf:"bytes,1,opt,name=tenant_id,json=tenantId,proto3" json:"tenant_id,omitempty"`
	OperationId   string                 `protobuf:"bytes,2,opt,name=operation_id,json=operationId,proto3" json:"operation_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetGenerationRequest) Reset() {
	*x = GetGenerationRequest{}
	mi := &file_anvilkit_control_v1_generation_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetGenerationRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetGenerationRequest) ProtoMessage() {}

func (x *GetGenerationRequest) ProtoReflect() protoreflect.Message {
	mi := &file_anvilkit_control_v1_generation_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetGenerationRequest.ProtoReflect.Descriptor instead.
func (*GetGenerationRequest) Descriptor() ([]byte, []int) {
	return file_anvilkit_control_v1_generation_proto_rawDescGZIP(), []int{3}
}

func (x *GetGenerationRequest) GetTenantId() string {
	if x != nil {
		return x.TenantId
	}
	return ""
}

func (x *GetGenerationRequest) GetOperationId() string {
	if x != nil {
		return x.OperationId
	}
	return ""
}

type GetGenerationResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Generation    *Generation            `protobuf:"bytes,1,opt,name=generation,proto3" json:"generation,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetGenerationResponse) Reset() {
	*x = GetGenerationResponse{}
	mi := &file_anvilkit_control_v1_generation_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetGenerationResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetGenerationResponse) ProtoMessage() {}

func (x *GetGenerationResponse) ProtoReflect() protoreflect.Message {
	mi := &file_anvilkit_control_v1_generation_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetGenerationResponse.ProtoReflect.Descriptor instead.
func (*GetGenerationResponse) Descriptor() ([]byte, []int) {
	return file_anvilkit_control_v1_generation_proto_rawDescGZIP(), []int{4}
}

func (x *GetGenerationResponse) GetGeneration() *Generation {
	if x != nil {
		return x.Generation
	}
	return nil
}

type RequestExecutionPermitRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Command       *CommandIdentity       `protobuf:"bytes,1,opt,name=command,proto3" json:"command,omitempty"`
	OperationId   string                 `protobuf:"bytes,2,opt,name=operation_id,json=operationId,proto3" json:"operation_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RequestExecutionPermitRequest) Reset() {
	*x = RequestExecutionPermitRequest{}
	mi := &file_anvilkit_control_v1_generation_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RequestExecutionPermitRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RequestExecutionPermitRequest) ProtoMessage() {}

func (x *RequestExecutionPermitRequest) ProtoReflect() protoreflect.Message {
	mi := &file_anvilkit_control_v1_generation_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RequestExecutionPermitRequest.ProtoReflect.Descriptor instead.
func (*RequestExecutionPermitRequest) Descriptor() ([]byte, []int) {
	return file_anvilkit_control_v1_generation_proto_rawDescGZIP(), []int{5}
}

func (x *RequestExecutionPermitRequest) GetCommand() *CommandIdentity {
	if x != nil {
		return x.Command
	}
	return nil
}

func (x *RequestExecutionPermitRequest) GetOperationId() string {
	if x != nil {
		return x.OperationId
	}
	return ""
}

type RequestExecutionPermitResponse struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Granted        bool                   `protobuf:"varint,1,opt,name=granted,proto3" json:"granted,omitempty"`
	Permit         *ExecutionPermit       `protobuf:"bytes,2,opt,name=permit,proto3,oneof" json:"permit,omitempty"`
	ActiveDeadline *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=active_deadline,json=activeDeadline,proto3,oneof" json:"active_deadline,omitempty"`
	QueueDeadline  *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=queue_deadline,json=queueDeadline,proto3" json:"queue_deadline,omitempty"`
	// The pool's position facts for a queued request.
	QueuedAhead   string `protobuf:"bytes,5,opt,name=queued_ahead,json=queuedAhead,proto3" json:"queued_ahead,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RequestExecutionPermitResponse) Reset() {
	*x = RequestExecutionPermitResponse{}
	mi := &file_anvilkit_control_v1_generation_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RequestExecutionPermitResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RequestExecutionPermitResponse) ProtoMessage() {}

func (x *RequestExecutionPermitResponse) ProtoReflect() protoreflect.Message {
	mi := &file_anvilkit_control_v1_generation_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RequestExecutionPermitResponse.ProtoReflect.Descriptor instead.
func (*RequestExecutionPermitResponse) Descriptor() ([]byte, []int) {
	return file_anvilkit_control_v1_generation_proto_rawDescGZIP(), []int{6}
}

func (x *RequestExecutionPermitResponse) GetGranted() bool {
	if x != nil {
		return x.Granted
	}
	return false
}

func (x *RequestExecutionPermitResponse) GetPermit() *ExecutionPermit {
	if x != nil {
		return x.Permit
	}
	return nil
}

func (x *RequestExecutionPermitResponse) GetActiveDeadline() *timestamppb.Timestamp {
	if x != nil {
		return x.ActiveDeadline
	}
	return nil
}

func (x *RequestExecutionPermitResponse) GetQueueDeadline() *timestamppb.Timestamp {
	if x != nil {
		return x.QueueDeadline
	}
	return nil
}

func (x *RequestExecutionPermitResponse) GetQueuedAhead() string {
	if x != nil {
		return x.QueuedAhead
	}
	return ""
}

type RecordLeaseRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Command       *CommandIdentity       `protobuf:"bytes,1,opt,name=command,proto3" json:"command,omitempty"`
	OperationId   string                 `protobuf:"bytes,2,opt,name=operation_id,json=operationId,proto3" json:"operation_id,omitempty"`
	Occurrence    string                 `protobuf:"bytes,3,opt,name=occurrence,proto3" json:"occurrence,omitempty"`
	State         LeaseState             `protobuf:"varint,4,opt,name=state,proto3,enum=anvilkit.control.v1.LeaseState" json:"state,omitempty"`
	LeaseId       string                 `protobuf:"bytes,5,opt,name=lease_id,json=leaseId,proto3" json:"lease_id,omitempty"`
	Fence         string                 `protobuf:"bytes,6,opt,name=fence,proto3" json:"fence,omitempty"`
	ExpiresAt     *timestamppb.Timestamp `protobuf:"bytes,7,opt,name=expires_at,json=expiresAt,proto3,oneof" json:"expires_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RecordLeaseRequest) Reset() {
	*x = RecordLeaseRequest{}
	mi := &file_anvilkit_control_v1_generation_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RecordLeaseRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RecordLeaseRequest) ProtoMessage() {}

func (x *RecordLeaseRequest) ProtoReflect() protoreflect.Message {
	mi := &file_anvilkit_control_v1_generation_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RecordLeaseRequest.ProtoReflect.Descriptor instead.
func (*RecordLeaseRequest) Descriptor() ([]byte, []int) {
	return file_anvilkit_control_v1_generation_proto_rawDescGZIP(), []int{7}
}

func (x *RecordLeaseRequest) GetCommand() *CommandIdentity {
	if x != nil {
		return x.Command
	}
	return nil
}

func (x *RecordLeaseRequest) GetOperationId() string {
	if x != nil {
		return x.OperationId
	}
	return ""
}

func (x *RecordLeaseRequest) GetOccurrence() string {
	if x != nil {
		return x.Occurrence
	}
	return ""
}

func (x *RecordLeaseRequest) GetState() LeaseState {
	if x != nil {
		return x.State
	}
	return LeaseState_LEASE_STATE_UNSPECIFIED
}

func (x *RecordLeaseRequest) GetLeaseId() string {
	if x != nil {
		return x.LeaseId
	}
	return ""
}

func (x *RecordLeaseRequest) GetFence() string {
	if x != nil {
		return x.Fence
	}
	return ""
}

func (x *RecordLeaseRequest) GetExpiresAt() *timestamppb.Timestamp {
	if x != nil {
		return x.ExpiresAt
	}
	return nil
}

type RecordLeaseResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Lease         *LeaseRecord           `protobuf:"bytes,1,opt,name=lease,proto3" json:"lease,omitempty"`
	Operation     *OperationView         `protobuf:"bytes,2,opt,name=operation,proto3" json:"operation,omitempty"`
	Existing      bool                   `protobuf:"varint,3,opt,name=existing,proto3" json:"existing,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RecordLeaseResponse) Reset() {
	*x = RecordLeaseResponse{}
	mi := &file_anvilkit_control_v1_generation_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RecordLeaseResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RecordLeaseResponse) ProtoMessage() {}

func (x *RecordLeaseResponse) ProtoReflect() protoreflect.Message {
	mi := &file_anvilkit_control_v1_generation_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RecordLeaseResponse.ProtoReflect.Descriptor instead.
func (*RecordLeaseResponse) Descriptor() ([]byte, []int) {
	return file_anvilkit_control_v1_generation_proto_rawDescGZIP(), []int{8}
}

func (x *RecordLeaseResponse) GetLease() *LeaseRecord {
	if x != nil {
		return x.Lease
	}
	return nil
}

func (x *RecordLeaseResponse) GetOperation() *OperationView {
	if x != nil {
		return x.Operation
	}
	return nil
}

func (x *RecordLeaseResponse) GetExisting() bool {
	if x != nil {
		return x.Existing
	}
	return false
}

type RecordFundingRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Command       *CommandIdentity       `protobuf:"bytes,1,opt,name=command,proto3" json:"command,omitempty"`
	OperationId   string                 `protobuf:"bytes,2,opt,name=operation_id,json=operationId,proto3" json:"operation_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RecordFundingRequest) Reset() {
	*x = RecordFundingRequest{}
	mi := &file_anvilkit_control_v1_generation_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RecordFundingRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RecordFundingRequest) ProtoMessage() {}

func (x *RecordFundingRequest) ProtoReflect() protoreflect.Message {
	mi := &file_anvilkit_control_v1_generation_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RecordFundingRequest.ProtoReflect.Descriptor instead.
func (*RecordFundingRequest) Descriptor() ([]byte, []int) {
	return file_anvilkit_control_v1_generation_proto_rawDescGZIP(), []int{9}
}

func (x *RecordFundingRequest) GetCommand() *CommandIdentity {
	if x != nil {
		return x.Command
	}
	return nil
}

func (x *RecordFundingRequest) GetOperationId() string {
	if x != nil {
		return x.OperationId
	}
	return ""
}

type RecordFundingResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Amount        *Money                 `protobuf:"bytes,1,opt,name=amount,proto3" json:"amount,omitempty"`
	Existing      bool                   `protobuf:"varint,2,opt,name=existing,proto3" json:"existing,omitempty"`
	Operation     *OperationView         `protobuf:"bytes,3,opt,name=operation,proto3" json:"operation,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RecordFundingResponse) Reset() {
	*x = RecordFundingResponse{}
	mi := &file_anvilkit_control_v1_generation_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RecordFundingResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RecordFundingResponse) ProtoMessage() {}

func (x *RecordFundingResponse) ProtoReflect() protoreflect.Message {
	mi := &file_anvilkit_control_v1_generation_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RecordFundingResponse.ProtoReflect.Descriptor instead.
func (*RecordFundingResponse) Descriptor() ([]byte, []int) {
	return file_anvilkit_control_v1_generation_proto_rawDescGZIP(), []int{10}
}

func (x *RecordFundingResponse) GetAmount() *Money {
	if x != nil {
		return x.Amount
	}
	return nil
}

func (x *RecordFundingResponse) GetExisting() bool {
	if x != nil {
		return x.Existing
	}
	return false
}

func (x *RecordFundingResponse) GetOperation() *OperationView {
	if x != nil {
		return x.Operation
	}
	return nil
}

type RecordCommandRelayRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TenantId      string                 `protobuf:"bytes,1,opt,name=tenant_id,json=tenantId,proto3" json:"tenant_id,omitempty"`
	CommandId     string                 `protobuf:"bytes,2,opt,name=command_id,json=commandId,proto3" json:"command_id,omitempty"`
	Outcome       CommandOutcome         `protobuf:"varint,3,opt,name=outcome,proto3,enum=anvilkit.control.v1.CommandOutcome" json:"outcome,omitempty"`
	ReasonCode    string                 `protobuf:"bytes,4,opt,name=reason_code,json=reasonCode,proto3" json:"reason_code,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RecordCommandRelayRequest) Reset() {
	*x = RecordCommandRelayRequest{}
	mi := &file_anvilkit_control_v1_generation_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RecordCommandRelayRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RecordCommandRelayRequest) ProtoMessage() {}

func (x *RecordCommandRelayRequest) ProtoReflect() protoreflect.Message {
	mi := &file_anvilkit_control_v1_generation_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RecordCommandRelayRequest.ProtoReflect.Descriptor instead.
func (*RecordCommandRelayRequest) Descriptor() ([]byte, []int) {
	return file_anvilkit_control_v1_generation_proto_rawDescGZIP(), []int{11}
}

func (x *RecordCommandRelayRequest) GetTenantId() string {
	if x != nil {
		return x.TenantId
	}
	return ""
}

func (x *RecordCommandRelayRequest) GetCommandId() string {
	if x != nil {
		return x.CommandId
	}
	return ""
}

func (x *RecordCommandRelayRequest) GetOutcome() CommandOutcome {
	if x != nil {
		return x.Outcome
	}
	return CommandOutcome_COMMAND_OUTCOME_UNSPECIFIED
}

func (x *RecordCommandRelayRequest) GetReasonCode() string {
	if x != nil {
		return x.ReasonCode
	}
	return ""
}

type RecordCommandRelayResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Receipt       *CommandReceipt        `protobuf:"bytes,1,opt,name=receipt,proto3" json:"receipt,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RecordCommandRelayResponse) Reset() {
	*x = RecordCommandRelayResponse{}
	mi := &file_anvilkit_control_v1_generation_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RecordCommandRelayResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RecordCommandRelayResponse) ProtoMessage() {}

func (x *RecordCommandRelayResponse) ProtoReflect() protoreflect.Message {
	mi := &file_anvilkit_control_v1_generation_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RecordCommandRelayResponse.ProtoReflect.Descriptor instead.
func (*RecordCommandRelayResponse) Descriptor() ([]byte, []int) {
	return file_anvilkit_control_v1_generation_proto_rawDescGZIP(), []int{12}
}

func (x *RecordCommandRelayResponse) GetReceipt() *CommandReceipt {
	if x != nil {
		return x.Receipt
	}
	return nil
}

var File_anvilkit_control_v1_generation_proto protoreflect.FileDescriptor

const file_anvilkit_control_v1_generation_proto_rawDesc = "" +
	"\n" +
	"$anvilkit/control/v1/generation.proto\x12\x13anvilkit.control.v1\x1a!anvilkit/control/v1/control.proto\x1a%anvilkit/control/v1/preparation.proto\x1a\x1bbuf/validate/validate.proto\x1a\x1fgoogle/protobuf/timestamp.proto\"\xd0\x02\n" +
	"\x0fExecutionPermit\x12\x1b\n" +
	"\tpermit_id\x18\x01 \x01(\tR\bpermitId\x12\x17\n" +
	"\apool_id\x18\x02 \x01(\tR\x06poolId\x12!\n" +
	"\foperation_id\x18\x03 \x01(\tR\voperationId\x12\x1f\n" +
	"\vfence_epoch\x18\x04 \x01(\tR\n" +
	"fenceEpoch\x126\n" +
	"\x05state\x18\x05 \x01(\x0e2 .anvilkit.control.v1.PermitStateR\x05state\x129\n" +
	"\n" +
	"granted_at\x18\x06 \x01(\v2\x1a.google.protobuf.TimestampR\tgrantedAt\x12@\n" +
	"\vreleased_at\x18\a \x01(\v2\x1a.google.protobuf.TimestampH\x00R\n" +
	"releasedAt\x88\x01\x01B\x0e\n" +
	"\f_released_at\"\xe4\x01\n" +
	"\vLeaseRecord\x125\n" +
	"\x05state\x18\x01 \x01(\x0e2\x1f.anvilkit.control.v1.LeaseStateR\x05state\x12\x19\n" +
	"\blease_id\x18\x02 \x01(\tR\aleaseId\x12\x14\n" +
	"\x05fence\x18\x03 \x01(\tR\x05fence\x12>\n" +
	"\n" +
	"expires_at\x18\x04 \x01(\v2\x1a.google.protobuf.TimestampH\x00R\texpiresAt\x88\x01\x01\x12\x1e\n" +
	"\n" +
	"occurrence\x18\x05 \x01(\tR\n" +
	"occurrenceB\r\n" +
	"\v_expires_at\"\xcb\x06\n" +
	"\n" +
	"Generation\x12!\n" +
	"\foperation_id\x18\x01 \x01(\tR\voperationId\x12\x1b\n" +
	"\ttenant_id\x18\x02 \x01(\tR\btenantId\x120\n" +
	"\x05brief\x18\x03 \x01(\v2\x1a.anvilkit.control.v1.BriefR\x05brief\x12A\n" +
	"\x06permit\x18\x04 \x01(\v2$.anvilkit.control.v1.ExecutionPermitH\x00R\x06permit\x88\x01\x01\x12H\n" +
	"\x0factive_deadline\x18\x05 \x01(\v2\x1a.google.protobuf.TimestampH\x01R\x0eactiveDeadline\x88\x01\x01\x12A\n" +
	"\x0equeue_deadline\x18\x06 \x01(\v2\x1a.google.protobuf.TimestampR\rqueueDeadline\x126\n" +
	"\x05lease\x18\a \x01(\v2 .anvilkit.control.v1.LeaseRecordR\x05lease\x129\n" +
	"\afunding\x18\b \x01(\v2\x1a.anvilkit.control.v1.MoneyH\x02R\afunding\x88\x01\x01\x123\n" +
	"\x15definition_activation\x18\t \x01(\tR\x14definitionActivation\x12\x1f\n" +
	"\vmax_repairs\x18\n" +
	" \x01(\tR\n" +
	"maxRepairs\x12,\n" +
	"\x12codegen_profile_id\x18\v \x01(\tR\x10codegenProfileId\x120\n" +
	"\x14validator_profile_id\x18\f \x01(\tR\x12validatorProfileId\x123\n" +
	"\x13candidate_effect_id\x18\r \x01(\tH\x03R\x11candidateEffectId\x88\x01\x01\x12?\n" +
	"\asubject\x18\x0e \x01(\v2%.anvilkit.control.v1.OperationSubjectR\asubject\x12\x19\n" +
	"\bactor_id\x18\x0f \x01(\tR\aactorIdB\t\n" +
	"\a_permitB\x12\n" +
	"\x10_active_deadlineB\n" +
	"\n" +
	"\b_fundingB\x16\n" +
	"\x14_candidate_effect_id\"n\n" +
	"\x14GetGenerationRequest\x12'\n" +
	"\ttenant_id\x18\x01 \x01(\tB\n" +
	"\xbaH\ar\x05\x10\x01\x18\x80\x01R\btenantId\x12-\n" +
	"\foperation_id\x18\x02 \x01(\tB\n" +
	"\xbaH\ar\x05\x10\x01\x18\x80\x01R\voperationId\"X\n" +
	"\x15GetGenerationResponse\x12?\n" +
	"\n" +
	"generation\x18\x01 \x01(\v2\x1f.anvilkit.control.v1.GenerationR\n" +
	"generation\"\x96\x01\n" +
	"\x1dRequestExecutionPermitRequest\x12F\n" +
	"\acommand\x18\x01 \x01(\v2$.anvilkit.control.v1.CommandIdentityB\x06\xbaH\x03\xc8\x01\x01R\acommand\x12-\n" +
	"\foperation_id\x18\x02 \x01(\tB\n" +
	"\xbaH\ar\x05\x10\x01\x18\x80\x01R\voperationId\"\xcc\x02\n" +
	"\x1eRequestExecutionPermitResponse\x12\x18\n" +
	"\agranted\x18\x01 \x01(\bR\agranted\x12A\n" +
	"\x06permit\x18\x02 \x01(\v2$.anvilkit.control.v1.ExecutionPermitH\x00R\x06permit\x88\x01\x01\x12H\n" +
	"\x0factive_deadline\x18\x03 \x01(\v2\x1a.google.protobuf.TimestampH\x01R\x0eactiveDeadline\x88\x01\x01\x12A\n" +
	"\x0equeue_deadline\x18\x04 \x01(\v2\x1a.google.protobuf.TimestampR\rqueueDeadline\x12!\n" +
	"\fqueued_ahead\x18\x05 \x01(\tR\vqueuedAheadB\t\n" +
	"\a_permitB\x12\n" +
	"\x10_active_deadline\"\xb5\x03\n" +
	"\x12RecordLeaseRequest\x12F\n" +
	"\acommand\x18\x01 \x01(\v2$.anvilkit.control.v1.CommandIdentityB\x06\xbaH\x03\xc8\x01\x01R\acommand\x12-\n" +
	"\foperation_id\x18\x02 \x01(\tB\n" +
	"\xbaH\ar\x05\x10\x01\x18\x80\x01R\voperationId\x129\n" +
	"\n" +
	"occurrence\x18\x03 \x01(\tB\x19\xbaH\x16r\x142\x12^[1-9][0-9]{0,19}$R\n" +
	"occurrence\x12C\n" +
	"\x05state\x18\x04 \x01(\x0e2\x1f.anvilkit.control.v1.LeaseStateB\f\xbaH\t\x82\x01\x06\x10\x01 \x00 \x01R\x05state\x12#\n" +
	"\blease_id\x18\x05 \x01(\tB\b\xbaH\x05r\x03\x18\x80\x01R\aleaseId\x124\n" +
	"\x05fence\x18\x06 \x01(\tB\x1e\xbaH\x1br\x192\x17^(0|[1-9][0-9]{0,19})?$R\x05fence\x12>\n" +
	"\n" +
	"expires_at\x18\a \x01(\v2\x1a.google.protobuf.TimestampH\x00R\texpiresAt\x88\x01\x01B\r\n" +
	"\v_expires_at\"\xab\x01\n" +
	"\x13RecordLeaseResponse\x126\n" +
	"\x05lease\x18\x01 \x01(\v2 .anvilkit.control.v1.LeaseRecordR\x05lease\x12@\n" +
	"\toperation\x18\x02 \x01(\v2\".anvilkit.control.v1.OperationViewR\toperation\x12\x1a\n" +
	"\bexisting\x18\x03 \x01(\bR\bexisting\"\x8d\x01\n" +
	"\x14RecordFundingRequest\x12F\n" +
	"\acommand\x18\x01 \x01(\v2$.anvilkit.control.v1.CommandIdentityB\x06\xbaH\x03\xc8\x01\x01R\acommand\x12-\n" +
	"\foperation_id\x18\x02 \x01(\tB\n" +
	"\xbaH\ar\x05\x10\x01\x18\x80\x01R\voperationId\"\xa9\x01\n" +
	"\x15RecordFundingResponse\x122\n" +
	"\x06amount\x18\x01 \x01(\v2\x1a.anvilkit.control.v1.MoneyR\x06amount\x12\x1a\n" +
	"\bexisting\x18\x02 \x01(\bR\bexisting\x12@\n" +
	"\toperation\x18\x03 \x01(\v2\".anvilkit.control.v1.OperationViewR\toperation\"\xe4\x01\n" +
	"\x19RecordCommandRelayRequest\x12'\n" +
	"\ttenant_id\x18\x01 \x01(\tB\n" +
	"\xbaH\ar\x05\x10\x01\x18\x80\x01R\btenantId\x12)\n" +
	"\n" +
	"command_id\x18\x02 \x01(\tB\n" +
	"\xbaH\ar\x05\x10\x01\x18\x80\x01R\tcommandId\x12I\n" +
	"\aoutcome\x18\x03 \x01(\x0e2#.anvilkit.control.v1.CommandOutcomeB\n" +
	"\xbaH\a\x82\x01\x04\x10\x01 \x00R\aoutcome\x12(\n" +
	"\vreason_code\x18\x04 \x01(\tB\a\xbaH\x04r\x02\x18@R\n" +
	"reasonCode\"[\n" +
	"\x1aRecordCommandRelayResponse\x12=\n" +
	"\areceipt\x18\x01 \x01(\v2#.anvilkit.control.v1.CommandReceiptR\areceipt*\x85\x01\n" +
	"\vPermitState\x12\x1c\n" +
	"\x18PERMIT_STATE_UNSPECIFIED\x10\x00\x12\x17\n" +
	"\x13PERMIT_STATE_ACTIVE\x10\x01\x12\x19\n" +
	"\x15PERMIT_STATE_RELEASED\x10\x02\x12$\n" +
	" PERMIT_STATE_EXPIRED_UNCONFIRMED\x10\x03*\x85\x01\n" +
	"\n" +
	"LeaseState\x12\x1b\n" +
	"\x17LEASE_STATE_UNSPECIFIED\x10\x00\x12\x14\n" +
	"\x10LEASE_STATE_NONE\x10\x01\x12\x14\n" +
	"\x10LEASE_STATE_HELD\x10\x02\x12\x14\n" +
	"\x10LEASE_STATE_LOST\x10\x03\x12\x18\n" +
	"\x14LEASE_STATE_RELEASED\x10\x042\xc0\x04\n" +
	"\x11GenerationService\x12f\n" +
	"\rGetGeneration\x12).anvilkit.control.v1.GetGenerationRequest\x1a*.anvilkit.control.v1.GetGenerationResponse\x12\x81\x01\n" +
	"\x16RequestExecutionPermit\x122.anvilkit.control.v1.RequestExecutionPermitRequest\x1a3.anvilkit.control.v1.RequestExecutionPermitResponse\x12`\n" +
	"\vRecordLease\x12'.anvilkit.control.v1.RecordLeaseRequest\x1a(.anvilkit.control.v1.RecordLeaseResponse\x12f\n" +
	"\rRecordFunding\x12).anvilkit.control.v1.RecordFundingRequest\x1a*.anvilkit.control.v1.RecordFundingResponse\x12u\n" +
	"\x12RecordCommandRelay\x12..anvilkit.control.v1.RecordCommandRelayRequest\x1a/.anvilkit.control.v1.RecordCommandRelayResponseB\xe7\x01\n" +
	"\x17com.anvilkit.control.v1B\x0fGenerationProtoP\x01ZMgithub.com/ancyloce/anvilkit-agent-contracts/go/anvilkit/control/v1;controlv1\xa2\x02\x03ACX\xaa\x02\x13Anvilkit.Control.V1\xca\x02\x13Anvilkit\\Control\\V1\xe2\x02\x1fAnvilkit\\Control\\V1\\GPBMetadata\xea\x02\x15Anvilkit::Control::V1b\x06proto3"

var (
	file_anvilkit_control_v1_generation_proto_rawDescOnce sync.Once
	file_anvilkit_control_v1_generation_proto_rawDescData []byte
)

func file_anvilkit_control_v1_generation_proto_rawDescGZIP() []byte {
	file_anvilkit_control_v1_generation_proto_rawDescOnce.Do(func() {
		file_anvilkit_control_v1_generation_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_anvilkit_control_v1_generation_proto_rawDesc), len(file_anvilkit_control_v1_generation_proto_rawDesc)))
	})
	return file_anvilkit_control_v1_generation_proto_rawDescData
}

var file_anvilkit_control_v1_generation_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_anvilkit_control_v1_generation_proto_msgTypes = make([]protoimpl.MessageInfo, 13)
var file_anvilkit_control_v1_generation_proto_goTypes = []any{
	(PermitState)(0),                       // 0: anvilkit.control.v1.PermitState
	(LeaseState)(0),                        // 1: anvilkit.control.v1.LeaseState
	(*ExecutionPermit)(nil),                // 2: anvilkit.control.v1.ExecutionPermit
	(*LeaseRecord)(nil),                    // 3: anvilkit.control.v1.LeaseRecord
	(*Generation)(nil),                     // 4: anvilkit.control.v1.Generation
	(*GetGenerationRequest)(nil),           // 5: anvilkit.control.v1.GetGenerationRequest
	(*GetGenerationResponse)(nil),          // 6: anvilkit.control.v1.GetGenerationResponse
	(*RequestExecutionPermitRequest)(nil),  // 7: anvilkit.control.v1.RequestExecutionPermitRequest
	(*RequestExecutionPermitResponse)(nil), // 8: anvilkit.control.v1.RequestExecutionPermitResponse
	(*RecordLeaseRequest)(nil),             // 9: anvilkit.control.v1.RecordLeaseRequest
	(*RecordLeaseResponse)(nil),            // 10: anvilkit.control.v1.RecordLeaseResponse
	(*RecordFundingRequest)(nil),           // 11: anvilkit.control.v1.RecordFundingRequest
	(*RecordFundingResponse)(nil),          // 12: anvilkit.control.v1.RecordFundingResponse
	(*RecordCommandRelayRequest)(nil),      // 13: anvilkit.control.v1.RecordCommandRelayRequest
	(*RecordCommandRelayResponse)(nil),     // 14: anvilkit.control.v1.RecordCommandRelayResponse
	(*timestamppb.Timestamp)(nil),          // 15: google.protobuf.Timestamp
	(*Brief)(nil),                          // 16: anvilkit.control.v1.Brief
	(*Money)(nil),                          // 17: anvilkit.control.v1.Money
	(*OperationSubject)(nil),               // 18: anvilkit.control.v1.OperationSubject
	(*CommandIdentity)(nil),                // 19: anvilkit.control.v1.CommandIdentity
	(*OperationView)(nil),                  // 20: anvilkit.control.v1.OperationView
	(CommandOutcome)(0),                    // 21: anvilkit.control.v1.CommandOutcome
	(*CommandReceipt)(nil),                 // 22: anvilkit.control.v1.CommandReceipt
}
var file_anvilkit_control_v1_generation_proto_depIdxs = []int32{
	0,  // 0: anvilkit.control.v1.ExecutionPermit.state:type_name -> anvilkit.control.v1.PermitState
	15, // 1: anvilkit.control.v1.ExecutionPermit.granted_at:type_name -> google.protobuf.Timestamp
	15, // 2: anvilkit.control.v1.ExecutionPermit.released_at:type_name -> google.protobuf.Timestamp
	1,  // 3: anvilkit.control.v1.LeaseRecord.state:type_name -> anvilkit.control.v1.LeaseState
	15, // 4: anvilkit.control.v1.LeaseRecord.expires_at:type_name -> google.protobuf.Timestamp
	16, // 5: anvilkit.control.v1.Generation.brief:type_name -> anvilkit.control.v1.Brief
	2,  // 6: anvilkit.control.v1.Generation.permit:type_name -> anvilkit.control.v1.ExecutionPermit
	15, // 7: anvilkit.control.v1.Generation.active_deadline:type_name -> google.protobuf.Timestamp
	15, // 8: anvilkit.control.v1.Generation.queue_deadline:type_name -> google.protobuf.Timestamp
	3,  // 9: anvilkit.control.v1.Generation.lease:type_name -> anvilkit.control.v1.LeaseRecord
	17, // 10: anvilkit.control.v1.Generation.funding:type_name -> anvilkit.control.v1.Money
	18, // 11: anvilkit.control.v1.Generation.subject:type_name -> anvilkit.control.v1.OperationSubject
	4,  // 12: anvilkit.control.v1.GetGenerationResponse.generation:type_name -> anvilkit.control.v1.Generation
	19, // 13: anvilkit.control.v1.RequestExecutionPermitRequest.command:type_name -> anvilkit.control.v1.CommandIdentity
	2,  // 14: anvilkit.control.v1.RequestExecutionPermitResponse.permit:type_name -> anvilkit.control.v1.ExecutionPermit
	15, // 15: anvilkit.control.v1.RequestExecutionPermitResponse.active_deadline:type_name -> google.protobuf.Timestamp
	15, // 16: anvilkit.control.v1.RequestExecutionPermitResponse.queue_deadline:type_name -> google.protobuf.Timestamp
	19, // 17: anvilkit.control.v1.RecordLeaseRequest.command:type_name -> anvilkit.control.v1.CommandIdentity
	1,  // 18: anvilkit.control.v1.RecordLeaseRequest.state:type_name -> anvilkit.control.v1.LeaseState
	15, // 19: anvilkit.control.v1.RecordLeaseRequest.expires_at:type_name -> google.protobuf.Timestamp
	3,  // 20: anvilkit.control.v1.RecordLeaseResponse.lease:type_name -> anvilkit.control.v1.LeaseRecord
	20, // 21: anvilkit.control.v1.RecordLeaseResponse.operation:type_name -> anvilkit.control.v1.OperationView
	19, // 22: anvilkit.control.v1.RecordFundingRequest.command:type_name -> anvilkit.control.v1.CommandIdentity
	17, // 23: anvilkit.control.v1.RecordFundingResponse.amount:type_name -> anvilkit.control.v1.Money
	20, // 24: anvilkit.control.v1.RecordFundingResponse.operation:type_name -> anvilkit.control.v1.OperationView
	21, // 25: anvilkit.control.v1.RecordCommandRelayRequest.outcome:type_name -> anvilkit.control.v1.CommandOutcome
	22, // 26: anvilkit.control.v1.RecordCommandRelayResponse.receipt:type_name -> anvilkit.control.v1.CommandReceipt
	5,  // 27: anvilkit.control.v1.GenerationService.GetGeneration:input_type -> anvilkit.control.v1.GetGenerationRequest
	7,  // 28: anvilkit.control.v1.GenerationService.RequestExecutionPermit:input_type -> anvilkit.control.v1.RequestExecutionPermitRequest
	9,  // 29: anvilkit.control.v1.GenerationService.RecordLease:input_type -> anvilkit.control.v1.RecordLeaseRequest
	11, // 30: anvilkit.control.v1.GenerationService.RecordFunding:input_type -> anvilkit.control.v1.RecordFundingRequest
	13, // 31: anvilkit.control.v1.GenerationService.RecordCommandRelay:input_type -> anvilkit.control.v1.RecordCommandRelayRequest
	6,  // 32: anvilkit.control.v1.GenerationService.GetGeneration:output_type -> anvilkit.control.v1.GetGenerationResponse
	8,  // 33: anvilkit.control.v1.GenerationService.RequestExecutionPermit:output_type -> anvilkit.control.v1.RequestExecutionPermitResponse
	10, // 34: anvilkit.control.v1.GenerationService.RecordLease:output_type -> anvilkit.control.v1.RecordLeaseResponse
	12, // 35: anvilkit.control.v1.GenerationService.RecordFunding:output_type -> anvilkit.control.v1.RecordFundingResponse
	14, // 36: anvilkit.control.v1.GenerationService.RecordCommandRelay:output_type -> anvilkit.control.v1.RecordCommandRelayResponse
	32, // [32:37] is the sub-list for method output_type
	27, // [27:32] is the sub-list for method input_type
	27, // [27:27] is the sub-list for extension type_name
	27, // [27:27] is the sub-list for extension extendee
	0,  // [0:27] is the sub-list for field type_name
}

func init() { file_anvilkit_control_v1_generation_proto_init() }
func file_anvilkit_control_v1_generation_proto_init() {
	if File_anvilkit_control_v1_generation_proto != nil {
		return
	}
	file_anvilkit_control_v1_control_proto_init()
	file_anvilkit_control_v1_preparation_proto_init()
	file_anvilkit_control_v1_generation_proto_msgTypes[0].OneofWrappers = []any{}
	file_anvilkit_control_v1_generation_proto_msgTypes[1].OneofWrappers = []any{}
	file_anvilkit_control_v1_generation_proto_msgTypes[2].OneofWrappers = []any{}
	file_anvilkit_control_v1_generation_proto_msgTypes[6].OneofWrappers = []any{}
	file_anvilkit_control_v1_generation_proto_msgTypes[7].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_anvilkit_control_v1_generation_proto_rawDesc), len(file_anvilkit_control_v1_generation_proto_rawDesc)),
			NumEnums:      2,
			NumMessages:   13,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_anvilkit_control_v1_generation_proto_goTypes,
		DependencyIndexes: file_anvilkit_control_v1_generation_proto_depIdxs,
		EnumInfos:         file_anvilkit_control_v1_generation_proto_enumTypes,
		MessageInfos:      file_anvilkit_control_v1_generation_proto_msgTypes,
	}.Build()
	File_anvilkit_control_v1_generation_proto = out.File
	file_anvilkit_control_v1_generation_proto_goTypes = nil
	file_anvilkit_control_v1_generation_proto_depIdxs = nil
}
