// Preparation (DD-01 §3, delivery.md P13): the durable human-input records
// of a Preparation operation. Control persists question sets with their
// immutable absolute expiry, accepts one answer per question set revision
// under a durable command identity together with its Update relay intent,
// and freezes the brief that binds requirements, source revisions and
// brand/asset content digests to the preparation operation. The Workflow
// reads the accepted answer through GetAnswer (also for a lost Update
// receipt: the original answer and its Update are queried, never re-sent
// under a new identity); no Signal, polling loop or wake-up service exists.

// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             (unknown)
// source: anvilkit/control/v1/preparation.proto

package controlv1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	PreparationService_GetPreparation_FullMethodName    = "/anvilkit.control.v1.PreparationService/GetPreparation"
	PreparationService_RecordQuestionSet_FullMethodName = "/anvilkit.control.v1.PreparationService/RecordQuestionSet"
	PreparationService_SubmitAnswer_FullMethodName      = "/anvilkit.control.v1.PreparationService/SubmitAnswer"
	PreparationService_GetAnswer_FullMethodName         = "/anvilkit.control.v1.PreparationService/GetAnswer"
	PreparationService_RecordAnswerRelay_FullMethodName = "/anvilkit.control.v1.PreparationService/RecordAnswerRelay"
	PreparationService_RecordBrief_FullMethodName       = "/anvilkit.control.v1.PreparationService/RecordBrief"
	PreparationService_GetBrief_FullMethodName          = "/anvilkit.control.v1.PreparationService/GetBrief"
)

// PreparationServiceClient is the client API for PreparationService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type PreparationServiceClient interface {
	// Reads the intake, question sets and brief of a Preparation.
	GetPreparation(ctx context.Context, in *GetPreparationRequest, opts ...grpc.CallOption) (*GetPreparationResponse, error)
	// Records a grouped question round with its immutable expiry (asked_at plus
	// the profile's wait). The same command returns the original set; a round
	// or question count beyond the profile's bounds, a set for a fenced or
	// terminal operation, or a round asked while a set is open is refused.
	// The operation becomes waiting/awaiting_input.
	RecordQuestionSet(ctx context.Context, in *RecordQuestionSetRequest, opts ...grpc.CallOption) (*RecordQuestionSetResponse, error)
	// Accepts an answer (API-06) bound to the current question set revision:
	// the same command returns the original receipt; another answer for the
	// same revision, a stale revision or an expired set is refused. The answer
	// and its Update relay intent commit together.
	SubmitAnswer(ctx context.Context, in *SubmitAnswerRequest, opts ...grpc.CallOption) (*SubmitAnswerResponse, error)
	// Reads the accepted answer of a question set (or by answer id).
	GetAnswer(ctx context.Context, in *GetAnswerRequest, opts ...grpc.CallOption) (*GetAnswerResponse, error)
	// Records the Update outcome of an answer's relay (the relay's own record
	// of the receipt; a lost receipt is repaired by querying the Update).
	RecordAnswerRelay(ctx context.Context, in *RecordAnswerRelayRequest, opts ...grpc.CallOption) (*RecordAnswerRelayResponse, error)
	// Freezes the brief: the brief artifact, the requirements digest, the
	// source revisions and the content digests bind to the preparation
	// operation; a previous brief of the operation is superseded. The same
	// command returns the original brief.
	RecordBrief(ctx context.Context, in *RecordBriefRequest, opts ...grpc.CallOption) (*RecordBriefResponse, error)
	GetBrief(ctx context.Context, in *GetBriefRequest, opts ...grpc.CallOption) (*GetBriefResponse, error)
}

type preparationServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewPreparationServiceClient(cc grpc.ClientConnInterface) PreparationServiceClient {
	return &preparationServiceClient{cc}
}

func (c *preparationServiceClient) GetPreparation(ctx context.Context, in *GetPreparationRequest, opts ...grpc.CallOption) (*GetPreparationResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetPreparationResponse)
	err := c.cc.Invoke(ctx, PreparationService_GetPreparation_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *preparationServiceClient) RecordQuestionSet(ctx context.Context, in *RecordQuestionSetRequest, opts ...grpc.CallOption) (*RecordQuestionSetResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RecordQuestionSetResponse)
	err := c.cc.Invoke(ctx, PreparationService_RecordQuestionSet_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *preparationServiceClient) SubmitAnswer(ctx context.Context, in *SubmitAnswerRequest, opts ...grpc.CallOption) (*SubmitAnswerResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SubmitAnswerResponse)
	err := c.cc.Invoke(ctx, PreparationService_SubmitAnswer_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *preparationServiceClient) GetAnswer(ctx context.Context, in *GetAnswerRequest, opts ...grpc.CallOption) (*GetAnswerResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetAnswerResponse)
	err := c.cc.Invoke(ctx, PreparationService_GetAnswer_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *preparationServiceClient) RecordAnswerRelay(ctx context.Context, in *RecordAnswerRelayRequest, opts ...grpc.CallOption) (*RecordAnswerRelayResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RecordAnswerRelayResponse)
	err := c.cc.Invoke(ctx, PreparationService_RecordAnswerRelay_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *preparationServiceClient) RecordBrief(ctx context.Context, in *RecordBriefRequest, opts ...grpc.CallOption) (*RecordBriefResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RecordBriefResponse)
	err := c.cc.Invoke(ctx, PreparationService_RecordBrief_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *preparationServiceClient) GetBrief(ctx context.Context, in *GetBriefRequest, opts ...grpc.CallOption) (*GetBriefResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetBriefResponse)
	err := c.cc.Invoke(ctx, PreparationService_GetBrief_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// PreparationServiceServer is the server API for PreparationService service.
// All implementations must embed UnimplementedPreparationServiceServer
// for forward compatibility.
type PreparationServiceServer interface {
	// Reads the intake, question sets and brief of a Preparation.
	GetPreparation(context.Context, *GetPreparationRequest) (*GetPreparationResponse, error)
	// Records a grouped question round with its immutable expiry (asked_at plus
	// the profile's wait). The same command returns the original set; a round
	// or question count beyond the profile's bounds, a set for a fenced or
	// terminal operation, or a round asked while a set is open is refused.
	// The operation becomes waiting/awaiting_input.
	RecordQuestionSet(context.Context, *RecordQuestionSetRequest) (*RecordQuestionSetResponse, error)
	// Accepts an answer (API-06) bound to the current question set revision:
	// the same command returns the original receipt; another answer for the
	// same revision, a stale revision or an expired set is refused. The answer
	// and its Update relay intent commit together.
	SubmitAnswer(context.Context, *SubmitAnswerRequest) (*SubmitAnswerResponse, error)
	// Reads the accepted answer of a question set (or by answer id).
	GetAnswer(context.Context, *GetAnswerRequest) (*GetAnswerResponse, error)
	// Records the Update outcome of an answer's relay (the relay's own record
	// of the receipt; a lost receipt is repaired by querying the Update).
	RecordAnswerRelay(context.Context, *RecordAnswerRelayRequest) (*RecordAnswerRelayResponse, error)
	// Freezes the brief: the brief artifact, the requirements digest, the
	// source revisions and the content digests bind to the preparation
	// operation; a previous brief of the operation is superseded. The same
	// command returns the original brief.
	RecordBrief(context.Context, *RecordBriefRequest) (*RecordBriefResponse, error)
	GetBrief(context.Context, *GetBriefRequest) (*GetBriefResponse, error)
	mustEmbedUnimplementedPreparationServiceServer()
}

// UnimplementedPreparationServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedPreparationServiceServer struct{}

func (UnimplementedPreparationServiceServer) GetPreparation(context.Context, *GetPreparationRequest) (*GetPreparationResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetPreparation not implemented")
}
func (UnimplementedPreparationServiceServer) RecordQuestionSet(context.Context, *RecordQuestionSetRequest) (*RecordQuestionSetResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method RecordQuestionSet not implemented")
}
func (UnimplementedPreparationServiceServer) SubmitAnswer(context.Context, *SubmitAnswerRequest) (*SubmitAnswerResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method SubmitAnswer not implemented")
}
func (UnimplementedPreparationServiceServer) GetAnswer(context.Context, *GetAnswerRequest) (*GetAnswerResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetAnswer not implemented")
}
func (UnimplementedPreparationServiceServer) RecordAnswerRelay(context.Context, *RecordAnswerRelayRequest) (*RecordAnswerRelayResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method RecordAnswerRelay not implemented")
}
func (UnimplementedPreparationServiceServer) RecordBrief(context.Context, *RecordBriefRequest) (*RecordBriefResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method RecordBrief not implemented")
}
func (UnimplementedPreparationServiceServer) GetBrief(context.Context, *GetBriefRequest) (*GetBriefResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetBrief not implemented")
}
func (UnimplementedPreparationServiceServer) mustEmbedUnimplementedPreparationServiceServer() {}
func (UnimplementedPreparationServiceServer) testEmbeddedByValue()                            {}

// UnsafePreparationServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to PreparationServiceServer will
// result in compilation errors.
type UnsafePreparationServiceServer interface {
	mustEmbedUnimplementedPreparationServiceServer()
}

func RegisterPreparationServiceServer(s grpc.ServiceRegistrar, srv PreparationServiceServer) {
	// If the following call panics, it indicates UnimplementedPreparationServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&PreparationService_ServiceDesc, srv)
}

func _PreparationService_GetPreparation_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetPreparationRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PreparationServiceServer).GetPreparation(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PreparationService_GetPreparation_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PreparationServiceServer).GetPreparation(ctx, req.(*GetPreparationRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PreparationService_RecordQuestionSet_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RecordQuestionSetRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PreparationServiceServer).RecordQuestionSet(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PreparationService_RecordQuestionSet_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PreparationServiceServer).RecordQuestionSet(ctx, req.(*RecordQuestionSetRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PreparationService_SubmitAnswer_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SubmitAnswerRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PreparationServiceServer).SubmitAnswer(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PreparationService_SubmitAnswer_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PreparationServiceServer).SubmitAnswer(ctx, req.(*SubmitAnswerRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PreparationService_GetAnswer_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetAnswerRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PreparationServiceServer).GetAnswer(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PreparationService_GetAnswer_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PreparationServiceServer).GetAnswer(ctx, req.(*GetAnswerRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PreparationService_RecordAnswerRelay_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RecordAnswerRelayRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PreparationServiceServer).RecordAnswerRelay(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PreparationService_RecordAnswerRelay_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PreparationServiceServer).RecordAnswerRelay(ctx, req.(*RecordAnswerRelayRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PreparationService_RecordBrief_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RecordBriefRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PreparationServiceServer).RecordBrief(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PreparationService_RecordBrief_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PreparationServiceServer).RecordBrief(ctx, req.(*RecordBriefRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PreparationService_GetBrief_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetBriefRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PreparationServiceServer).GetBrief(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PreparationService_GetBrief_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PreparationServiceServer).GetBrief(ctx, req.(*GetBriefRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// PreparationService_ServiceDesc is the grpc.ServiceDesc for PreparationService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var PreparationService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "anvilkit.control.v1.PreparationService",
	HandlerType: (*PreparationServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetPreparation",
			Handler:    _PreparationService_GetPreparation_Handler,
		},
		{
			MethodName: "RecordQuestionSet",
			Handler:    _PreparationService_RecordQuestionSet_Handler,
		},
		{
			MethodName: "SubmitAnswer",
			Handler:    _PreparationService_SubmitAnswer_Handler,
		},
		{
			MethodName: "GetAnswer",
			Handler:    _PreparationService_GetAnswer_Handler,
		},
		{
			MethodName: "RecordAnswerRelay",
			Handler:    _PreparationService_RecordAnswerRelay_Handler,
		},
		{
			MethodName: "RecordBrief",
			Handler:    _PreparationService_RecordBrief_Handler,
		},
		{
			MethodName: "GetBrief",
			Handler:    _PreparationService_GetBrief_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "anvilkit/control/v1/preparation.proto",
}
