// Recovery reconciliation of a rollback window (DD-02 §5, platform.md recovery
// gates, delivery.md P07). The ordered steps are driven by the Workflow
// service's RecoveryWorkflow against this service, which owns the state:
// BeginRecovery closes admission for the scope and fences every active
// execution identity under a new recovery epoch in one commit; EnumerateInventory
// reads one resumable page of one obligation class; ReconcileFinding restores a
// missing identity and queries its original outcome; RecordLaunchOutcome records
// the trusted launcher's evidence for a restored launch; EvaluateRecovery
// reopens the scope only when every class is enumerated completely and every
// finding is settled. DisposeObligation is the evidence-bound operator decision
// about one obligation; there is no bulk form.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        (unknown)
// source: anvilkit/control/v1/recovery.proto

package controlv1

import (
	_ "buf.build/gen/go/bufbuild/protovalidate/protocolbuffers/go/buf/validate"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	durationpb "google.golang.org/protobuf/types/known/durationpb"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type RecoveryPhase int32

const (
	RecoveryPhase_RECOVERY_PHASE_UNSPECIFIED RecoveryPhase = 0
	RecoveryPhase_RECOVERY_PHASE_FENCED      RecoveryPhase = 1
	RecoveryPhase_RECOVERY_PHASE_ENUMERATING RecoveryPhase = 2
	RecoveryPhase_RECOVERY_PHASE_RECONCILING RecoveryPhase = 3
	RecoveryPhase_RECOVERY_PHASE_RESTRICTED  RecoveryPhase = 4
	RecoveryPhase_RECOVERY_PHASE_REOPENED    RecoveryPhase = 5
)

// Enum value maps for RecoveryPhase.
var (
	RecoveryPhase_name = map[int32]string{
		0: "RECOVERY_PHASE_UNSPECIFIED",
		1: "RECOVERY_PHASE_FENCED",
		2: "RECOVERY_PHASE_ENUMERATING",
		3: "RECOVERY_PHASE_RECONCILING",
		4: "RECOVERY_PHASE_RESTRICTED",
		5: "RECOVERY_PHASE_REOPENED",
	}
	RecoveryPhase_value = map[string]int32{
		"RECOVERY_PHASE_UNSPECIFIED": 0,
		"RECOVERY_PHASE_FENCED":      1,
		"RECOVERY_PHASE_ENUMERATING": 2,
		"RECOVERY_PHASE_RECONCILING": 3,
		"RECOVERY_PHASE_RESTRICTED":  4,
		"RECOVERY_PHASE_REOPENED":    5,
	}
)

func (x RecoveryPhase) Enum() *RecoveryPhase {
	p := new(RecoveryPhase)
	*p = x
	return p
}

func (x RecoveryPhase) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (RecoveryPhase) Descriptor() protoreflect.EnumDescriptor {
	return file_anvilkit_control_v1_recovery_proto_enumTypes[0].Descriptor()
}

func (RecoveryPhase) Type() protoreflect.EnumType {
	return &file_anvilkit_control_v1_recovery_proto_enumTypes[0]
}

func (x RecoveryPhase) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use RecoveryPhase.Descriptor instead.
func (RecoveryPhase) EnumDescriptor() ([]byte, []int) {
	return file_anvilkit_control_v1_recovery_proto_rawDescGZIP(), []int{0}
}

type FindingStatus int32

const (
	FindingStatus_FINDING_STATUS_UNSPECIFIED   FindingStatus = 0
	FindingStatus_FINDING_STATUS_PRESENT       FindingStatus = 1
	FindingStatus_FINDING_STATUS_MISSING       FindingStatus = 2
	FindingStatus_FINDING_STATUS_RESTORED      FindingStatus = 3
	FindingStatus_FINDING_STATUS_RESOLVED      FindingStatus = 4
	FindingStatus_FINDING_STATUS_UNRESOLVED    FindingStatus = 5
	FindingStatus_FINDING_STATUS_DISPOSED      FindingStatus = 6
	FindingStatus_FINDING_STATUS_OUTSIDE_SCOPE FindingStatus = 7
)

// Enum value maps for FindingStatus.
var (
	FindingStatus_name = map[int32]string{
		0: "FINDING_STATUS_UNSPECIFIED",
		1: "FINDING_STATUS_PRESENT",
		2: "FINDING_STATUS_MISSING",
		3: "FINDING_STATUS_RESTORED",
		4: "FINDING_STATUS_RESOLVED",
		5: "FINDING_STATUS_UNRESOLVED",
		6: "FINDING_STATUS_DISPOSED",
		7: "FINDING_STATUS_OUTSIDE_SCOPE",
	}
	FindingStatus_value = map[string]int32{
		"FINDING_STATUS_UNSPECIFIED":   0,
		"FINDING_STATUS_PRESENT":       1,
		"FINDING_STATUS_MISSING":       2,
		"FINDING_STATUS_RESTORED":      3,
		"FINDING_STATUS_RESOLVED":      4,
		"FINDING_STATUS_UNRESOLVED":    5,
		"FINDING_STATUS_DISPOSED":      6,
		"FINDING_STATUS_OUTSIDE_SCOPE": 7,
	}
)

func (x FindingStatus) Enum() *FindingStatus {
	p := new(FindingStatus)
	*p = x
	return p
}

func (x FindingStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (FindingStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_anvilkit_control_v1_recovery_proto_enumTypes[1].Descriptor()
}

func (FindingStatus) Type() protoreflect.EnumType {
	return &file_anvilkit_control_v1_recovery_proto_enumTypes[1]
}

func (x FindingStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use FindingStatus.Descriptor instead.
func (FindingStatus) EnumDescriptor() ([]byte, []int) {
	return file_anvilkit_control_v1_recovery_proto_rawDescGZIP(), []int{1}
}

type DispositionDecision int32

const (
	DispositionDecision_DISPOSITION_DECISION_UNSPECIFIED       DispositionDecision = 0
	DispositionDecision_DISPOSITION_DECISION_CONFIRM_NOT_SENT  DispositionDecision = 1
	DispositionDecision_DISPOSITION_DECISION_RESOLVE_SUCCEEDED DispositionDecision = 2
	DispositionDecision_DISPOSITION_DECISION_RESOLVE_FAILED    DispositionDecision = 3
	DispositionDecision_DISPOSITION_DECISION_RETAIN_EXPOSURE   DispositionDecision = 4
)

// Enum value maps for DispositionDecision.
var (
	DispositionDecision_name = map[int32]string{
		0: "DISPOSITION_DECISION_UNSPECIFIED",
		1: "DISPOSITION_DECISION_CONFIRM_NOT_SENT",
		2: "DISPOSITION_DECISION_RESOLVE_SUCCEEDED",
		3: "DISPOSITION_DECISION_RESOLVE_FAILED",
		4: "DISPOSITION_DECISION_RETAIN_EXPOSURE",
	}
	DispositionDecision_value = map[string]int32{
		"DISPOSITION_DECISION_UNSPECIFIED":       0,
		"DISPOSITION_DECISION_CONFIRM_NOT_SENT":  1,
		"DISPOSITION_DECISION_RESOLVE_SUCCEEDED": 2,
		"DISPOSITION_DECISION_RESOLVE_FAILED":    3,
		"DISPOSITION_DECISION_RETAIN_EXPOSURE":   4,
	}
)

func (x DispositionDecision) Enum() *DispositionDecision {
	p := new(DispositionDecision)
	*p = x
	return p
}

func (x DispositionDecision) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (DispositionDecision) Descriptor() protoreflect.EnumDescriptor {
	return file_anvilkit_control_v1_recovery_proto_enumTypes[2].Descriptor()
}

func (DispositionDecision) Type() protoreflect.EnumType {
	return &file_anvilkit_control_v1_recovery_proto_enumTypes[2]
}

func (x DispositionDecision) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use DispositionDecision.Descriptor instead.
func (DispositionDecision) EnumDescriptor() ([]byte, []int) {
	return file_anvilkit_control_v1_recovery_proto_rawDescGZIP(), []int{2}
}

type RecoveryRun struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	RunId string                 `protobuf:"bytes,1,opt,name=run_id,json=runId,proto3" json:"run_id,omitempty"`
	// scope_key is a tenant id or "*" for every tenant.
	ScopeKey          string                 `protobuf:"bytes,2,opt,name=scope_key,json=scopeKey,proto3" json:"scope_key,omitempty"`
	RecoveryEpoch     string                 `protobuf:"bytes,3,opt,name=recovery_epoch,json=recoveryEpoch,proto3" json:"recovery_epoch,omitempty"`
	Phase             RecoveryPhase          `protobuf:"varint,4,opt,name=phase,proto3,enum=anvilkit.control.v1.RecoveryPhase" json:"phase,omitempty"`
	WindowStart       *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=window_start,json=windowStart,proto3" json:"window_start,omitempty"`
	WindowEnd         *timestamppb.Timestamp `protobuf:"bytes,6,opt,name=window_end,json=windowEnd,proto3" json:"window_end,omitempty"`
	ClockUncertainty  *durationpb.Duration   `protobuf:"bytes,7,opt,name=clock_uncertainty,json=clockUncertainty,proto3" json:"clock_uncertainty,omitempty"`
	FencedOperations  string                 `protobuf:"bytes,8,opt,name=fenced_operations,json=fencedOperations,proto3" json:"fenced_operations,omitempty"`
	UnsettledFindings string                 `protobuf:"bytes,9,opt,name=unsettled_findings,json=unsettledFindings,proto3" json:"unsettled_findings,omitempty"`
	Progress          []*ClassProgress       `protobuf:"bytes,10,rep,name=progress,proto3" json:"progress,omitempty"`
	CreatedAt         *timestamppb.Timestamp `protobuf:"bytes,11,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	ReopenedAt        *timestamppb.Timestamp `protobuf:"bytes,12,opt,name=reopened_at,json=reopenedAt,proto3,oneof" json:"reopened_at,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *RecoveryRun) Reset() {
	*x = RecoveryRun{}
	mi := &file_anvilkit_control_v1_recovery_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RecoveryRun) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RecoveryRun) ProtoMessage() {}

func (x *RecoveryRun) ProtoReflect() protoreflect.Message {
	mi := &file_anvilkit_control_v1_recovery_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RecoveryRun.ProtoReflect.Descriptor instead.
func (*RecoveryRun) Descriptor() ([]byte, []int) {
	return file_anvilkit_control_v1_recovery_proto_rawDescGZIP(), []int{0}
}

func (x *RecoveryRun) GetRunId() string {
	if x != nil {
		return x.RunId
	}
	return ""
}

func (x *RecoveryRun) GetScopeKey() string {
	if x != nil {
		return x.ScopeKey
	}
	return ""
}

func (x *RecoveryRun) GetRecoveryEpoch() string {
	if x != nil {
		return x.RecoveryEpoch
	}
	return ""
}

func (x *RecoveryRun) GetPhase() RecoveryPhase {
	if x != nil {
		return x.Phase
	}
	return RecoveryPhase_RECOVERY_PHASE_UNSPECIFIED
}

func (x *RecoveryRun) GetWindowStart() *timestamppb.Timestamp {
	if x != nil {
		return x.WindowStart
	}
	return nil
}

func (x *RecoveryRun) GetWindowEnd() *timestamppb.Timestamp {
	if x != nil {
		return x.WindowEnd
	}
	return nil
}

func (x *RecoveryRun) GetClockUncertainty() *durationpb.Duration {
	if x != nil {
		return x.ClockUncertainty
	}
	return nil
}

func (x *RecoveryRun) GetFencedOperations() string {
	if x != nil {
		return x.FencedOperations
	}
	return ""
}

func (x *RecoveryRun) GetUnsettledFindings() string {
	if x != nil {
		return x.UnsettledFindings
	}
	return ""
}

func (x *RecoveryRun) GetProgress() []*ClassProgress {
	if x != nil {
		return x.Progress
	}
	return nil
}

func (x *RecoveryRun) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *RecoveryRun) GetReopenedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.ReopenedAt
	}
	return nil
}

type ClassProgress struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Class         string                 `protobuf:"bytes,1,opt,name=class,proto3" json:"class,omitempty"`
	Cursor        string                 `protobuf:"bytes,2,opt,name=cursor,proto3" json:"cursor,omitempty"`
	Complete      bool                   `protobuf:"varint,3,opt,name=complete,proto3" json:"complete,omitempty"`
	Seen          string                 `protobuf:"bytes,4,opt,name=seen,proto3" json:"seen,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ClassProgress) Reset() {
	*x = ClassProgress{}
	mi := &file_anvilkit_control_v1_recovery_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ClassProgress) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClassProgress) ProtoMessage() {}

func (x *ClassProgress) ProtoReflect() protoreflect.Message {
	mi := &file_anvilkit_control_v1_recovery_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClassProgress.ProtoReflect.Descriptor instead.
func (*ClassProgress) Descriptor() ([]byte, []int) {
	return file_anvilkit_control_v1_recovery_proto_rawDescGZIP(), []int{1}
}

func (x *ClassProgress) GetClass() string {
	if x != nil {
		return x.Class
	}
	return ""
}

func (x *ClassProgress) GetCursor() string {
	if x != nil {
		return x.Cursor
	}
	return ""
}

func (x *ClassProgress) GetComplete() bool {
	if x != nil {
		return x.Complete
	}
	return false
}

func (x *ClassProgress) GetSeen() string {
	if x != nil {
		return x.Seen
	}
	return ""
}

type Finding struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	FindingId        string                 `protobuf:"bytes,1,opt,name=finding_id,json=findingId,proto3" json:"finding_id,omitempty"`
	RunId            string                 `protobuf:"bytes,2,opt,name=run_id,json=runId,proto3" json:"run_id,omitempty"`
	Class            string                 `protobuf:"bytes,3,opt,name=class,proto3" json:"class,omitempty"`
	ObligationId     string                 `protobuf:"bytes,4,opt,name=obligation_id,json=obligationId,proto3" json:"obligation_id,omitempty"`
	TenantId         string                 `protobuf:"bytes,5,opt,name=tenant_id,json=tenantId,proto3" json:"tenant_id,omitempty"`
	InventoryVersion string                 `protobuf:"bytes,6,opt,name=inventory_version,json=inventoryVersion,proto3" json:"inventory_version,omitempty"`
	RecordedAt       *timestamppb.Timestamp `protobuf:"bytes,7,opt,name=recorded_at,json=recordedAt,proto3" json:"recorded_at,omitempty"`
	Status           FindingStatus          `protobuf:"varint,8,opt,name=status,proto3,enum=anvilkit.control.v1.FindingStatus" json:"status,omitempty"`
	Outcome          string                 `protobuf:"bytes,9,opt,name=outcome,proto3" json:"outcome,omitempty"`
	EvidenceRef      string                 `protobuf:"bytes,10,opt,name=evidence_ref,json=evidenceRef,proto3" json:"evidence_ref,omitempty"`
	Detail           string                 `protobuf:"bytes,11,opt,name=detail,proto3" json:"detail,omitempty"`
	// launch_key is set for job-launch findings whose launch the database holds
	// (restored or present): the identity the trusted launcher observes.
	LaunchKey     string `protobuf:"bytes,12,opt,name=launch_key,json=launchKey,proto3" json:"launch_key,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Finding) Reset() {
	*x = Finding{}
	mi := &file_anvilkit_control_v1_recovery_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Finding) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Finding) ProtoMessage() {}

func (x *Finding) ProtoReflect() protoreflect.Message {
	mi := &file_anvilkit_control_v1_recovery_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Finding.ProtoReflect.Descriptor instead.
func (*Finding) Descriptor() ([]byte, []int) {
	return file_anvilkit_control_v1_recovery_proto_rawDescGZIP(), []int{2}
}

func (x *Finding) GetFindingId() string {
	if x != nil {
		return x.FindingId
	}
	return ""
}

func (x *Finding) GetRunId() string {
	if x != nil {
		return x.RunId
	}
	return ""
}

func (x *Finding) GetClass() string {
	if x != nil {
		return x.Class
	}
	return ""
}

func (x *Finding) GetObligationId() string {
	if x != nil {
		return x.ObligationId
	}
	return ""
}

func (x *Finding) GetTenantId() string {
	if x != nil {
		return x.TenantId
	}
	return ""
}

func (x *Finding) GetInventoryVersion() string {
	if x != nil {
		return x.InventoryVersion
	}
	return ""
}

func (x *Finding) GetRecordedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.RecordedAt
	}
	return nil
}

func (x *Finding) GetStatus() FindingStatus {
	if x != nil {
		return x.Status
	}
	return FindingStatus_FINDING_STATUS_UNSPECIFIED
}

func (x *Finding) GetOutcome() string {
	if x != nil {
		return x.Outcome
	}
	return ""
}

func (x *Finding) GetEvidenceRef() string {
	if x != nil {
		return x.EvidenceRef
	}
	return ""
}

func (x *Finding) GetDetail() string {
	if x != nil {
		return x.Detail
	}
	return ""
}

func (x *Finding) GetLaunchKey() string {
	if x != nil {
		return x.LaunchKey
	}
	return ""
}

type BeginRecoveryRequest struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	Command          *CommandIdentity       `protobuf:"bytes,1,opt,name=command,proto3" json:"command,omitempty"`
	ScopeKey         string                 `protobuf:"bytes,2,opt,name=scope_key,json=scopeKey,proto3" json:"scope_key,omitempty"`
	WindowStart      *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=window_start,json=windowStart,proto3" json:"window_start,omitempty"`
	WindowEnd        *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=window_end,json=windowEnd,proto3" json:"window_end,omitempty"`
	ClockUncertainty *durationpb.Duration   `protobuf:"bytes,5,opt,name=clock_uncertainty,json=clockUncertainty,proto3" json:"clock_uncertainty,omitempty"`
	Reason           string                 `protobuf:"bytes,6,opt,name=reason,proto3" json:"reason,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *BeginRecoveryRequest) Reset() {
	*x = BeginRecoveryRequest{}
	mi := &file_anvilkit_control_v1_recovery_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BeginRecoveryRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BeginRecoveryRequest) ProtoMessage() {}

func (x *BeginRecoveryRequest) ProtoReflect() protoreflect.Message {
	mi := &file_anvilkit_control_v1_recovery_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BeginRecoveryRequest.ProtoReflect.Descriptor instead.
func (*BeginRecoveryRequest) Descriptor() ([]byte, []int) {
	return file_anvilkit_control_v1_recovery_proto_rawDescGZIP(), []int{3}
}

func (x *BeginRecoveryRequest) GetCommand() *CommandIdentity {
	if x != nil {
		return x.Command
	}
	return nil
}

func (x *BeginRecoveryRequest) GetScopeKey() string {
	if x != nil {
		return x.ScopeKey
	}
	return ""
}

func (x *BeginRecoveryRequest) GetWindowStart() *timestamppb.Timestamp {
	if x != nil {
		return x.WindowStart
	}
	return nil
}

func (x *BeginRecoveryRequest) GetWindowEnd() *timestamppb.Timestamp {
	if x != nil {
		return x.WindowEnd
	}
	return nil
}

func (x *BeginRecoveryRequest) GetClockUncertainty() *durationpb.Duration {
	if x != nil {
		return x.ClockUncertainty
	}
	return nil
}

func (x *BeginRecoveryRequest) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

type BeginRecoveryResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Run           *RecoveryRun           `protobuf:"bytes,1,opt,name=run,proto3" json:"run,omitempty"`
	Existing      bool                   `protobuf:"varint,2,opt,name=existing,proto3" json:"existing,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BeginRecoveryResponse) Reset() {
	*x = BeginRecoveryResponse{}
	mi := &file_anvilkit_control_v1_recovery_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BeginRecoveryResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BeginRecoveryResponse) ProtoMessage() {}

func (x *BeginRecoveryResponse) ProtoReflect() protoreflect.Message {
	mi := &file_anvilkit_control_v1_recovery_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BeginRecoveryResponse.ProtoReflect.Descriptor instead.
func (*BeginRecoveryResponse) Descriptor() ([]byte, []int) {
	return file_anvilkit_control_v1_recovery_proto_rawDescGZIP(), []int{4}
}

func (x *BeginRecoveryResponse) GetRun() *RecoveryRun {
	if x != nil {
		return x.Run
	}
	return nil
}

func (x *BeginRecoveryResponse) GetExisting() bool {
	if x != nil {
		return x.Existing
	}
	return false
}

type GetRecoveryRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RunId         string                 `protobuf:"bytes,1,opt,name=run_id,json=runId,proto3" json:"run_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetRecoveryRequest) Reset() {
	*x = GetRecoveryRequest{}
	mi := &file_anvilkit_control_v1_recovery_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetRecoveryRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetRecoveryRequest) ProtoMessage() {}

func (x *GetRecoveryRequest) ProtoReflect() protoreflect.Message {
	mi := &file_anvilkit_control_v1_recovery_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetRecoveryRequest.ProtoReflect.Descriptor instead.
func (*GetRecoveryRequest) Descriptor() ([]byte, []int) {
	return file_anvilkit_control_v1_recovery_proto_rawDescGZIP(), []int{5}
}

func (x *GetRecoveryRequest) GetRunId() string {
	if x != nil {
		return x.RunId
	}
	return ""
}

type GetRecoveryResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Run           *RecoveryRun           `protobuf:"bytes,1,opt,name=run,proto3" json:"run,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetRecoveryResponse) Reset() {
	*x = GetRecoveryResponse{}
	mi := &file_anvilkit_control_v1_recovery_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetRecoveryResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetRecoveryResponse) ProtoMessage() {}

func (x *GetRecoveryResponse) ProtoReflect() protoreflect.Message {
	mi := &file_anvilkit_control_v1_recovery_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetRecoveryResponse.ProtoReflect.Descriptor instead.
func (*GetRecoveryResponse) Descriptor() ([]byte, []int) {
	return file_anvilkit_control_v1_recovery_proto_rawDescGZIP(), []int{6}
}

func (x *GetRecoveryResponse) GetRun() *RecoveryRun {
	if x != nil {
		return x.Run
	}
	return nil
}

type EnumerateInventoryRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RunId         string                 `protobuf:"bytes,1,opt,name=run_id,json=runId,proto3" json:"run_id,omitempty"`
	Class         string                 `protobuf:"bytes,2,opt,name=class,proto3" json:"class,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EnumerateInventoryRequest) Reset() {
	*x = EnumerateInventoryRequest{}
	mi := &file_anvilkit_control_v1_recovery_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EnumerateInventoryRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EnumerateInventoryRequest) ProtoMessage() {}

func (x *EnumerateInventoryRequest) ProtoReflect() protoreflect.Message {
	mi := &file_anvilkit_control_v1_recovery_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EnumerateInventoryRequest.ProtoReflect.Descriptor instead.
func (*EnumerateInventoryRequest) Descriptor() ([]byte, []int) {
	return file_anvilkit_control_v1_recovery_proto_rawDescGZIP(), []int{7}
}

func (x *EnumerateInventoryRequest) GetRunId() string {
	if x != nil {
		return x.RunId
	}
	return ""
}

func (x *EnumerateInventoryRequest) GetClass() string {
	if x != nil {
		return x.Class
	}
	return ""
}

type EnumerateInventoryResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Progress      *ClassProgress         `protobuf:"bytes,1,opt,name=progress,proto3" json:"progress,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EnumerateInventoryResponse) Reset() {
	*x = EnumerateInventoryResponse{}
	mi := &file_anvilkit_control_v1_recovery_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EnumerateInventoryResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EnumerateInventoryResponse) ProtoMessage() {}

func (x *EnumerateInventoryResponse) ProtoReflect() protoreflect.Message {
	mi := &file_anvilkit_control_v1_recovery_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EnumerateInventoryResponse.ProtoReflect.Descriptor instead.
func (*EnumerateInventoryResponse) Descriptor() ([]byte, []int) {
	return file_anvilkit_control_v1_recovery_proto_rawDescGZIP(), []int{8}
}

func (x *EnumerateInventoryResponse) GetProgress() *ClassProgress {
	if x != nil {
		return x.Progress
	}
	return nil
}

type ListFindingsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RunId         string                 `protobuf:"bytes,1,opt,name=run_id,json=runId,proto3" json:"run_id,omitempty"`
	Status        FindingStatus          `protobuf:"varint,2,opt,name=status,proto3,enum=anvilkit.control.v1.FindingStatus" json:"status,omitempty"`
	Limit         int32                  `protobuf:"varint,3,opt,name=limit,proto3" json:"limit,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListFindingsRequest) Reset() {
	*x = ListFindingsRequest{}
	mi := &file_anvilkit_control_v1_recovery_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListFindingsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListFindingsRequest) ProtoMessage() {}

func (x *ListFindingsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_anvilkit_control_v1_recovery_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListFindingsRequest.ProtoReflect.Descriptor instead.
func (*ListFindingsRequest) Descriptor() ([]byte, []int) {
	return file_anvilkit_control_v1_recovery_proto_rawDescGZIP(), []int{9}
}

func (x *ListFindingsRequest) GetRunId() string {
	if x != nil {
		return x.RunId
	}
	return ""
}

func (x *ListFindingsRequest) GetStatus() FindingStatus {
	if x != nil {
		return x.Status
	}
	return FindingStatus_FINDING_STATUS_UNSPECIFIED
}

func (x *ListFindingsRequest) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

type ListFindingsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Findings      []*Finding             `protobuf:"bytes,1,rep,name=findings,proto3" json:"findings,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListFindingsResponse) Reset() {
	*x = ListFindingsResponse{}
	mi := &file_anvilkit_control_v1_recovery_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListFindingsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListFindingsResponse) ProtoMessage() {}

func (x *ListFindingsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_anvilkit_control_v1_recovery_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListFindingsResponse.ProtoReflect.Descriptor instead.
func (*ListFindingsResponse) Descriptor() ([]byte, []int) {
	return file_anvilkit_control_v1_recovery_proto_rawDescGZIP(), []int{10}
}

func (x *ListFindingsResponse) GetFindings() []*Finding {
	if x != nil {
		return x.Findings
	}
	return nil
}

type ReconcileFindingRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RunId         string                 `protobuf:"bytes,1,opt,name=run_id,json=runId,proto3" json:"run_id,omitempty"`
	FindingId     string                 `protobuf:"bytes,2,opt,name=finding_id,json=findingId,proto3" json:"finding_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReconcileFindingRequest) Reset() {
	*x = ReconcileFindingRequest{}
	mi := &file_anvilkit_control_v1_recovery_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReconcileFindingRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReconcileFindingRequest) ProtoMessage() {}

func (x *ReconcileFindingRequest) ProtoReflect() protoreflect.Message {
	mi := &file_anvilkit_control_v1_recovery_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReconcileFindingRequest.ProtoReflect.Descriptor instead.
func (*ReconcileFindingRequest) Descriptor() ([]byte, []int) {
	return file_anvilkit_control_v1_recovery_proto_rawDescGZIP(), []int{11}
}

func (x *ReconcileFindingRequest) GetRunId() string {
	if x != nil {
		return x.RunId
	}
	return ""
}

func (x *ReconcileFindingRequest) GetFindingId() string {
	if x != nil {
		return x.FindingId
	}
	return ""
}

type ReconcileFindingResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Finding       *Finding               `protobuf:"bytes,1,opt,name=finding,proto3" json:"finding,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReconcileFindingResponse) Reset() {
	*x = ReconcileFindingResponse{}
	mi := &file_anvilkit_control_v1_recovery_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReconcileFindingResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReconcileFindingResponse) ProtoMessage() {}

func (x *ReconcileFindingResponse) ProtoReflect() protoreflect.Message {
	mi := &file_anvilkit_control_v1_recovery_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReconcileFindingResponse.ProtoReflect.Descriptor instead.
func (*ReconcileFindingResponse) Descriptor() ([]byte, []int) {
	return file_anvilkit_control_v1_recovery_proto_rawDescGZIP(), []int{12}
}

func (x *ReconcileFindingResponse) GetFinding() *Finding {
	if x != nil {
		return x.Finding
	}
	return nil
}

// LaunchPod is one Pod the trusted launcher observed under the original
// launch key.
type LaunchPod struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PodUid        string                 `protobuf:"bytes,1,opt,name=pod_uid,json=podUid,proto3" json:"pod_uid,omitempty"`
	Phase         InstancePhase          `protobuf:"varint,2,opt,name=phase,proto3,enum=anvilkit.control.v1.InstancePhase" json:"phase,omitempty"`
	ExitCode      *int32                 `protobuf:"varint,3,opt,name=exit_code,json=exitCode,proto3,oneof" json:"exit_code,omitempty"`
	ObservedAt    *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=observed_at,json=observedAt,proto3" json:"observed_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LaunchPod) Reset() {
	*x = LaunchPod{}
	mi := &file_anvilkit_control_v1_recovery_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LaunchPod) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LaunchPod) ProtoMessage() {}

func (x *LaunchPod) ProtoReflect() protoreflect.Message {
	mi := &file_anvilkit_control_v1_recovery_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LaunchPod.ProtoReflect.Descriptor instead.
func (*LaunchPod) Descriptor() ([]byte, []int) {
	return file_anvilkit_control_v1_recovery_proto_rawDescGZIP(), []int{13}
}

func (x *LaunchPod) GetPodUid() string {
	if x != nil {
		return x.PodUid
	}
	return ""
}

func (x *LaunchPod) GetPhase() InstancePhase {
	if x != nil {
		return x.Phase
	}
	return InstancePhase_INSTANCE_PHASE_UNSPECIFIED
}

func (x *LaunchPod) GetExitCode() int32 {
	if x != nil && x.ExitCode != nil {
		return *x.ExitCode
	}
	return 0
}

func (x *LaunchPod) GetObservedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.ObservedAt
	}
	return nil
}

type RecordLaunchOutcomeRequest struct {
	state     protoimpl.MessageState `protogen:"open.v1"`
	RunId     string                 `protobuf:"bytes,1,opt,name=run_id,json=runId,proto3" json:"run_id,omitempty"`
	FindingId string                 `protobuf:"bytes,2,opt,name=finding_id,json=findingId,proto3" json:"finding_id,omitempty"`
	JobUid    string                 `protobuf:"bytes,3,opt,name=job_uid,json=jobUid,proto3" json:"job_uid,omitempty"`
	Pods      []*LaunchPod           `protobuf:"bytes,4,rep,name=pods,proto3" json:"pods,omitempty"`
	// stopped is the launcher's confirmation that the backend holds neither
	// the Job nor a Pod under the launch key.
	Stopped       bool `protobuf:"varint,5,opt,name=stopped,proto3" json:"stopped,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RecordLaunchOutcomeRequest) Reset() {
	*x = RecordLaunchOutcomeRequest{}
	mi := &file_anvilkit_control_v1_recovery_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RecordLaunchOutcomeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RecordLaunchOutcomeRequest) ProtoMessage() {}

func (x *RecordLaunchOutcomeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_anvilkit_control_v1_recovery_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RecordLaunchOutcomeRequest.ProtoReflect.Descriptor instead.
func (*RecordLaunchOutcomeRequest) Descriptor() ([]byte, []int) {
	return file_anvilkit_control_v1_recovery_proto_rawDescGZIP(), []int{14}
}

func (x *RecordLaunchOutcomeRequest) GetRunId() string {
	if x != nil {
		return x.RunId
	}
	return ""
}

func (x *RecordLaunchOutcomeRequest) GetFindingId() string {
	if x != nil {
		return x.FindingId
	}
	return ""
}

func (x *RecordLaunchOutcomeRequest) GetJobUid() string {
	if x != nil {
		return x.JobUid
	}
	return ""
}

func (x *RecordLaunchOutcomeRequest) GetPods() []*LaunchPod {
	if x != nil {
		return x.Pods
	}
	return nil
}

func (x *RecordLaunchOutcomeRequest) GetStopped() bool {
	if x != nil {
		return x.Stopped
	}
	return false
}

type RecordLaunchOutcomeResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Finding       *Finding               `protobuf:"bytes,1,opt,name=finding,proto3" json:"finding,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RecordLaunchOutcomeResponse) Reset() {
	*x = RecordLaunchOutcomeResponse{}
	mi := &file_anvilkit_control_v1_recovery_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RecordLaunchOutcomeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RecordLaunchOutcomeResponse) ProtoMessage() {}

func (x *RecordLaunchOutcomeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_anvilkit_control_v1_recovery_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RecordLaunchOutcomeResponse.ProtoReflect.Descriptor instead.
func (*RecordLaunchOutcomeResponse) Descriptor() ([]byte, []int) {
	return file_anvilkit_control_v1_recovery_proto_rawDescGZIP(), []int{15}
}

func (x *RecordLaunchOutcomeResponse) GetFinding() *Finding {
	if x != nil {
		return x.Finding
	}
	return nil
}

type EvaluateRecoveryRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RunId         string                 `protobuf:"bytes,1,opt,name=run_id,json=runId,proto3" json:"run_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EvaluateRecoveryRequest) Reset() {
	*x = EvaluateRecoveryRequest{}
	mi := &file_anvilkit_control_v1_recovery_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EvaluateRecoveryRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EvaluateRecoveryRequest) ProtoMessage() {}

func (x *EvaluateRecoveryRequest) ProtoReflect() protoreflect.Message {
	mi := &file_anvilkit_control_v1_recovery_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EvaluateRecoveryRequest.ProtoReflect.Descriptor instead.
func (*EvaluateRecoveryRequest) Descriptor() ([]byte, []int) {
	return file_anvilkit_control_v1_recovery_proto_rawDescGZIP(), []int{16}
}

func (x *EvaluateRecoveryRequest) GetRunId() string {
	if x != nil {
		return x.RunId
	}
	return ""
}

type EvaluateRecoveryResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Run           *RecoveryRun           `protobuf:"bytes,1,opt,name=run,proto3" json:"run,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EvaluateRecoveryResponse) Reset() {
	*x = EvaluateRecoveryResponse{}
	mi := &file_anvilkit_control_v1_recovery_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EvaluateRecoveryResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EvaluateRecoveryResponse) ProtoMessage() {}

func (x *EvaluateRecoveryResponse) ProtoReflect() protoreflect.Message {
	mi := &file_anvilkit_control_v1_recovery_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EvaluateRecoveryResponse.ProtoReflect.Descriptor instead.
func (*EvaluateRecoveryResponse) Descriptor() ([]byte, []int) {
	return file_anvilkit_control_v1_recovery_proto_rawDescGZIP(), []int{17}
}

func (x *EvaluateRecoveryResponse) GetRun() *RecoveryRun {
	if x != nil {
		return x.Run
	}
	return nil
}

type DisposeObligationRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Command        *CommandIdentity       `protobuf:"bytes,1,opt,name=command,proto3" json:"command,omitempty"`
	Class          string                 `protobuf:"bytes,2,opt,name=class,proto3" json:"class,omitempty"`
	ObligationId   string                 `protobuf:"bytes,3,opt,name=obligation_id,json=obligationId,proto3" json:"obligation_id,omitempty"`
	Decision       DispositionDecision    `protobuf:"varint,4,opt,name=decision,proto3,enum=anvilkit.control.v1.DispositionDecision" json:"decision,omitempty"`
	EvidenceRef    string                 `protobuf:"bytes,5,opt,name=evidence_ref,json=evidenceRef,proto3" json:"evidence_ref,omitempty"`
	EvidenceDigest string                 `protobuf:"bytes,6,opt,name=evidence_digest,json=evidenceDigest,proto3" json:"evidence_digest,omitempty"`
	RecoveryEpoch  string                 `protobuf:"bytes,7,opt,name=recovery_epoch,json=recoveryEpoch,proto3" json:"recovery_epoch,omitempty"`
	RunId          *string                `protobuf:"bytes,8,opt,name=run_id,json=runId,proto3,oneof" json:"run_id,omitempty"`
	Reason         string                 `protobuf:"bytes,9,opt,name=reason,proto3" json:"reason,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *DisposeObligationRequest) Reset() {
	*x = DisposeObligationRequest{}
	mi := &file_anvilkit_control_v1_recovery_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DisposeObligationRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DisposeObligationRequest) ProtoMessage() {}

func (x *DisposeObligationRequest) ProtoReflect() protoreflect.Message {
	mi := &file_anvilkit_control_v1_recovery_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DisposeObligationRequest.ProtoReflect.Descriptor instead.
func (*DisposeObligationRequest) Descriptor() ([]byte, []int) {
	return file_anvilkit_control_v1_recovery_proto_rawDescGZIP(), []int{18}
}

func (x *DisposeObligationRequest) GetCommand() *CommandIdentity {
	if x != nil {
		return x.Command
	}
	return nil
}

func (x *DisposeObligationRequest) GetClass() string {
	if x != nil {
		return x.Class
	}
	return ""
}

func (x *DisposeObligationRequest) GetObligationId() string {
	if x != nil {
		return x.ObligationId
	}
	return ""
}

func (x *DisposeObligationRequest) GetDecision() DispositionDecision {
	if x != nil {
		return x.Decision
	}
	return DispositionDecision_DISPOSITION_DECISION_UNSPECIFIED
}

func (x *DisposeObligationRequest) GetEvidenceRef() string {
	if x != nil {
		return x.EvidenceRef
	}
	return ""
}

func (x *DisposeObligationRequest) GetEvidenceDigest() string {
	if x != nil {
		return x.EvidenceDigest
	}
	return ""
}

func (x *DisposeObligationRequest) GetRecoveryEpoch() string {
	if x != nil {
		return x.RecoveryEpoch
	}
	return ""
}

func (x *DisposeObligationRequest) GetRunId() string {
	if x != nil && x.RunId != nil {
		return *x.RunId
	}
	return ""
}

func (x *DisposeObligationRequest) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

type Disposition struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	DispositionId  string                 `protobuf:"bytes,1,opt,name=disposition_id,json=dispositionId,proto3" json:"disposition_id,omitempty"`
	Class          string                 `protobuf:"bytes,2,opt,name=class,proto3" json:"class,omitempty"`
	ObligationId   string                 `protobuf:"bytes,3,opt,name=obligation_id,json=obligationId,proto3" json:"obligation_id,omitempty"`
	Decision       DispositionDecision    `protobuf:"varint,4,opt,name=decision,proto3,enum=anvilkit.control.v1.DispositionDecision" json:"decision,omitempty"`
	EvidenceRef    string                 `protobuf:"bytes,5,opt,name=evidence_ref,json=evidenceRef,proto3" json:"evidence_ref,omitempty"`
	EvidenceDigest string                 `protobuf:"bytes,6,opt,name=evidence_digest,json=evidenceDigest,proto3" json:"evidence_digest,omitempty"`
	RecoveryEpoch  string                 `protobuf:"bytes,7,opt,name=recovery_epoch,json=recoveryEpoch,proto3" json:"recovery_epoch,omitempty"`
	RunId          *string                `protobuf:"bytes,8,opt,name=run_id,json=runId,proto3,oneof" json:"run_id,omitempty"`
	DecidedAt      *timestamppb.Timestamp `protobuf:"bytes,9,opt,name=decided_at,json=decidedAt,proto3" json:"decided_at,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *Disposition) Reset() {
	*x = Disposition{}
	mi := &file_anvilkit_control_v1_recovery_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Disposition) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Disposition) ProtoMessage() {}

func (x *Disposition) ProtoReflect() protoreflect.Message {
	mi := &file_anvilkit_control_v1_recovery_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Disposition.ProtoReflect.Descriptor instead.
func (*Disposition) Descriptor() ([]byte, []int) {
	return file_anvilkit_control_v1_recovery_proto_rawDescGZIP(), []int{19}
}

func (x *Disposition) GetDispositionId() string {
	if x != nil {
		return x.DispositionId
	}
	return ""
}

func (x *Disposition) GetClass() string {
	if x != nil {
		return x.Class
	}
	return ""
}

func (x *Disposition) GetObligationId() string {
	if x != nil {
		return x.ObligationId
	}
	return ""
}

func (x *Disposition) GetDecision() DispositionDecision {
	if x != nil {
		return x.Decision
	}
	return DispositionDecision_DISPOSITION_DECISION_UNSPECIFIED
}

func (x *Disposition) GetEvidenceRef() string {
	if x != nil {
		return x.EvidenceRef
	}
	return ""
}

func (x *Disposition) GetEvidenceDigest() string {
	if x != nil {
		return x.EvidenceDigest
	}
	return ""
}

func (x *Disposition) GetRecoveryEpoch() string {
	if x != nil {
		return x.RecoveryEpoch
	}
	return ""
}

func (x *Disposition) GetRunId() string {
	if x != nil && x.RunId != nil {
		return *x.RunId
	}
	return ""
}

func (x *Disposition) GetDecidedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.DecidedAt
	}
	return nil
}

type DisposeObligationResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Disposition   *Disposition           `protobuf:"bytes,1,opt,name=disposition,proto3" json:"disposition,omitempty"`
	Existing      bool                   `protobuf:"varint,2,opt,name=existing,proto3" json:"existing,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DisposeObligationResponse) Reset() {
	*x = DisposeObligationResponse{}
	mi := &file_anvilkit_control_v1_recovery_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DisposeObligationResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DisposeObligationResponse) ProtoMessage() {}

func (x *DisposeObligationResponse) ProtoReflect() protoreflect.Message {
	mi := &file_anvilkit_control_v1_recovery_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DisposeObligationResponse.ProtoReflect.Descriptor instead.
func (*DisposeObligationResponse) Descriptor() ([]byte, []int) {
	return file_anvilkit_control_v1_recovery_proto_rawDescGZIP(), []int{20}
}

func (x *DisposeObligationResponse) GetDisposition() *Disposition {
	if x != nil {
		return x.Disposition
	}
	return nil
}

func (x *DisposeObligationResponse) GetExisting() bool {
	if x != nil {
		return x.Existing
	}
	return false
}

var File_anvilkit_control_v1_recovery_proto protoreflect.FileDescriptor

const file_anvilkit_control_v1_recovery_proto_rawDesc = "" +
	"\n" +
	"\"anvilkit/control/v1/recovery.proto\x12\x13anvilkit.control.v1\x1a!anvilkit/control/v1/control.proto\x1a\x1bbuf/validate/validate.proto\x1a\x1egoogle/protobuf/duration.proto\x1a\x1fgoogle/protobuf/timestamp.proto\"\x8d\x05\n" +
	"\vRecoveryRun\x12\x15\n" +
	"\x06run_id\x18\x01 \x01(\tR\x05runId\x12\x1b\n" +
	"\tscope_key\x18\x02 \x01(\tR\bscopeKey\x12%\n" +
	"\x0erecovery_epoch\x18\x03 \x01(\tR\rrecoveryEpoch\x128\n" +
	"\x05phase\x18\x04 \x01(\x0e2\".anvilkit.control.v1.RecoveryPhaseR\x05phase\x12=\n" +
	"\fwindow_start\x18\x05 \x01(\v2\x1a.google.protobuf.TimestampR\vwindowStart\x129\n" +
	"\n" +
	"window_end\x18\x06 \x01(\v2\x1a.google.protobuf.TimestampR\twindowEnd\x12F\n" +
	"\x11clock_uncertainty\x18\a \x01(\v2\x19.google.protobuf.DurationR\x10clockUncertainty\x12+\n" +
	"\x11fenced_operations\x18\b \x01(\tR\x10fencedOperations\x12-\n" +
	"\x12unsettled_findings\x18\t \x01(\tR\x11unsettledFindings\x12>\n" +
	"\bprogress\x18\n" +
	" \x03(\v2\".anvilkit.control.v1.ClassProgressR\bprogress\x129\n" +
	"\n" +
	"created_at\x18\v \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x12@\n" +
	"\vreopened_at\x18\f \x01(\v2\x1a.google.protobuf.TimestampH\x00R\n" +
	"reopenedAt\x88\x01\x01B\x0e\n" +
	"\f_reopened_at\"m\n" +
	"\rClassProgress\x12\x14\n" +
	"\x05class\x18\x01 \x01(\tR\x05class\x12\x16\n" +
	"\x06cursor\x18\x02 \x01(\tR\x06cursor\x12\x1a\n" +
	"\bcomplete\x18\x03 \x01(\bR\bcomplete\x12\x12\n" +
	"\x04seen\x18\x04 \x01(\tR\x04seen\"\xb1\x03\n" +
	"\aFinding\x12\x1d\n" +
	"\n" +
	"finding_id\x18\x01 \x01(\tR\tfindingId\x12\x15\n" +
	"\x06run_id\x18\x02 \x01(\tR\x05runId\x12\x14\n" +
	"\x05class\x18\x03 \x01(\tR\x05class\x12#\n" +
	"\robligation_id\x18\x04 \x01(\tR\fobligationId\x12\x1b\n" +
	"\ttenant_id\x18\x05 \x01(\tR\btenantId\x12+\n" +
	"\x11inventory_version\x18\x06 \x01(\tR\x10inventoryVersion\x12;\n" +
	"\vrecorded_at\x18\a \x01(\v2\x1a.google.protobuf.TimestampR\n" +
	"recordedAt\x12:\n" +
	"\x06status\x18\b \x01(\x0e2\".anvilkit.control.v1.FindingStatusR\x06status\x12\x18\n" +
	"\aoutcome\x18\t \x01(\tR\aoutcome\x12!\n" +
	"\fevidence_ref\x18\n" +
	" \x01(\tR\vevidenceRef\x12\x16\n" +
	"\x06detail\x18\v \x01(\tR\x06detail\x12\x1d\n" +
	"\n" +
	"launch_key\x18\f \x01(\tR\tlaunchKey\"\xfb\x02\n" +
	"\x14BeginRecoveryRequest\x12F\n" +
	"\acommand\x18\x01 \x01(\v2$.anvilkit.control.v1.CommandIdentityB\x06\xbaH\x03\xc8\x01\x01R\acommand\x12'\n" +
	"\tscope_key\x18\x02 \x01(\tB\n" +
	"\xbaH\ar\x05\x10\x01\x18\x80\x01R\bscopeKey\x12E\n" +
	"\fwindow_start\x18\x03 \x01(\v2\x1a.google.protobuf.TimestampB\x06\xbaH\x03\xc8\x01\x01R\vwindowStart\x12A\n" +
	"\n" +
	"window_end\x18\x04 \x01(\v2\x1a.google.protobuf.TimestampB\x06\xbaH\x03\xc8\x01\x01R\twindowEnd\x12F\n" +
	"\x11clock_uncertainty\x18\x05 \x01(\v2\x19.google.protobuf.DurationR\x10clockUncertainty\x12 \n" +
	"\x06reason\x18\x06 \x01(\tB\b\xbaH\x05r\x03\x18\x80\x04R\x06reason\"g\n" +
	"\x15BeginRecoveryResponse\x122\n" +
	"\x03run\x18\x01 \x01(\v2 .anvilkit.control.v1.RecoveryRunR\x03run\x12\x1a\n" +
	"\bexisting\x18\x02 \x01(\bR\bexisting\"7\n" +
	"\x12GetRecoveryRequest\x12!\n" +
	"\x06run_id\x18\x01 \x01(\tB\n" +
	"\xbaH\ar\x05\x10\x01\x18\x80\x01R\x05runId\"I\n" +
	"\x13GetRecoveryResponse\x122\n" +
	"\x03run\x18\x01 \x01(\v2 .anvilkit.control.v1.RecoveryRunR\x03run\"\x9e\x01\n" +
	"\x19EnumerateInventoryRequest\x12!\n" +
	"\x06run_id\x18\x01 \x01(\tB\n" +
	"\xbaH\ar\x05\x10\x01\x18\x80\x01R\x05runId\x12^\n" +
	"\x05class\x18\x02 \x01(\tBH\xbaHErCR\x06intakeR\n" +
	"job-launchR\x0emodel-dispatchR\rtool-dispatchR\x0ebusiness-writeR\x05class\"\\\n" +
	"\x1aEnumerateInventoryResponse\x12>\n" +
	"\bprogress\x18\x01 \x01(\v2\".anvilkit.control.v1.ClassProgressR\bprogress\"\x96\x01\n" +
	"\x13ListFindingsRequest\x12!\n" +
	"\x06run_id\x18\x01 \x01(\tB\n" +
	"\xbaH\ar\x05\x10\x01\x18\x80\x01R\x05runId\x12:\n" +
	"\x06status\x18\x02 \x01(\x0e2\".anvilkit.control.v1.FindingStatusR\x06status\x12 \n" +
	"\x05limit\x18\x03 \x01(\x05B\n" +
	"\xbaH\a\x1a\x05\x18\xe8\a(\x00R\x05limit\"P\n" +
	"\x14ListFindingsResponse\x128\n" +
	"\bfindings\x18\x01 \x03(\v2\x1c.anvilkit.control.v1.FindingR\bfindings\"g\n" +
	"\x17ReconcileFindingRequest\x12!\n" +
	"\x06run_id\x18\x01 \x01(\tB\n" +
	"\xbaH\ar\x05\x10\x01\x18\x80\x01R\x05runId\x12)\n" +
	"\n" +
	"finding_id\x18\x02 \x01(\tB\n" +
	"\xbaH\ar\x05\x10\x01\x18\x80\x01R\tfindingId\"R\n" +
	"\x18ReconcileFindingResponse\x126\n" +
	"\afinding\x18\x01 \x01(\v2\x1c.anvilkit.control.v1.FindingR\afinding\"\xdf\x01\n" +
	"\tLaunchPod\x12#\n" +
	"\apod_uid\x18\x01 \x01(\tB\n" +
	"\xbaH\ar\x05\x10\x01\x18\x80\x01R\x06podUid\x128\n" +
	"\x05phase\x18\x02 \x01(\x0e2\".anvilkit.control.v1.InstancePhaseR\x05phase\x12 \n" +
	"\texit_code\x18\x03 \x01(\x05H\x00R\bexitCode\x88\x01\x01\x12C\n" +
	"\vobserved_at\x18\x04 \x01(\v2\x1a.google.protobuf.TimestampB\x06\xbaH\x03\xc8\x01\x01R\n" +
	"observedAtB\f\n" +
	"\n" +
	"_exit_code\"\xe5\x01\n" +
	"\x1aRecordLaunchOutcomeRequest\x12!\n" +
	"\x06run_id\x18\x01 \x01(\tB\n" +
	"\xbaH\ar\x05\x10\x01\x18\x80\x01R\x05runId\x12)\n" +
	"\n" +
	"finding_id\x18\x02 \x01(\tB\n" +
	"\xbaH\ar\x05\x10\x01\x18\x80\x01R\tfindingId\x12!\n" +
	"\ajob_uid\x18\x03 \x01(\tB\b\xbaH\x05r\x03\x18\x80\x01R\x06jobUid\x12<\n" +
	"\x04pods\x18\x04 \x03(\v2\x1e.anvilkit.control.v1.LaunchPodB\b\xbaH\x05\x92\x01\x02\x10@R\x04pods\x12\x18\n" +
	"\astopped\x18\x05 \x01(\bR\astopped\"U\n" +
	"\x1bRecordLaunchOutcomeResponse\x126\n" +
	"\afinding\x18\x01 \x01(\v2\x1c.anvilkit.control.v1.FindingR\afinding\"<\n" +
	"\x17EvaluateRecoveryRequest\x12!\n" +
	"\x06run_id\x18\x01 \x01(\tB\n" +
	"\xbaH\ar\x05\x10\x01\x18\x80\x01R\x05runId\"N\n" +
	"\x18EvaluateRecoveryResponse\x122\n" +
	"\x03run\x18\x01 \x01(\v2 .anvilkit.control.v1.RecoveryRunR\x03run\"\xd0\x04\n" +
	"\x18DisposeObligationRequest\x12F\n" +
	"\acommand\x18\x01 \x01(\v2$.anvilkit.control.v1.CommandIdentityB\x06\xbaH\x03\xc8\x01\x01R\acommand\x12^\n" +
	"\x05class\x18\x02 \x01(\tBH\xbaHErCR\x06intakeR\n" +
	"job-launchR\x0emodel-dispatchR\rtool-dispatchR\x0ebusiness-writeR\x05class\x12/\n" +
	"\robligation_id\x18\x03 \x01(\tB\n" +
	"\xbaH\ar\x05\x10\x01\x18\x80\x01R\fobligationId\x12P\n" +
	"\bdecision\x18\x04 \x01(\x0e2(.anvilkit.control.v1.DispositionDecisionB\n" +
	"\xbaH\a\x82\x01\x04\x10\x01 \x00R\bdecision\x12-\n" +
	"\fevidence_ref\x18\x05 \x01(\tB\n" +
	"\xbaH\ar\x05\x10\x01\x18\x80\x02R\vevidenceRef\x12E\n" +
	"\x0fevidence_digest\x18\x06 \x01(\tB\x1c\xbaH\x19r\x172\x15^sha256:[0-9a-f]{64}$R\x0eevidenceDigest\x12@\n" +
	"\x0erecovery_epoch\x18\a \x01(\tB\x19\xbaH\x16r\x142\x12^[1-9][0-9]{0,19}$R\rrecoveryEpoch\x12$\n" +
	"\x06run_id\x18\b \x01(\tB\b\xbaH\x05r\x03\x18\x80\x01H\x00R\x05runId\x88\x01\x01\x12 \n" +
	"\x06reason\x18\t \x01(\tB\b\xbaH\x05r\x03\x18\x80\x04R\x06reasonB\t\n" +
	"\a_run_id\"\x8a\x03\n" +
	"\vDisposition\x12%\n" +
	"\x0edisposition_id\x18\x01 \x01(\tR\rdispositionId\x12\x14\n" +
	"\x05class\x18\x02 \x01(\tR\x05class\x12#\n" +
	"\robligation_id\x18\x03 \x01(\tR\fobligationId\x12D\n" +
	"\bdecision\x18\x04 \x01(\x0e2(.anvilkit.control.v1.DispositionDecisionR\bdecision\x12!\n" +
	"\fevidence_ref\x18\x05 \x01(\tR\vevidenceRef\x12'\n" +
	"\x0fevidence_digest\x18\x06 \x01(\tR\x0eevidenceDigest\x12%\n" +
	"\x0erecovery_epoch\x18\a \x01(\tR\rrecoveryEpoch\x12\x1a\n" +
	"\x06run_id\x18\b \x01(\tH\x00R\x05runId\x88\x01\x01\x129\n" +
	"\n" +
	"decided_at\x18\t \x01(\v2\x1a.google.protobuf.TimestampR\tdecidedAtB\t\n" +
	"\a_run_id\"{\n" +
	"\x19DisposeObligationResponse\x12B\n" +
	"\vdisposition\x18\x01 \x01(\v2 .anvilkit.control.v1.DispositionR\vdisposition\x12\x1a\n" +
	"\bexisting\x18\x02 \x01(\bR\bexisting*\xc6\x01\n" +
	"\rRecoveryPhase\x12\x1e\n" +
	"\x1aRECOVERY_PHASE_UNSPECIFIED\x10\x00\x12\x19\n" +
	"\x15RECOVERY_PHASE_FENCED\x10\x01\x12\x1e\n" +
	"\x1aRECOVERY_PHASE_ENUMERATING\x10\x02\x12\x1e\n" +
	"\x1aRECOVERY_PHASE_RECONCILING\x10\x03\x12\x1d\n" +
	"\x19RECOVERY_PHASE_RESTRICTED\x10\x04\x12\x1b\n" +
	"\x17RECOVERY_PHASE_REOPENED\x10\x05*\xff\x01\n" +
	"\rFindingStatus\x12\x1e\n" +
	"\x1aFINDING_STATUS_UNSPECIFIED\x10\x00\x12\x1a\n" +
	"\x16FINDING_STATUS_PRESENT\x10\x01\x12\x1a\n" +
	"\x16FINDING_STATUS_MISSING\x10\x02\x12\x1b\n" +
	"\x17FINDING_STATUS_RESTORED\x10\x03\x12\x1b\n" +
	"\x17FINDING_STATUS_RESOLVED\x10\x04\x12\x1d\n" +
	"\x19FINDING_STATUS_UNRESOLVED\x10\x05\x12\x1b\n" +
	"\x17FINDING_STATUS_DISPOSED\x10\x06\x12 \n" +
	"\x1cFINDING_STATUS_OUTSIDE_SCOPE\x10\a*\xe5\x01\n" +
	"\x13DispositionDecision\x12$\n" +
	" DISPOSITION_DECISION_UNSPECIFIED\x10\x00\x12)\n" +
	"%DISPOSITION_DECISION_CONFIRM_NOT_SENT\x10\x01\x12*\n" +
	"&DISPOSITION_DECISION_RESOLVE_SUCCEEDED\x10\x02\x12'\n" +
	"#DISPOSITION_DECISION_RESOLVE_FAILED\x10\x03\x12(\n" +
	"$DISPOSITION_DECISION_RETAIN_EXPOSURE\x10\x042\x87\a\n" +
	"\x0fRecoveryService\x12f\n" +
	"\rBeginRecovery\x12).anvilkit.control.v1.BeginRecoveryRequest\x1a*.anvilkit.control.v1.BeginRecoveryResponse\x12`\n" +
	"\vGetRecovery\x12'.anvilkit.control.v1.GetRecoveryRequest\x1a(.anvilkit.control.v1.GetRecoveryResponse\x12u\n" +
	"\x12EnumerateInventory\x12..anvilkit.control.v1.EnumerateInventoryRequest\x1a/.anvilkit.control.v1.EnumerateInventoryResponse\x12c\n" +
	"\fListFindings\x12(.anvilkit.control.v1.ListFindingsRequest\x1a).anvilkit.control.v1.ListFindingsResponse\x12o\n" +
	"\x10ReconcileFinding\x12,.anvilkit.control.v1.ReconcileFindingRequest\x1a-.anvilkit.control.v1.ReconcileFindingResponse\x12x\n" +
	"\x13RecordLaunchOutcome\x12/.anvilkit.control.v1.RecordLaunchOutcomeRequest\x1a0.anvilkit.control.v1.RecordLaunchOutcomeResponse\x12o\n" +
	"\x10EvaluateRecovery\x12,.anvilkit.control.v1.EvaluateRecoveryRequest\x1a-.anvilkit.control.v1.EvaluateRecoveryResponse\x12r\n" +
	"\x11DisposeObligation\x12-.anvilkit.control.v1.DisposeObligationRequest\x1a..anvilkit.control.v1.DisposeObligationResponseB\xe5\x01\n" +
	"\x17com.anvilkit.control.v1B\rRecoveryProtoP\x01ZMgithub.com/ancyloce/anvilkit-agent-contracts/go/anvilkit/control/v1;controlv1\xa2\x02\x03ACX\xaa\x02\x13Anvilkit.Control.V1\xca\x02\x13Anvilkit\\Control\\V1\xe2\x02\x1fAnvilkit\\Control\\V1\\GPBMetadata\xea\x02\x15Anvilkit::Control::V1b\x06proto3"

var (
	file_anvilkit_control_v1_recovery_proto_rawDescOnce sync.Once
	file_anvilkit_control_v1_recovery_proto_rawDescData []byte
)

func file_anvilkit_control_v1_recovery_proto_rawDescGZIP() []byte {
	file_anvilkit_control_v1_recovery_proto_rawDescOnce.Do(func() {
		file_anvilkit_control_v1_recovery_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_anvilkit_control_v1_recovery_proto_rawDesc), len(file_anvilkit_control_v1_recovery_proto_rawDesc)))
	})
	return file_anvilkit_control_v1_recovery_proto_rawDescData
}

var file_anvilkit_control_v1_recovery_proto_enumTypes = make([]protoimpl.EnumInfo, 3)
var file_anvilkit_control_v1_recovery_proto_msgTypes = make([]protoimpl.MessageInfo, 21)
var file_anvilkit_control_v1_recovery_proto_goTypes = []any{
	(RecoveryPhase)(0),                  // 0: anvilkit.control.v1.RecoveryPhase
	(FindingStatus)(0),                  // 1: anvilkit.control.v1.FindingStatus
	(DispositionDecision)(0),            // 2: anvilkit.control.v1.DispositionDecision
	(*RecoveryRun)(nil),                 // 3: anvilkit.control.v1.RecoveryRun
	(*ClassProgress)(nil),               // 4: anvilkit.control.v1.ClassProgress
	(*Finding)(nil),                     // 5: anvilkit.control.v1.Finding
	(*BeginRecoveryRequest)(nil),        // 6: anvilkit.control.v1.BeginRecoveryRequest
	(*BeginRecoveryResponse)(nil),       // 7: anvilkit.control.v1.BeginRecoveryResponse
	(*GetRecoveryRequest)(nil),          // 8: anvilkit.control.v1.GetRecoveryRequest
	(*GetRecoveryResponse)(nil),         // 9: anvilkit.control.v1.GetRecoveryResponse
	(*EnumerateInventoryRequest)(nil),   // 10: anvilkit.control.v1.EnumerateInventoryRequest
	(*EnumerateInventoryResponse)(nil),  // 11: anvilkit.control.v1.EnumerateInventoryResponse
	(*ListFindingsRequest)(nil),         // 12: anvilkit.control.v1.ListFindingsRequest
	(*ListFindingsResponse)(nil),        // 13: anvilkit.control.v1.ListFindingsResponse
	(*ReconcileFindingRequest)(nil),     // 14: anvilkit.control.v1.ReconcileFindingRequest
	(*ReconcileFindingResponse)(nil),    // 15: anvilkit.control.v1.ReconcileFindingResponse
	(*LaunchPod)(nil),                   // 16: anvilkit.control.v1.LaunchPod
	(*RecordLaunchOutcomeRequest)(nil),  // 17: anvilkit.control.v1.RecordLaunchOutcomeRequest
	(*RecordLaunchOutcomeResponse)(nil), // 18: anvilkit.control.v1.RecordLaunchOutcomeResponse
	(*EvaluateRecoveryRequest)(nil),     // 19: anvilkit.control.v1.EvaluateRecoveryRequest
	(*EvaluateRecoveryResponse)(nil),    // 20: anvilkit.control.v1.EvaluateRecoveryResponse
	(*DisposeObligationRequest)(nil),    // 21: anvilkit.control.v1.DisposeObligationRequest
	(*Disposition)(nil),                 // 22: anvilkit.control.v1.Disposition
	(*DisposeObligationResponse)(nil),   // 23: anvilkit.control.v1.DisposeObligationResponse
	(*timestamppb.Timestamp)(nil),       // 24: google.protobuf.Timestamp
	(*durationpb.Duration)(nil),         // 25: google.protobuf.Duration
	(*CommandIdentity)(nil),             // 26: anvilkit.control.v1.CommandIdentity
	(InstancePhase)(0),                  // 27: anvilkit.control.v1.InstancePhase
}
var file_anvilkit_control_v1_recovery_proto_depIdxs = []int32{
	0,  // 0: anvilkit.control.v1.RecoveryRun.phase:type_name -> anvilkit.control.v1.RecoveryPhase
	24, // 1: anvilkit.control.v1.RecoveryRun.window_start:type_name -> google.protobuf.Timestamp
	24, // 2: anvilkit.control.v1.RecoveryRun.window_end:type_name -> google.protobuf.Timestamp
	25, // 3: anvilkit.control.v1.RecoveryRun.clock_uncertainty:type_name -> google.protobuf.Duration
	4,  // 4: anvilkit.control.v1.RecoveryRun.progress:type_name -> anvilkit.control.v1.ClassProgress
	24, // 5: anvilkit.control.v1.RecoveryRun.created_at:type_name -> google.protobuf.Timestamp
	24, // 6: anvilkit.control.v1.RecoveryRun.reopened_at:type_name -> google.protobuf.Timestamp
	24, // 7: anvilkit.control.v1.Finding.recorded_at:type_name -> google.protobuf.Timestamp
	1,  // 8: anvilkit.control.v1.Finding.status:type_name -> anvilkit.control.v1.FindingStatus
	26, // 9: anvilkit.control.v1.BeginRecoveryRequest.command:type_name -> anvilkit.control.v1.CommandIdentity
	24, // 10: anvilkit.control.v1.BeginRecoveryRequest.window_start:type_name -> google.protobuf.Timestamp
	24, // 11: anvilkit.control.v1.BeginRecoveryRequest.window_end:type_name -> google.protobuf.Timestamp
	25, // 12: anvilkit.control.v1.BeginRecoveryRequest.clock_uncertainty:type_name -> google.protobuf.Duration
	3,  // 13: anvilkit.control.v1.BeginRecoveryResponse.run:type_name -> anvilkit.control.v1.RecoveryRun
	3,  // 14: anvilkit.control.v1.GetRecoveryResponse.run:type_name -> anvilkit.control.v1.RecoveryRun
	4,  // 15: anvilkit.control.v1.EnumerateInventoryResponse.progress:type_name -> anvilkit.control.v1.ClassProgress
	1,  // 16: anvilkit.control.v1.ListFindingsRequest.status:type_name -> anvilkit.control.v1.FindingStatus
	5,  // 17: anvilkit.control.v1.ListFindingsResponse.findings:type_name -> anvilkit.control.v1.Finding
	5,  // 18: anvilkit.control.v1.ReconcileFindingResponse.finding:type_name -> anvilkit.control.v1.Finding
	27, // 19: anvilkit.control.v1.LaunchPod.phase:type_name -> anvilkit.control.v1.InstancePhase
	24, // 20: anvilkit.control.v1.LaunchPod.observed_at:type_name -> google.protobuf.Timestamp
	16, // 21: anvilkit.control.v1.RecordLaunchOutcomeRequest.pods:type_name -> anvilkit.control.v1.LaunchPod
	5,  // 22: anvilkit.control.v1.RecordLaunchOutcomeResponse.finding:type_name -> anvilkit.control.v1.Finding
	3,  // 23: anvilkit.control.v1.EvaluateRecoveryResponse.run:type_name -> anvilkit.control.v1.RecoveryRun
	26, // 24: anvilkit.control.v1.DisposeObligationRequest.command:type_name -> anvilkit.control.v1.CommandIdentity
	2,  // 25: anvilkit.control.v1.DisposeObligationRequest.decision:type_name -> anvilkit.control.v1.DispositionDecision
	2,  // 26: anvilkit.control.v1.Disposition.decision:type_name -> anvilkit.control.v1.DispositionDecision
	24, // 27: anvilkit.control.v1.Disposition.decided_at:type_name -> google.protobuf.Timestamp
	22, // 28: anvilkit.control.v1.DisposeObligationResponse.disposition:type_name -> anvilkit.control.v1.Disposition
	6,  // 29: anvilkit.control.v1.RecoveryService.BeginRecovery:input_type -> anvilkit.control.v1.BeginRecoveryRequest
	8,  // 30: anvilkit.control.v1.RecoveryService.GetRecovery:input_type -> anvilkit.control.v1.GetRecoveryRequest
	10, // 31: anvilkit.control.v1.RecoveryService.EnumerateInventory:input_type -> anvilkit.control.v1.EnumerateInventoryRequest
	12, // 32: anvilkit.control.v1.RecoveryService.ListFindings:input_type -> anvilkit.control.v1.ListFindingsRequest
	14, // 33: anvilkit.control.v1.RecoveryService.ReconcileFinding:input_type -> anvilkit.control.v1.ReconcileFindingRequest
	17, // 34: anvilkit.control.v1.RecoveryService.RecordLaunchOutcome:input_type -> anvilkit.control.v1.RecordLaunchOutcomeRequest
	19, // 35: anvilkit.control.v1.RecoveryService.EvaluateRecovery:input_type -> anvilkit.control.v1.EvaluateRecoveryRequest
	21, // 36: anvilkit.control.v1.RecoveryService.DisposeObligation:input_type -> anvilkit.control.v1.DisposeObligationRequest
	7,  // 37: anvilkit.control.v1.RecoveryService.BeginRecovery:output_type -> anvilkit.control.v1.BeginRecoveryResponse
	9,  // 38: anvilkit.control.v1.RecoveryService.GetRecovery:output_type -> anvilkit.control.v1.GetRecoveryResponse
	11, // 39: anvilkit.control.v1.RecoveryService.EnumerateInventory:output_type -> anvilkit.control.v1.EnumerateInventoryResponse
	13, // 40: anvilkit.control.v1.RecoveryService.ListFindings:output_type -> anvilkit.control.v1.ListFindingsResponse
	15, // 41: anvilkit.control.v1.RecoveryService.ReconcileFinding:output_type -> anvilkit.control.v1.ReconcileFindingResponse
	18, // 42: anvilkit.control.v1.RecoveryService.RecordLaunchOutcome:output_type -> anvilkit.control.v1.RecordLaunchOutcomeResponse
	20, // 43: anvilkit.control.v1.RecoveryService.EvaluateRecovery:output_type -> anvilkit.control.v1.EvaluateRecoveryResponse
	23, // 44: anvilkit.control.v1.RecoveryService.DisposeObligation:output_type -> anvilkit.control.v1.DisposeObligationResponse
	37, // [37:45] is the sub-list for method output_type
	29, // [29:37] is the sub-list for method input_type
	29, // [29:29] is the sub-list for extension type_name
	29, // [29:29] is the sub-list for extension extendee
	0,  // [0:29] is the sub-list for field type_name
}

func init() { file_anvilkit_control_v1_recovery_proto_init() }
func file_anvilkit_control_v1_recovery_proto_init() {
	if File_anvilkit_control_v1_recovery_proto != nil {
		return
	}
	file_anvilkit_control_v1_control_proto_init()
	file_anvilkit_control_v1_recovery_proto_msgTypes[0].OneofWrappers = []any{}
	file_anvilkit_control_v1_recovery_proto_msgTypes[13].OneofWrappers = []any{}
	file_anvilkit_control_v1_recovery_proto_msgTypes[18].OneofWrappers = []any{}
	file_anvilkit_control_v1_recovery_proto_msgTypes[19].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_anvilkit_control_v1_recovery_proto_rawDesc), len(file_anvilkit_control_v1_recovery_proto_rawDesc)),
			NumEnums:      3,
			NumMessages:   21,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_anvilkit_control_v1_recovery_proto_goTypes,
		DependencyIndexes: file_anvilkit_control_v1_recovery_proto_depIdxs,
		EnumInfos:         file_anvilkit_control_v1_recovery_proto_enumTypes,
		MessageInfos:      file_anvilkit_control_v1_recovery_proto_msgTypes,
	}.Build()
	File_anvilkit_control_v1_recovery_proto = out.File
	file_anvilkit_control_v1_recovery_proto_goTypes = nil
	file_anvilkit_control_v1_recovery_proto_depIdxs = nil
}
