// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.12.3
//   protoc               unknown
// source: anvilkit/control/v1/artifact.proto

/* eslint-disable */
import { BinaryReader, BinaryWriter } from "@bufbuild/protobuf/wire";
import {
  type CallOptions,
  type ChannelCredentials,
  Client,
  type ClientOptions,
  type ClientUnaryCall,
  type handleUnaryCall,
  makeGenericClientConstructor,
  type Metadata,
  type ServiceError,
  type UntypedServiceImplementation,
} from "@grpc/grpc-js";
import { Timestamp } from "../../../google/protobuf/timestamp.js";
import { messageTypeRegistry } from "../../../typeRegistry.js";
import { CommandIdentity, Scope } from "./control.js";

export const protobufPackage = "anvilkit.control.v1";

/**
 * Scoped artifact transfer and acceptance (DD-02 §6). Trusted flows receive an
 * object-scoped capability; candidates receive only an opaque handle. Finalize
 * verifies the actual object version, bytes, size and hash outside DB locks.
 *
 * Every transfer is scoped: begun under a tenant (and, when bound, an
 * operation and attempt with their current execution and recovery epochs),
 * read and resolved only inside that scope, and finalized only while the
 * scope's epochs and deadlines are current. The capability is a short-lived
 * upload authorization for exactly the declared bytes under an object key
 * only Control knows; the key never appears on this surface.
 */

export enum ArtifactClass {
  ARTIFACT_CLASS_UNSPECIFIED = 0,
  ARTIFACT_CLASS_PROMPT = 1,
  ARTIFACT_CLASS_BRIEF = 2,
  ARTIFACT_CLASS_SOURCE = 3,
  ARTIFACT_CLASS_STAGE = 4,
  ARTIFACT_CLASS_RESULT = 5,
  ARTIFACT_CLASS_EVIDENCE = 6,
  ARTIFACT_CLASS_ANSWER = 7,
  ARTIFACT_CLASS_ARGUMENT = 8,
  /**
   * ARTIFACT_CLASS_NPM - The build deliverables of a certified component (DD-04 §2, P10): the
   * npm tarball, the browser ES module and a stylesheet, each a finalized
   * transfer an accepted validator stage binds by exact digest and size.
   */
  ARTIFACT_CLASS_NPM = 9,
  ARTIFACT_CLASS_BROWSER = 10,
  ARTIFACT_CLASS_CSS = 11,
  UNRECOGNIZED = -1,
}

export function artifactClassFromJSON(object: any): ArtifactClass {
  switch (object) {
    case 0:
    case "ARTIFACT_CLASS_UNSPECIFIED":
      return ArtifactClass.ARTIFACT_CLASS_UNSPECIFIED;
    case 1:
    case "ARTIFACT_CLASS_PROMPT":
      return ArtifactClass.ARTIFACT_CLASS_PROMPT;
    case 2:
    case "ARTIFACT_CLASS_BRIEF":
      return ArtifactClass.ARTIFACT_CLASS_BRIEF;
    case 3:
    case "ARTIFACT_CLASS_SOURCE":
      return ArtifactClass.ARTIFACT_CLASS_SOURCE;
    case 4:
    case "ARTIFACT_CLASS_STAGE":
      return ArtifactClass.ARTIFACT_CLASS_STAGE;
    case 5:
    case "ARTIFACT_CLASS_RESULT":
      return ArtifactClass.ARTIFACT_CLASS_RESULT;
    case 6:
    case "ARTIFACT_CLASS_EVIDENCE":
      return ArtifactClass.ARTIFACT_CLASS_EVIDENCE;
    case 7:
    case "ARTIFACT_CLASS_ANSWER":
      return ArtifactClass.ARTIFACT_CLASS_ANSWER;
    case 8:
    case "ARTIFACT_CLASS_ARGUMENT":
      return ArtifactClass.ARTIFACT_CLASS_ARGUMENT;
    case 9:
    case "ARTIFACT_CLASS_NPM":
      return ArtifactClass.ARTIFACT_CLASS_NPM;
    case 10:
    case "ARTIFACT_CLASS_BROWSER":
      return ArtifactClass.ARTIFACT_CLASS_BROWSER;
    case 11:
    case "ARTIFACT_CLASS_CSS":
      return ArtifactClass.ARTIFACT_CLASS_CSS;
    case -1:
    case "UNRECOGNIZED":
    default:
      return ArtifactClass.UNRECOGNIZED;
  }
}

export function artifactClassToJSON(object: ArtifactClass): string {
  switch (object) {
    case ArtifactClass.ARTIFACT_CLASS_UNSPECIFIED:
      return "ARTIFACT_CLASS_UNSPECIFIED";
    case ArtifactClass.ARTIFACT_CLASS_PROMPT:
      return "ARTIFACT_CLASS_PROMPT";
    case ArtifactClass.ARTIFACT_CLASS_BRIEF:
      return "ARTIFACT_CLASS_BRIEF";
    case ArtifactClass.ARTIFACT_CLASS_SOURCE:
      return "ARTIFACT_CLASS_SOURCE";
    case ArtifactClass.ARTIFACT_CLASS_STAGE:
      return "ARTIFACT_CLASS_STAGE";
    case ArtifactClass.ARTIFACT_CLASS_RESULT:
      return "ARTIFACT_CLASS_RESULT";
    case ArtifactClass.ARTIFACT_CLASS_EVIDENCE:
      return "ARTIFACT_CLASS_EVIDENCE";
    case ArtifactClass.ARTIFACT_CLASS_ANSWER:
      return "ARTIFACT_CLASS_ANSWER";
    case ArtifactClass.ARTIFACT_CLASS_ARGUMENT:
      return "ARTIFACT_CLASS_ARGUMENT";
    case ArtifactClass.ARTIFACT_CLASS_NPM:
      return "ARTIFACT_CLASS_NPM";
    case ArtifactClass.ARTIFACT_CLASS_BROWSER:
      return "ARTIFACT_CLASS_BROWSER";
    case ArtifactClass.ARTIFACT_CLASS_CSS:
      return "ARTIFACT_CLASS_CSS";
    case ArtifactClass.UNRECOGNIZED:
    default:
      return "UNRECOGNIZED";
  }
}

export enum TransferState {
  TRANSFER_STATE_UNSPECIFIED = 0,
  TRANSFER_STATE_BEGUN = 1,
  TRANSFER_STATE_FINALIZED = 2,
  TRANSFER_STATE_REJECTED = 3,
  TRANSFER_STATE_EXPIRED = 4,
  UNRECOGNIZED = -1,
}

export function transferStateFromJSON(object: any): TransferState {
  switch (object) {
    case 0:
    case "TRANSFER_STATE_UNSPECIFIED":
      return TransferState.TRANSFER_STATE_UNSPECIFIED;
    case 1:
    case "TRANSFER_STATE_BEGUN":
      return TransferState.TRANSFER_STATE_BEGUN;
    case 2:
    case "TRANSFER_STATE_FINALIZED":
      return TransferState.TRANSFER_STATE_FINALIZED;
    case 3:
    case "TRANSFER_STATE_REJECTED":
      return TransferState.TRANSFER_STATE_REJECTED;
    case 4:
    case "TRANSFER_STATE_EXPIRED":
      return TransferState.TRANSFER_STATE_EXPIRED;
    case -1:
    case "UNRECOGNIZED":
    default:
      return TransferState.UNRECOGNIZED;
  }
}

export function transferStateToJSON(object: TransferState): string {
  switch (object) {
    case TransferState.TRANSFER_STATE_UNSPECIFIED:
      return "TRANSFER_STATE_UNSPECIFIED";
    case TransferState.TRANSFER_STATE_BEGUN:
      return "TRANSFER_STATE_BEGUN";
    case TransferState.TRANSFER_STATE_FINALIZED:
      return "TRANSFER_STATE_FINALIZED";
    case TransferState.TRANSFER_STATE_REJECTED:
      return "TRANSFER_STATE_REJECTED";
    case TransferState.TRANSFER_STATE_EXPIRED:
      return "TRANSFER_STATE_EXPIRED";
    case TransferState.UNRECOGNIZED:
    default:
      return "UNRECOGNIZED";
  }
}

export interface Transfer {
  $type: "anvilkit.control.v1.Transfer";
  transferId: string;
  handle: string;
  class: ArtifactClass;
  expectedDigest: string;
  expectedSize: string;
  state: TransferState;
  deadline: Date | undefined;
  objectVersion?: string | undefined;
  reasonCode?: string | undefined;
  tenantId: string;
  operationId?: string | undefined;
  attemptId?: string | undefined;
  mediaType: string;
  /**
   * The epochs the transfer was begun under; finalization requires them to
   * be current for a bound transfer.
   */
  executionEpoch: string;
  recoveryEpoch: string;
  createdAt: Date | undefined;
  finalizedAt?: Date | undefined;
}

/**
 * TransferCapability is the scoped upload authorization for one transfer:
 * one request of the given method to the URL, carrying exactly the listed
 * headers, with the declared bytes; it expires at expires_at and never
 * outlives the transfer's deadline. It names no bucket, key or credential
 * beyond what the signed URL itself carries, and it is never returned to
 * candidate code.
 */
export interface TransferCapability {
  $type: "anvilkit.control.v1.TransferCapability";
  url: string;
  method: string;
  headers: { [key: string]: string };
  expiresAt: Date | undefined;
}

export interface TransferCapability_HeadersEntry {
  $type: "anvilkit.control.v1.TransferCapability.HeadersEntry";
  key: string;
  value: string;
}

export interface BeginTransferRequest {
  $type: "anvilkit.control.v1.BeginTransferRequest";
  command: CommandIdentity | undefined;
  scope: Scope | undefined;
  class: ArtifactClass;
  expectedDigest: string;
  expectedSize: string;
  mediaType: string;
  operationId?: string | undefined;
  attemptId?: string | undefined;
  deadline: Date | undefined;
}

export interface BeginTransferResponse {
  $type: "anvilkit.control.v1.BeginTransferResponse";
  transfer: Transfer | undefined;
  existing: boolean;
  /**
   * The upload capability for a transfer that is still begun; the caller
   * (a trusted service) decides whether its own client may receive it.
   */
  upload: TransferCapability | undefined;
}

/**
 * ResolveHandle is the trusted harness's path from a candidate's opaque
 * handle to the upload capability: the resolving physical instance must be
 * the current instance of the transfer's attempt under the current epochs.
 */
export interface ResolveHandleRequest {
  $type: "anvilkit.control.v1.ResolveHandleRequest";
  handle: string;
  instanceId: string;
}

export interface ResolveHandleResponse {
  $type: "anvilkit.control.v1.ResolveHandleResponse";
  transfer:
    | Transfer
    | undefined;
  /**
   * Scoped capability for the trusted sidecar; never returned to a candidate.
   * capability is the upload URL; upload carries the same URL with the
   * method and headers the request must use.
   */
  capability: string;
  expiresAt: Date | undefined;
  upload: TransferCapability | undefined;
}

/**
 * FinalizeTransfer names the transfer (by id or by handle) and the exact
 * object version the uploader wrote; Control reads that version and
 * verifies its bytes against the declared size and digest before anything
 * is finalized. Caller claims, ETags and upload receipts are insufficient.
 */
export interface FinalizeTransferRequest {
  $type: "anvilkit.control.v1.FinalizeTransferRequest";
  command: CommandIdentity | undefined;
  transferId: string;
  objectVersion: string;
  instanceId: string;
  handle: string;
}

export interface FinalizeTransferResponse {
  $type: "anvilkit.control.v1.FinalizeTransferResponse";
  transfer: Transfer | undefined;
  existing: boolean;
}

/**
 * GetTransfer reads one transfer (by id or by handle) inside the caller's
 * verified scope; a transfer of another tenant is not found.
 */
export interface GetTransferRequest {
  $type: "anvilkit.control.v1.GetTransferRequest";
  transferId: string;
  scope: Scope | undefined;
  handle: string;
}

export interface GetTransferResponse {
  $type: "anvilkit.control.v1.GetTransferResponse";
  transfer: Transfer | undefined;
}

export interface ReadArtifactRequest {
  $type: "anvilkit.control.v1.ReadArtifactRequest";
  /** The artifact by handle or by transfer id (one of the two). */
  handle: string;
  transferId: string;
  /** The reading operation; the relationship is checked against it. */
  operationId: string;
  /**
   * The reading physical instance when the reader is a Job's trusted
   * sidecar; empty for the Workflow's own reads.
   */
  instanceId: string;
}

export interface ReadArtifactResponse {
  $type: "anvilkit.control.v1.ReadArtifactResponse";
  transfer:
    | Transfer
    | undefined;
  /**
   * The scoped download capability of the exact object version (one GET,
   * the listed headers, valid until expires_at).
   */
  download: TransferCapability | undefined;
}

function createBaseTransfer(): Transfer {
  return {
    $type: "anvilkit.control.v1.Transfer",
    transferId: "",
    handle: "",
    class: 0,
    expectedDigest: "",
    expectedSize: "",
    state: 0,
    deadline: undefined,
    objectVersion: undefined,
    reasonCode: undefined,
    tenantId: "",
    operationId: undefined,
    attemptId: undefined,
    mediaType: "",
    executionEpoch: "",
    recoveryEpoch: "",
    createdAt: undefined,
    finalizedAt: undefined,
  };
}

export const Transfer: MessageFns<Transfer, "anvilkit.control.v1.Transfer"> = {
  $type: "anvilkit.control.v1.Transfer" as const,

  encode(message: Transfer, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.transferId !== "") {
      writer.uint32(10).string(message.transferId);
    }
    if (message.handle !== "") {
      writer.uint32(18).string(message.handle);
    }
    if (message.class !== 0) {
      writer.uint32(24).int32(message.class);
    }
    if (message.expectedDigest !== "") {
      writer.uint32(34).string(message.expectedDigest);
    }
    if (message.expectedSize !== "") {
      writer.uint32(42).string(message.expectedSize);
    }
    if (message.state !== 0) {
      writer.uint32(48).int32(message.state);
    }
    if (message.deadline !== undefined) {
      Timestamp.encode(toTimestamp(message.deadline), writer.uint32(58).fork()).join();
    }
    if (message.objectVersion !== undefined) {
      writer.uint32(66).string(message.objectVersion);
    }
    if (message.reasonCode !== undefined) {
      writer.uint32(74).string(message.reasonCode);
    }
    if (message.tenantId !== "") {
      writer.uint32(82).string(message.tenantId);
    }
    if (message.operationId !== undefined) {
      writer.uint32(90).string(message.operationId);
    }
    if (message.attemptId !== undefined) {
      writer.uint32(98).string(message.attemptId);
    }
    if (message.mediaType !== "") {
      writer.uint32(106).string(message.mediaType);
    }
    if (message.executionEpoch !== "") {
      writer.uint32(114).string(message.executionEpoch);
    }
    if (message.recoveryEpoch !== "") {
      writer.uint32(122).string(message.recoveryEpoch);
    }
    if (message.createdAt !== undefined) {
      Timestamp.encode(toTimestamp(message.createdAt), writer.uint32(130).fork()).join();
    }
    if (message.finalizedAt !== undefined) {
      Timestamp.encode(toTimestamp(message.finalizedAt), writer.uint32(138).fork()).join();
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): Transfer {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const previousRecursionDepth = (reader as any).__tsProtoDecodeDepth ?? 0;
    if (previousRecursionDepth >= 100) {
      throw new globalThis.Error("protobuf decode recursion limit exceeded");
    }
    (reader as any).__tsProtoDecodeDepth = previousRecursionDepth + 1;
    try {
      const end = length === undefined ? reader.len : reader.pos + length;
      const message = createBaseTransfer();
      while (reader.pos < end) {
        const tag = reader.uint32();
        switch (tag >>> 3) {
          case 1: {
            if (tag !== 10) {
              break;
            }

            message.transferId = reader.string();
            continue;
          }
          case 2: {
            if (tag !== 18) {
              break;
            }

            message.handle = reader.string();
            continue;
          }
          case 3: {
            if (tag !== 24) {
              break;
            }

            message.class = reader.int32() as any;
            continue;
          }
          case 4: {
            if (tag !== 34) {
              break;
            }

            message.expectedDigest = reader.string();
            continue;
          }
          case 5: {
            if (tag !== 42) {
              break;
            }

            message.expectedSize = reader.string();
            continue;
          }
          case 6: {
            if (tag !== 48) {
              break;
            }

            message.state = reader.int32() as any;
            continue;
          }
          case 7: {
            if (tag !== 58) {
              break;
            }

            message.deadline = fromTimestamp(Timestamp.decode(reader, reader.uint32()));
            continue;
          }
          case 8: {
            if (tag !== 66) {
              break;
            }

            message.objectVersion = reader.string();
            continue;
          }
          case 9: {
            if (tag !== 74) {
              break;
            }

            message.reasonCode = reader.string();
            continue;
          }
          case 10: {
            if (tag !== 82) {
              break;
            }

            message.tenantId = reader.string();
            continue;
          }
          case 11: {
            if (tag !== 90) {
              break;
            }

            message.operationId = reader.string();
            continue;
          }
          case 12: {
            if (tag !== 98) {
              break;
            }

            message.attemptId = reader.string();
            continue;
          }
          case 13: {
            if (tag !== 106) {
              break;
            }

            message.mediaType = reader.string();
            continue;
          }
          case 14: {
            if (tag !== 114) {
              break;
            }

            message.executionEpoch = reader.string();
            continue;
          }
          case 15: {
            if (tag !== 122) {
              break;
            }

            message.recoveryEpoch = reader.string();
            continue;
          }
          case 16: {
            if (tag !== 130) {
              break;
            }

            message.createdAt = fromTimestamp(Timestamp.decode(reader, reader.uint32()));
            continue;
          }
          case 17: {
            if (tag !== 138) {
              break;
            }

            message.finalizedAt = fromTimestamp(Timestamp.decode(reader, reader.uint32()));
            continue;
          }
        }
        if ((tag & 7) === 4 || tag === 0) {
          break;
        }
        reader.skip(tag & 7);
      }
      return message;
    } finally {
      (reader as any).__tsProtoDecodeDepth = previousRecursionDepth;
    }
  },

  fromJSON(object: any): Transfer {
    return {
      $type: Transfer.$type,
      transferId: isSet(object.transferId)
        ? globalThis.String(object.transferId)
        : isSet(object.transfer_id)
        ? globalThis.String(object.transfer_id)
        : "",
      handle: isSet(object.handle) ? globalThis.String(object.handle) : "",
      class: isSet(object.class) ? artifactClassFromJSON(object.class) : 0,
      expectedDigest: isSet(object.expectedDigest)
        ? globalThis.String(object.expectedDigest)
        : isSet(object.expected_digest)
        ? globalThis.String(object.expected_digest)
        : "",
      expectedSize: isSet(object.expectedSize)
        ? globalThis.String(object.expectedSize)
        : isSet(object.expected_size)
        ? globalThis.String(object.expected_size)
        : "",
      state: isSet(object.state) ? transferStateFromJSON(object.state) : 0,
      deadline: isSet(object.deadline) ? fromJsonTimestamp(object.deadline) : undefined,
      objectVersion: isSet(object.objectVersion)
        ? globalThis.String(object.objectVersion)
        : isSet(object.object_version)
        ? globalThis.String(object.object_version)
        : undefined,
      reasonCode: isSet(object.reasonCode)
        ? globalThis.String(object.reasonCode)
        : isSet(object.reason_code)
        ? globalThis.String(object.reason_code)
        : undefined,
      tenantId: isSet(object.tenantId)
        ? globalThis.String(object.tenantId)
        : isSet(object.tenant_id)
        ? globalThis.String(object.tenant_id)
        : "",
      operationId: isSet(object.operationId)
        ? globalThis.String(object.operationId)
        : isSet(object.operation_id)
        ? globalThis.String(object.operation_id)
        : undefined,
      attemptId: isSet(object.attemptId)
        ? globalThis.String(object.attemptId)
        : isSet(object.attempt_id)
        ? globalThis.String(object.attempt_id)
        : undefined,
      mediaType: isSet(object.mediaType)
        ? globalThis.String(object.mediaType)
        : isSet(object.media_type)
        ? globalThis.String(object.media_type)
        : "",
      executionEpoch: isSet(object.executionEpoch)
        ? globalThis.String(object.executionEpoch)
        : isSet(object.execution_epoch)
        ? globalThis.String(object.execution_epoch)
        : "",
      recoveryEpoch: isSet(object.recoveryEpoch)
        ? globalThis.String(object.recoveryEpoch)
        : isSet(object.recovery_epoch)
        ? globalThis.String(object.recovery_epoch)
        : "",
      createdAt: isSet(object.createdAt)
        ? fromJsonTimestamp(object.createdAt)
        : isSet(object.created_at)
        ? fromJsonTimestamp(object.created_at)
        : undefined,
      finalizedAt: isSet(object.finalizedAt)
        ? fromJsonTimestamp(object.finalizedAt)
        : isSet(object.finalized_at)
        ? fromJsonTimestamp(object.finalized_at)
        : undefined,
    };
  },

  toJSON(message: Transfer): unknown {
    const obj: any = {};
    if (message.transferId !== "") {
      obj.transferId = message.transferId;
    }
    if (message.handle !== "") {
      obj.handle = message.handle;
    }
    if (message.class !== 0) {
      obj.class = artifactClassToJSON(message.class);
    }
    if (message.expectedDigest !== "") {
      obj.expectedDigest = message.expectedDigest;
    }
    if (message.expectedSize !== "") {
      obj.expectedSize = message.expectedSize;
    }
    if (message.state !== 0) {
      obj.state = transferStateToJSON(message.state);
    }
    if (message.deadline !== undefined) {
      obj.deadline = message.deadline.toISOString();
    }
    if (message.objectVersion !== undefined) {
      obj.objectVersion = message.objectVersion;
    }
    if (message.reasonCode !== undefined) {
      obj.reasonCode = message.reasonCode;
    }
    if (message.tenantId !== "") {
      obj.tenantId = message.tenantId;
    }
    if (message.operationId !== undefined) {
      obj.operationId = message.operationId;
    }
    if (message.attemptId !== undefined) {
      obj.attemptId = message.attemptId;
    }
    if (message.mediaType !== "") {
      obj.mediaType = message.mediaType;
    }
    if (message.executionEpoch !== "") {
      obj.executionEpoch = message.executionEpoch;
    }
    if (message.recoveryEpoch !== "") {
      obj.recoveryEpoch = message.recoveryEpoch;
    }
    if (message.createdAt !== undefined) {
      obj.createdAt = message.createdAt.toISOString();
    }
    if (message.finalizedAt !== undefined) {
      obj.finalizedAt = message.finalizedAt.toISOString();
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<Transfer>, I>>(base?: I): Transfer {
    return Transfer.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<Transfer>, I>>(object: I): Transfer {
    const message = createBaseTransfer();
    message.transferId = object.transferId ?? "";
    message.handle = object.handle ?? "";
    message.class = object.class ?? 0;
    message.expectedDigest = object.expectedDigest ?? "";
    message.expectedSize = object.expectedSize ?? "";
    message.state = object.state ?? 0;
    message.deadline = object.deadline ?? undefined;
    message.objectVersion = object.objectVersion ?? undefined;
    message.reasonCode = object.reasonCode ?? undefined;
    message.tenantId = object.tenantId ?? "";
    message.operationId = object.operationId ?? undefined;
    message.attemptId = object.attemptId ?? undefined;
    message.mediaType = object.mediaType ?? "";
    message.executionEpoch = object.executionEpoch ?? "";
    message.recoveryEpoch = object.recoveryEpoch ?? "";
    message.createdAt = object.createdAt ?? undefined;
    message.finalizedAt = object.finalizedAt ?? undefined;
    return message;
  },
};

messageTypeRegistry.set(Transfer.$type, Transfer);

function createBaseTransferCapability(): TransferCapability {
  return { $type: "anvilkit.control.v1.TransferCapability", url: "", method: "", headers: {}, expiresAt: undefined };
}

export const TransferCapability: MessageFns<TransferCapability, "anvilkit.control.v1.TransferCapability"> = {
  $type: "anvilkit.control.v1.TransferCapability" as const,

  encode(message: TransferCapability, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.url !== "") {
      writer.uint32(10).string(message.url);
    }
    if (message.method !== "") {
      writer.uint32(18).string(message.method);
    }
    globalThis.Object.entries(message.headers).forEach(([key, value]: [string, string]) => {
      TransferCapability_HeadersEntry.encode({
        $type: "anvilkit.control.v1.TransferCapability.HeadersEntry",
        key: key as any,
        value,
      }, writer.uint32(26).fork()).join();
    });
    if (message.expiresAt !== undefined) {
      Timestamp.encode(toTimestamp(message.expiresAt), writer.uint32(34).fork()).join();
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): TransferCapability {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const previousRecursionDepth = (reader as any).__tsProtoDecodeDepth ?? 0;
    if (previousRecursionDepth >= 100) {
      throw new globalThis.Error("protobuf decode recursion limit exceeded");
    }
    (reader as any).__tsProtoDecodeDepth = previousRecursionDepth + 1;
    try {
      const end = length === undefined ? reader.len : reader.pos + length;
      const message = createBaseTransferCapability();
      while (reader.pos < end) {
        const tag = reader.uint32();
        switch (tag >>> 3) {
          case 1: {
            if (tag !== 10) {
              break;
            }

            message.url = reader.string();
            continue;
          }
          case 2: {
            if (tag !== 18) {
              break;
            }

            message.method = reader.string();
            continue;
          }
          case 3: {
            if (tag !== 26) {
              break;
            }

            const entry3 = TransferCapability_HeadersEntry.decode(reader, reader.uint32());
            if (entry3.value !== undefined) {
              message.headers[entry3.key] = entry3.value;
            }
            continue;
          }
          case 4: {
            if (tag !== 34) {
              break;
            }

            message.expiresAt = fromTimestamp(Timestamp.decode(reader, reader.uint32()));
            continue;
          }
        }
        if ((tag & 7) === 4 || tag === 0) {
          break;
        }
        reader.skip(tag & 7);
      }
      return message;
    } finally {
      (reader as any).__tsProtoDecodeDepth = previousRecursionDepth;
    }
  },

  fromJSON(object: any): TransferCapability {
    return {
      $type: TransferCapability.$type,
      url: isSet(object.url) ? globalThis.String(object.url) : "",
      method: isSet(object.method) ? globalThis.String(object.method) : "",
      headers: isObject(object.headers)
        ? (globalThis.Object.entries(object.headers) as [string, any][]).reduce(
          (acc: { [key: string]: string }, [key, value]: [string, any]) => {
            globalThis.Object.defineProperty(acc, key, {
              value: globalThis.String(value),
              enumerable: true,
              configurable: true,
              writable: true,
            });
            return acc;
          },
          {},
        )
        : {},
      expiresAt: isSet(object.expiresAt)
        ? fromJsonTimestamp(object.expiresAt)
        : isSet(object.expires_at)
        ? fromJsonTimestamp(object.expires_at)
        : undefined,
    };
  },

  toJSON(message: TransferCapability): unknown {
    const obj: any = {};
    if (message.url !== "") {
      obj.url = message.url;
    }
    if (message.method !== "") {
      obj.method = message.method;
    }
    if (message.headers) {
      const entries = globalThis.Object.entries(message.headers) as [string, string][];
      if (entries.length > 0) {
        obj.headers = {};
        entries.forEach(([k, v]) => {
          obj.headers[k] = v;
        });
      }
    }
    if (message.expiresAt !== undefined) {
      obj.expiresAt = message.expiresAt.toISOString();
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<TransferCapability>, I>>(base?: I): TransferCapability {
    return TransferCapability.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<TransferCapability>, I>>(object: I): TransferCapability {
    const message = createBaseTransferCapability();
    message.url = object.url ?? "";
    message.method = object.method ?? "";
    message.headers = (globalThis.Object.entries(object.headers ?? {}) as [string, string][]).reduce(
      (acc: { [key: string]: string }, [key, value]: [string, string]) => {
        if (value !== undefined) {
          acc[key] = globalThis.String(value);
        }
        return acc;
      },
      {},
    );
    message.expiresAt = object.expiresAt ?? undefined;
    return message;
  },
};

messageTypeRegistry.set(TransferCapability.$type, TransferCapability);

function createBaseTransferCapability_HeadersEntry(): TransferCapability_HeadersEntry {
  return { $type: "anvilkit.control.v1.TransferCapability.HeadersEntry", key: "", value: "" };
}

export const TransferCapability_HeadersEntry: MessageFns<
  TransferCapability_HeadersEntry,
  "anvilkit.control.v1.TransferCapability.HeadersEntry"
> = {
  $type: "anvilkit.control.v1.TransferCapability.HeadersEntry" as const,

  encode(message: TransferCapability_HeadersEntry, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.key !== "") {
      writer.uint32(10).string(message.key);
    }
    if (message.value !== "") {
      writer.uint32(18).string(message.value);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): TransferCapability_HeadersEntry {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const previousRecursionDepth = (reader as any).__tsProtoDecodeDepth ?? 0;
    if (previousRecursionDepth >= 100) {
      throw new globalThis.Error("protobuf decode recursion limit exceeded");
    }
    (reader as any).__tsProtoDecodeDepth = previousRecursionDepth + 1;
    try {
      const end = length === undefined ? reader.len : reader.pos + length;
      const message = createBaseTransferCapability_HeadersEntry();
      while (reader.pos < end) {
        const tag = reader.uint32();
        switch (tag >>> 3) {
          case 1: {
            if (tag !== 10) {
              break;
            }

            message.key = reader.string();
            continue;
          }
          case 2: {
            if (tag !== 18) {
              break;
            }

            message.value = reader.string();
            continue;
          }
        }
        if ((tag & 7) === 4 || tag === 0) {
          break;
        }
        reader.skip(tag & 7);
      }
      return message;
    } finally {
      (reader as any).__tsProtoDecodeDepth = previousRecursionDepth;
    }
  },

  fromJSON(object: any): TransferCapability_HeadersEntry {
    return {
      $type: TransferCapability_HeadersEntry.$type,
      key: isSet(object.key) ? globalThis.String(object.key) : "",
      value: isSet(object.value) ? globalThis.String(object.value) : "",
    };
  },

  toJSON(message: TransferCapability_HeadersEntry): unknown {
    const obj: any = {};
    if (message.key !== "") {
      obj.key = message.key;
    }
    if (message.value !== "") {
      obj.value = message.value;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<TransferCapability_HeadersEntry>, I>>(base?: I): TransferCapability_HeadersEntry {
    return TransferCapability_HeadersEntry.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<TransferCapability_HeadersEntry>, I>>(
    object: I,
  ): TransferCapability_HeadersEntry {
    const message = createBaseTransferCapability_HeadersEntry();
    message.key = object.key ?? "";
    message.value = object.value ?? "";
    return message;
  },
};

messageTypeRegistry.set(TransferCapability_HeadersEntry.$type, TransferCapability_HeadersEntry);

function createBaseBeginTransferRequest(): BeginTransferRequest {
  return {
    $type: "anvilkit.control.v1.BeginTransferRequest",
    command: undefined,
    scope: undefined,
    class: 0,
    expectedDigest: "",
    expectedSize: "",
    mediaType: "",
    operationId: undefined,
    attemptId: undefined,
    deadline: undefined,
  };
}

export const BeginTransferRequest: MessageFns<BeginTransferRequest, "anvilkit.control.v1.BeginTransferRequest"> = {
  $type: "anvilkit.control.v1.BeginTransferRequest" as const,

  encode(message: BeginTransferRequest, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.command !== undefined) {
      CommandIdentity.encode(message.command, writer.uint32(10).fork()).join();
    }
    if (message.scope !== undefined) {
      Scope.encode(message.scope, writer.uint32(18).fork()).join();
    }
    if (message.class !== 0) {
      writer.uint32(24).int32(message.class);
    }
    if (message.expectedDigest !== "") {
      writer.uint32(34).string(message.expectedDigest);
    }
    if (message.expectedSize !== "") {
      writer.uint32(42).string(message.expectedSize);
    }
    if (message.mediaType !== "") {
      writer.uint32(50).string(message.mediaType);
    }
    if (message.operationId !== undefined) {
      writer.uint32(58).string(message.operationId);
    }
    if (message.attemptId !== undefined) {
      writer.uint32(66).string(message.attemptId);
    }
    if (message.deadline !== undefined) {
      Timestamp.encode(toTimestamp(message.deadline), writer.uint32(74).fork()).join();
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): BeginTransferRequest {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const previousRecursionDepth = (reader as any).__tsProtoDecodeDepth ?? 0;
    if (previousRecursionDepth >= 100) {
      throw new globalThis.Error("protobuf decode recursion limit exceeded");
    }
    (reader as any).__tsProtoDecodeDepth = previousRecursionDepth + 1;
    try {
      const end = length === undefined ? reader.len : reader.pos + length;
      const message = createBaseBeginTransferRequest();
      while (reader.pos < end) {
        const tag = reader.uint32();
        switch (tag >>> 3) {
          case 1: {
            if (tag !== 10) {
              break;
            }

            message.command = CommandIdentity.decode(reader, reader.uint32());
            continue;
          }
          case 2: {
            if (tag !== 18) {
              break;
            }

            message.scope = Scope.decode(reader, reader.uint32());
            continue;
          }
          case 3: {
            if (tag !== 24) {
              break;
            }

            message.class = reader.int32() as any;
            continue;
          }
          case 4: {
            if (tag !== 34) {
              break;
            }

            message.expectedDigest = reader.string();
            continue;
          }
          case 5: {
            if (tag !== 42) {
              break;
            }

            message.expectedSize = reader.string();
            continue;
          }
          case 6: {
            if (tag !== 50) {
              break;
            }

            message.mediaType = reader.string();
            continue;
          }
          case 7: {
            if (tag !== 58) {
              break;
            }

            message.operationId = reader.string();
            continue;
          }
          case 8: {
            if (tag !== 66) {
              break;
            }

            message.attemptId = reader.string();
            continue;
          }
          case 9: {
            if (tag !== 74) {
              break;
            }

            message.deadline = fromTimestamp(Timestamp.decode(reader, reader.uint32()));
            continue;
          }
        }
        if ((tag & 7) === 4 || tag === 0) {
          break;
        }
        reader.skip(tag & 7);
      }
      return message;
    } finally {
      (reader as any).__tsProtoDecodeDepth = previousRecursionDepth;
    }
  },

  fromJSON(object: any): BeginTransferRequest {
    return {
      $type: BeginTransferRequest.$type,
      command: isSet(object.command) ? CommandIdentity.fromJSON(object.command) : undefined,
      scope: isSet(object.scope) ? Scope.fromJSON(object.scope) : undefined,
      class: isSet(object.class) ? artifactClassFromJSON(object.class) : 0,
      expectedDigest: isSet(object.expectedDigest)
        ? globalThis.String(object.expectedDigest)
        : isSet(object.expected_digest)
        ? globalThis.String(object.expected_digest)
        : "",
      expectedSize: isSet(object.expectedSize)
        ? globalThis.String(object.expectedSize)
        : isSet(object.expected_size)
        ? globalThis.String(object.expected_size)
        : "",
      mediaType: isSet(object.mediaType)
        ? globalThis.String(object.mediaType)
        : isSet(object.media_type)
        ? globalThis.String(object.media_type)
        : "",
      operationId: isSet(object.operationId)
        ? globalThis.String(object.operationId)
        : isSet(object.operation_id)
        ? globalThis.String(object.operation_id)
        : undefined,
      attemptId: isSet(object.attemptId)
        ? globalThis.String(object.attemptId)
        : isSet(object.attempt_id)
        ? globalThis.String(object.attempt_id)
        : undefined,
      deadline: isSet(object.deadline) ? fromJsonTimestamp(object.deadline) : undefined,
    };
  },

  toJSON(message: BeginTransferRequest): unknown {
    const obj: any = {};
    if (message.command !== undefined) {
      obj.command = CommandIdentity.toJSON(message.command);
    }
    if (message.scope !== undefined) {
      obj.scope = Scope.toJSON(message.scope);
    }
    if (message.class !== 0) {
      obj.class = artifactClassToJSON(message.class);
    }
    if (message.expectedDigest !== "") {
      obj.expectedDigest = message.expectedDigest;
    }
    if (message.expectedSize !== "") {
      obj.expectedSize = message.expectedSize;
    }
    if (message.mediaType !== "") {
      obj.mediaType = message.mediaType;
    }
    if (message.operationId !== undefined) {
      obj.operationId = message.operationId;
    }
    if (message.attemptId !== undefined) {
      obj.attemptId = message.attemptId;
    }
    if (message.deadline !== undefined) {
      obj.deadline = message.deadline.toISOString();
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<BeginTransferRequest>, I>>(base?: I): BeginTransferRequest {
    return BeginTransferRequest.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<BeginTransferRequest>, I>>(object: I): BeginTransferRequest {
    const message = createBaseBeginTransferRequest();
    message.command = (object.command !== undefined && object.command !== null)
      ? CommandIdentity.fromPartial(object.command)
      : undefined;
    message.scope = (object.scope !== undefined && object.scope !== null) ? Scope.fromPartial(object.scope) : undefined;
    message.class = object.class ?? 0;
    message.expectedDigest = object.expectedDigest ?? "";
    message.expectedSize = object.expectedSize ?? "";
    message.mediaType = object.mediaType ?? "";
    message.operationId = object.operationId ?? undefined;
    message.attemptId = object.attemptId ?? undefined;
    message.deadline = object.deadline ?? undefined;
    return message;
  },
};

messageTypeRegistry.set(BeginTransferRequest.$type, BeginTransferRequest);

function createBaseBeginTransferResponse(): BeginTransferResponse {
  return {
    $type: "anvilkit.control.v1.BeginTransferResponse",
    transfer: undefined,
    existing: false,
    upload: undefined,
  };
}

export const BeginTransferResponse: MessageFns<BeginTransferResponse, "anvilkit.control.v1.BeginTransferResponse"> = {
  $type: "anvilkit.control.v1.BeginTransferResponse" as const,

  encode(message: BeginTransferResponse, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.transfer !== undefined) {
      Transfer.encode(message.transfer, writer.uint32(10).fork()).join();
    }
    if (message.existing !== false) {
      writer.uint32(16).bool(message.existing);
    }
    if (message.upload !== undefined) {
      TransferCapability.encode(message.upload, writer.uint32(26).fork()).join();
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): BeginTransferResponse {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const previousRecursionDepth = (reader as any).__tsProtoDecodeDepth ?? 0;
    if (previousRecursionDepth >= 100) {
      throw new globalThis.Error("protobuf decode recursion limit exceeded");
    }
    (reader as any).__tsProtoDecodeDepth = previousRecursionDepth + 1;
    try {
      const end = length === undefined ? reader.len : reader.pos + length;
      const message = createBaseBeginTransferResponse();
      while (reader.pos < end) {
        const tag = reader.uint32();
        switch (tag >>> 3) {
          case 1: {
            if (tag !== 10) {
              break;
            }

            message.transfer = Transfer.decode(reader, reader.uint32());
            continue;
          }
          case 2: {
            if (tag !== 16) {
              break;
            }

            message.existing = reader.bool();
            continue;
          }
          case 3: {
            if (tag !== 26) {
              break;
            }

            message.upload = TransferCapability.decode(reader, reader.uint32());
            continue;
          }
        }
        if ((tag & 7) === 4 || tag === 0) {
          break;
        }
        reader.skip(tag & 7);
      }
      return message;
    } finally {
      (reader as any).__tsProtoDecodeDepth = previousRecursionDepth;
    }
  },

  fromJSON(object: any): BeginTransferResponse {
    return {
      $type: BeginTransferResponse.$type,
      transfer: isSet(object.transfer) ? Transfer.fromJSON(object.transfer) : undefined,
      existing: isSet(object.existing) ? globalThis.Boolean(object.existing) : false,
      upload: isSet(object.upload) ? TransferCapability.fromJSON(object.upload) : undefined,
    };
  },

  toJSON(message: BeginTransferResponse): unknown {
    const obj: any = {};
    if (message.transfer !== undefined) {
      obj.transfer = Transfer.toJSON(message.transfer);
    }
    if (message.existing !== false) {
      obj.existing = message.existing;
    }
    if (message.upload !== undefined) {
      obj.upload = TransferCapability.toJSON(message.upload);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<BeginTransferResponse>, I>>(base?: I): BeginTransferResponse {
    return BeginTransferResponse.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<BeginTransferResponse>, I>>(object: I): BeginTransferResponse {
    const message = createBaseBeginTransferResponse();
    message.transfer = (object.transfer !== undefined && object.transfer !== null)
      ? Transfer.fromPartial(object.transfer)
      : undefined;
    message.existing = object.existing ?? false;
    message.upload = (object.upload !== undefined && object.upload !== null)
      ? TransferCapability.fromPartial(object.upload)
      : undefined;
    return message;
  },
};

messageTypeRegistry.set(BeginTransferResponse.$type, BeginTransferResponse);

function createBaseResolveHandleRequest(): ResolveHandleRequest {
  return { $type: "anvilkit.control.v1.ResolveHandleRequest", handle: "", instanceId: "" };
}

export const ResolveHandleRequest: MessageFns<ResolveHandleRequest, "anvilkit.control.v1.ResolveHandleRequest"> = {
  $type: "anvilkit.control.v1.ResolveHandleRequest" as const,

  encode(message: ResolveHandleRequest, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.handle !== "") {
      writer.uint32(10).string(message.handle);
    }
    if (message.instanceId !== "") {
      writer.uint32(18).string(message.instanceId);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): ResolveHandleRequest {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const previousRecursionDepth = (reader as any).__tsProtoDecodeDepth ?? 0;
    if (previousRecursionDepth >= 100) {
      throw new globalThis.Error("protobuf decode recursion limit exceeded");
    }
    (reader as any).__tsProtoDecodeDepth = previousRecursionDepth + 1;
    try {
      const end = length === undefined ? reader.len : reader.pos + length;
      const message = createBaseResolveHandleRequest();
      while (reader.pos < end) {
        const tag = reader.uint32();
        switch (tag >>> 3) {
          case 1: {
            if (tag !== 10) {
              break;
            }

            message.handle = reader.string();
            continue;
          }
          case 2: {
            if (tag !== 18) {
              break;
            }

            message.instanceId = reader.string();
            continue;
          }
        }
        if ((tag & 7) === 4 || tag === 0) {
          break;
        }
        reader.skip(tag & 7);
      }
      return message;
    } finally {
      (reader as any).__tsProtoDecodeDepth = previousRecursionDepth;
    }
  },

  fromJSON(object: any): ResolveHandleRequest {
    return {
      $type: ResolveHandleRequest.$type,
      handle: isSet(object.handle) ? globalThis.String(object.handle) : "",
      instanceId: isSet(object.instanceId)
        ? globalThis.String(object.instanceId)
        : isSet(object.instance_id)
        ? globalThis.String(object.instance_id)
        : "",
    };
  },

  toJSON(message: ResolveHandleRequest): unknown {
    const obj: any = {};
    if (message.handle !== "") {
      obj.handle = message.handle;
    }
    if (message.instanceId !== "") {
      obj.instanceId = message.instanceId;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<ResolveHandleRequest>, I>>(base?: I): ResolveHandleRequest {
    return ResolveHandleRequest.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<ResolveHandleRequest>, I>>(object: I): ResolveHandleRequest {
    const message = createBaseResolveHandleRequest();
    message.handle = object.handle ?? "";
    message.instanceId = object.instanceId ?? "";
    return message;
  },
};

messageTypeRegistry.set(ResolveHandleRequest.$type, ResolveHandleRequest);

function createBaseResolveHandleResponse(): ResolveHandleResponse {
  return {
    $type: "anvilkit.control.v1.ResolveHandleResponse",
    transfer: undefined,
    capability: "",
    expiresAt: undefined,
    upload: undefined,
  };
}

export const ResolveHandleResponse: MessageFns<ResolveHandleResponse, "anvilkit.control.v1.ResolveHandleResponse"> = {
  $type: "anvilkit.control.v1.ResolveHandleResponse" as const,

  encode(message: ResolveHandleResponse, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.transfer !== undefined) {
      Transfer.encode(message.transfer, writer.uint32(10).fork()).join();
    }
    if (message.capability !== "") {
      writer.uint32(18).string(message.capability);
    }
    if (message.expiresAt !== undefined) {
      Timestamp.encode(toTimestamp(message.expiresAt), writer.uint32(26).fork()).join();
    }
    if (message.upload !== undefined) {
      TransferCapability.encode(message.upload, writer.uint32(34).fork()).join();
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): ResolveHandleResponse {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const previousRecursionDepth = (reader as any).__tsProtoDecodeDepth ?? 0;
    if (previousRecursionDepth >= 100) {
      throw new globalThis.Error("protobuf decode recursion limit exceeded");
    }
    (reader as any).__tsProtoDecodeDepth = previousRecursionDepth + 1;
    try {
      const end = length === undefined ? reader.len : reader.pos + length;
      const message = createBaseResolveHandleResponse();
      while (reader.pos < end) {
        const tag = reader.uint32();
        switch (tag >>> 3) {
          case 1: {
            if (tag !== 10) {
              break;
            }

            message.transfer = Transfer.decode(reader, reader.uint32());
            continue;
          }
          case 2: {
            if (tag !== 18) {
              break;
            }

            message.capability = reader.string();
            continue;
          }
          case 3: {
            if (tag !== 26) {
              break;
            }

            message.expiresAt = fromTimestamp(Timestamp.decode(reader, reader.uint32()));
            continue;
          }
          case 4: {
            if (tag !== 34) {
              break;
            }

            message.upload = TransferCapability.decode(reader, reader.uint32());
            continue;
          }
        }
        if ((tag & 7) === 4 || tag === 0) {
          break;
        }
        reader.skip(tag & 7);
      }
      return message;
    } finally {
      (reader as any).__tsProtoDecodeDepth = previousRecursionDepth;
    }
  },

  fromJSON(object: any): ResolveHandleResponse {
    return {
      $type: ResolveHandleResponse.$type,
      transfer: isSet(object.transfer) ? Transfer.fromJSON(object.transfer) : undefined,
      capability: isSet(object.capability) ? globalThis.String(object.capability) : "",
      expiresAt: isSet(object.expiresAt)
        ? fromJsonTimestamp(object.expiresAt)
        : isSet(object.expires_at)
        ? fromJsonTimestamp(object.expires_at)
        : undefined,
      upload: isSet(object.upload) ? TransferCapability.fromJSON(object.upload) : undefined,
    };
  },

  toJSON(message: ResolveHandleResponse): unknown {
    const obj: any = {};
    if (message.transfer !== undefined) {
      obj.transfer = Transfer.toJSON(message.transfer);
    }
    if (message.capability !== "") {
      obj.capability = message.capability;
    }
    if (message.expiresAt !== undefined) {
      obj.expiresAt = message.expiresAt.toISOString();
    }
    if (message.upload !== undefined) {
      obj.upload = TransferCapability.toJSON(message.upload);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<ResolveHandleResponse>, I>>(base?: I): ResolveHandleResponse {
    return ResolveHandleResponse.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<ResolveHandleResponse>, I>>(object: I): ResolveHandleResponse {
    const message = createBaseResolveHandleResponse();
    message.transfer = (object.transfer !== undefined && object.transfer !== null)
      ? Transfer.fromPartial(object.transfer)
      : undefined;
    message.capability = object.capability ?? "";
    message.expiresAt = object.expiresAt ?? undefined;
    message.upload = (object.upload !== undefined && object.upload !== null)
      ? TransferCapability.fromPartial(object.upload)
      : undefined;
    return message;
  },
};

messageTypeRegistry.set(ResolveHandleResponse.$type, ResolveHandleResponse);

function createBaseFinalizeTransferRequest(): FinalizeTransferRequest {
  return {
    $type: "anvilkit.control.v1.FinalizeTransferRequest",
    command: undefined,
    transferId: "",
    objectVersion: "",
    instanceId: "",
    handle: "",
  };
}

export const FinalizeTransferRequest: MessageFns<
  FinalizeTransferRequest,
  "anvilkit.control.v1.FinalizeTransferRequest"
> = {
  $type: "anvilkit.control.v1.FinalizeTransferRequest" as const,

  encode(message: FinalizeTransferRequest, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.command !== undefined) {
      CommandIdentity.encode(message.command, writer.uint32(10).fork()).join();
    }
    if (message.transferId !== "") {
      writer.uint32(18).string(message.transferId);
    }
    if (message.objectVersion !== "") {
      writer.uint32(26).string(message.objectVersion);
    }
    if (message.instanceId !== "") {
      writer.uint32(34).string(message.instanceId);
    }
    if (message.handle !== "") {
      writer.uint32(42).string(message.handle);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): FinalizeTransferRequest {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const previousRecursionDepth = (reader as any).__tsProtoDecodeDepth ?? 0;
    if (previousRecursionDepth >= 100) {
      throw new globalThis.Error("protobuf decode recursion limit exceeded");
    }
    (reader as any).__tsProtoDecodeDepth = previousRecursionDepth + 1;
    try {
      const end = length === undefined ? reader.len : reader.pos + length;
      const message = createBaseFinalizeTransferRequest();
      while (reader.pos < end) {
        const tag = reader.uint32();
        switch (tag >>> 3) {
          case 1: {
            if (tag !== 10) {
              break;
            }

            message.command = CommandIdentity.decode(reader, reader.uint32());
            continue;
          }
          case 2: {
            if (tag !== 18) {
              break;
            }

            message.transferId = reader.string();
            continue;
          }
          case 3: {
            if (tag !== 26) {
              break;
            }

            message.objectVersion = reader.string();
            continue;
          }
          case 4: {
            if (tag !== 34) {
              break;
            }

            message.instanceId = reader.string();
            continue;
          }
          case 5: {
            if (tag !== 42) {
              break;
            }

            message.handle = reader.string();
            continue;
          }
        }
        if ((tag & 7) === 4 || tag === 0) {
          break;
        }
        reader.skip(tag & 7);
      }
      return message;
    } finally {
      (reader as any).__tsProtoDecodeDepth = previousRecursionDepth;
    }
  },

  fromJSON(object: any): FinalizeTransferRequest {
    return {
      $type: FinalizeTransferRequest.$type,
      command: isSet(object.command) ? CommandIdentity.fromJSON(object.command) : undefined,
      transferId: isSet(object.transferId)
        ? globalThis.String(object.transferId)
        : isSet(object.transfer_id)
        ? globalThis.String(object.transfer_id)
        : "",
      objectVersion: isSet(object.objectVersion)
        ? globalThis.String(object.objectVersion)
        : isSet(object.object_version)
        ? globalThis.String(object.object_version)
        : "",
      instanceId: isSet(object.instanceId)
        ? globalThis.String(object.instanceId)
        : isSet(object.instance_id)
        ? globalThis.String(object.instance_id)
        : "",
      handle: isSet(object.handle) ? globalThis.String(object.handle) : "",
    };
  },

  toJSON(message: FinalizeTransferRequest): unknown {
    const obj: any = {};
    if (message.command !== undefined) {
      obj.command = CommandIdentity.toJSON(message.command);
    }
    if (message.transferId !== "") {
      obj.transferId = message.transferId;
    }
    if (message.objectVersion !== "") {
      obj.objectVersion = message.objectVersion;
    }
    if (message.instanceId !== "") {
      obj.instanceId = message.instanceId;
    }
    if (message.handle !== "") {
      obj.handle = message.handle;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<FinalizeTransferRequest>, I>>(base?: I): FinalizeTransferRequest {
    return FinalizeTransferRequest.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<FinalizeTransferRequest>, I>>(object: I): FinalizeTransferRequest {
    const message = createBaseFinalizeTransferRequest();
    message.command = (object.command !== undefined && object.command !== null)
      ? CommandIdentity.fromPartial(object.command)
      : undefined;
    message.transferId = object.transferId ?? "";
    message.objectVersion = object.objectVersion ?? "";
    message.instanceId = object.instanceId ?? "";
    message.handle = object.handle ?? "";
    return message;
  },
};

messageTypeRegistry.set(FinalizeTransferRequest.$type, FinalizeTransferRequest);

function createBaseFinalizeTransferResponse(): FinalizeTransferResponse {
  return { $type: "anvilkit.control.v1.FinalizeTransferResponse", transfer: undefined, existing: false };
}

export const FinalizeTransferResponse: MessageFns<
  FinalizeTransferResponse,
  "anvilkit.control.v1.FinalizeTransferResponse"
> = {
  $type: "anvilkit.control.v1.FinalizeTransferResponse" as const,

  encode(message: FinalizeTransferResponse, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.transfer !== undefined) {
      Transfer.encode(message.transfer, writer.uint32(10).fork()).join();
    }
    if (message.existing !== false) {
      writer.uint32(16).bool(message.existing);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): FinalizeTransferResponse {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const previousRecursionDepth = (reader as any).__tsProtoDecodeDepth ?? 0;
    if (previousRecursionDepth >= 100) {
      throw new globalThis.Error("protobuf decode recursion limit exceeded");
    }
    (reader as any).__tsProtoDecodeDepth = previousRecursionDepth + 1;
    try {
      const end = length === undefined ? reader.len : reader.pos + length;
      const message = createBaseFinalizeTransferResponse();
      while (reader.pos < end) {
        const tag = reader.uint32();
        switch (tag >>> 3) {
          case 1: {
            if (tag !== 10) {
              break;
            }

            message.transfer = Transfer.decode(reader, reader.uint32());
            continue;
          }
          case 2: {
            if (tag !== 16) {
              break;
            }

            message.existing = reader.bool();
            continue;
          }
        }
        if ((tag & 7) === 4 || tag === 0) {
          break;
        }
        reader.skip(tag & 7);
      }
      return message;
    } finally {
      (reader as any).__tsProtoDecodeDepth = previousRecursionDepth;
    }
  },

  fromJSON(object: any): FinalizeTransferResponse {
    return {
      $type: FinalizeTransferResponse.$type,
      transfer: isSet(object.transfer) ? Transfer.fromJSON(object.transfer) : undefined,
      existing: isSet(object.existing) ? globalThis.Boolean(object.existing) : false,
    };
  },

  toJSON(message: FinalizeTransferResponse): unknown {
    const obj: any = {};
    if (message.transfer !== undefined) {
      obj.transfer = Transfer.toJSON(message.transfer);
    }
    if (message.existing !== false) {
      obj.existing = message.existing;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<FinalizeTransferResponse>, I>>(base?: I): FinalizeTransferResponse {
    return FinalizeTransferResponse.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<FinalizeTransferResponse>, I>>(object: I): FinalizeTransferResponse {
    const message = createBaseFinalizeTransferResponse();
    message.transfer = (object.transfer !== undefined && object.transfer !== null)
      ? Transfer.fromPartial(object.transfer)
      : undefined;
    message.existing = object.existing ?? false;
    return message;
  },
};

messageTypeRegistry.set(FinalizeTransferResponse.$type, FinalizeTransferResponse);

function createBaseGetTransferRequest(): GetTransferRequest {
  return { $type: "anvilkit.control.v1.GetTransferRequest", transferId: "", scope: undefined, handle: "" };
}

export const GetTransferRequest: MessageFns<GetTransferRequest, "anvilkit.control.v1.GetTransferRequest"> = {
  $type: "anvilkit.control.v1.GetTransferRequest" as const,

  encode(message: GetTransferRequest, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.transferId !== "") {
      writer.uint32(10).string(message.transferId);
    }
    if (message.scope !== undefined) {
      Scope.encode(message.scope, writer.uint32(18).fork()).join();
    }
    if (message.handle !== "") {
      writer.uint32(26).string(message.handle);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): GetTransferRequest {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const previousRecursionDepth = (reader as any).__tsProtoDecodeDepth ?? 0;
    if (previousRecursionDepth >= 100) {
      throw new globalThis.Error("protobuf decode recursion limit exceeded");
    }
    (reader as any).__tsProtoDecodeDepth = previousRecursionDepth + 1;
    try {
      const end = length === undefined ? reader.len : reader.pos + length;
      const message = createBaseGetTransferRequest();
      while (reader.pos < end) {
        const tag = reader.uint32();
        switch (tag >>> 3) {
          case 1: {
            if (tag !== 10) {
              break;
            }

            message.transferId = reader.string();
            continue;
          }
          case 2: {
            if (tag !== 18) {
              break;
            }

            message.scope = Scope.decode(reader, reader.uint32());
            continue;
          }
          case 3: {
            if (tag !== 26) {
              break;
            }

            message.handle = reader.string();
            continue;
          }
        }
        if ((tag & 7) === 4 || tag === 0) {
          break;
        }
        reader.skip(tag & 7);
      }
      return message;
    } finally {
      (reader as any).__tsProtoDecodeDepth = previousRecursionDepth;
    }
  },

  fromJSON(object: any): GetTransferRequest {
    return {
      $type: GetTransferRequest.$type,
      transferId: isSet(object.transferId)
        ? globalThis.String(object.transferId)
        : isSet(object.transfer_id)
        ? globalThis.String(object.transfer_id)
        : "",
      scope: isSet(object.scope) ? Scope.fromJSON(object.scope) : undefined,
      handle: isSet(object.handle) ? globalThis.String(object.handle) : "",
    };
  },

  toJSON(message: GetTransferRequest): unknown {
    const obj: any = {};
    if (message.transferId !== "") {
      obj.transferId = message.transferId;
    }
    if (message.scope !== undefined) {
      obj.scope = Scope.toJSON(message.scope);
    }
    if (message.handle !== "") {
      obj.handle = message.handle;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<GetTransferRequest>, I>>(base?: I): GetTransferRequest {
    return GetTransferRequest.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<GetTransferRequest>, I>>(object: I): GetTransferRequest {
    const message = createBaseGetTransferRequest();
    message.transferId = object.transferId ?? "";
    message.scope = (object.scope !== undefined && object.scope !== null) ? Scope.fromPartial(object.scope) : undefined;
    message.handle = object.handle ?? "";
    return message;
  },
};

messageTypeRegistry.set(GetTransferRequest.$type, GetTransferRequest);

function createBaseGetTransferResponse(): GetTransferResponse {
  return { $type: "anvilkit.control.v1.GetTransferResponse", transfer: undefined };
}

export const GetTransferResponse: MessageFns<GetTransferResponse, "anvilkit.control.v1.GetTransferResponse"> = {
  $type: "anvilkit.control.v1.GetTransferResponse" as const,

  encode(message: GetTransferResponse, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.transfer !== undefined) {
      Transfer.encode(message.transfer, writer.uint32(10).fork()).join();
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): GetTransferResponse {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const previousRecursionDepth = (reader as any).__tsProtoDecodeDepth ?? 0;
    if (previousRecursionDepth >= 100) {
      throw new globalThis.Error("protobuf decode recursion limit exceeded");
    }
    (reader as any).__tsProtoDecodeDepth = previousRecursionDepth + 1;
    try {
      const end = length === undefined ? reader.len : reader.pos + length;
      const message = createBaseGetTransferResponse();
      while (reader.pos < end) {
        const tag = reader.uint32();
        switch (tag >>> 3) {
          case 1: {
            if (tag !== 10) {
              break;
            }

            message.transfer = Transfer.decode(reader, reader.uint32());
            continue;
          }
        }
        if ((tag & 7) === 4 || tag === 0) {
          break;
        }
        reader.skip(tag & 7);
      }
      return message;
    } finally {
      (reader as any).__tsProtoDecodeDepth = previousRecursionDepth;
    }
  },

  fromJSON(object: any): GetTransferResponse {
    return {
      $type: GetTransferResponse.$type,
      transfer: isSet(object.transfer) ? Transfer.fromJSON(object.transfer) : undefined,
    };
  },

  toJSON(message: GetTransferResponse): unknown {
    const obj: any = {};
    if (message.transfer !== undefined) {
      obj.transfer = Transfer.toJSON(message.transfer);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<GetTransferResponse>, I>>(base?: I): GetTransferResponse {
    return GetTransferResponse.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<GetTransferResponse>, I>>(object: I): GetTransferResponse {
    const message = createBaseGetTransferResponse();
    message.transfer = (object.transfer !== undefined && object.transfer !== null)
      ? Transfer.fromPartial(object.transfer)
      : undefined;
    return message;
  },
};

messageTypeRegistry.set(GetTransferResponse.$type, GetTransferResponse);

function createBaseReadArtifactRequest(): ReadArtifactRequest {
  return {
    $type: "anvilkit.control.v1.ReadArtifactRequest",
    handle: "",
    transferId: "",
    operationId: "",
    instanceId: "",
  };
}

export const ReadArtifactRequest: MessageFns<ReadArtifactRequest, "anvilkit.control.v1.ReadArtifactRequest"> = {
  $type: "anvilkit.control.v1.ReadArtifactRequest" as const,

  encode(message: ReadArtifactRequest, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.handle !== "") {
      writer.uint32(10).string(message.handle);
    }
    if (message.transferId !== "") {
      writer.uint32(18).string(message.transferId);
    }
    if (message.operationId !== "") {
      writer.uint32(26).string(message.operationId);
    }
    if (message.instanceId !== "") {
      writer.uint32(34).string(message.instanceId);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): ReadArtifactRequest {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const previousRecursionDepth = (reader as any).__tsProtoDecodeDepth ?? 0;
    if (previousRecursionDepth >= 100) {
      throw new globalThis.Error("protobuf decode recursion limit exceeded");
    }
    (reader as any).__tsProtoDecodeDepth = previousRecursionDepth + 1;
    try {
      const end = length === undefined ? reader.len : reader.pos + length;
      const message = createBaseReadArtifactRequest();
      while (reader.pos < end) {
        const tag = reader.uint32();
        switch (tag >>> 3) {
          case 1: {
            if (tag !== 10) {
              break;
            }

            message.handle = reader.string();
            continue;
          }
          case 2: {
            if (tag !== 18) {
              break;
            }

            message.transferId = reader.string();
            continue;
          }
          case 3: {
            if (tag !== 26) {
              break;
            }

            message.operationId = reader.string();
            continue;
          }
          case 4: {
            if (tag !== 34) {
              break;
            }

            message.instanceId = reader.string();
            continue;
          }
        }
        if ((tag & 7) === 4 || tag === 0) {
          break;
        }
        reader.skip(tag & 7);
      }
      return message;
    } finally {
      (reader as any).__tsProtoDecodeDepth = previousRecursionDepth;
    }
  },

  fromJSON(object: any): ReadArtifactRequest {
    return {
      $type: ReadArtifactRequest.$type,
      handle: isSet(object.handle) ? globalThis.String(object.handle) : "",
      transferId: isSet(object.transferId)
        ? globalThis.String(object.transferId)
        : isSet(object.transfer_id)
        ? globalThis.String(object.transfer_id)
        : "",
      operationId: isSet(object.operationId)
        ? globalThis.String(object.operationId)
        : isSet(object.operation_id)
        ? globalThis.String(object.operation_id)
        : "",
      instanceId: isSet(object.instanceId)
        ? globalThis.String(object.instanceId)
        : isSet(object.instance_id)
        ? globalThis.String(object.instance_id)
        : "",
    };
  },

  toJSON(message: ReadArtifactRequest): unknown {
    const obj: any = {};
    if (message.handle !== "") {
      obj.handle = message.handle;
    }
    if (message.transferId !== "") {
      obj.transferId = message.transferId;
    }
    if (message.operationId !== "") {
      obj.operationId = message.operationId;
    }
    if (message.instanceId !== "") {
      obj.instanceId = message.instanceId;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<ReadArtifactRequest>, I>>(base?: I): ReadArtifactRequest {
    return ReadArtifactRequest.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<ReadArtifactRequest>, I>>(object: I): ReadArtifactRequest {
    const message = createBaseReadArtifactRequest();
    message.handle = object.handle ?? "";
    message.transferId = object.transferId ?? "";
    message.operationId = object.operationId ?? "";
    message.instanceId = object.instanceId ?? "";
    return message;
  },
};

messageTypeRegistry.set(ReadArtifactRequest.$type, ReadArtifactRequest);

function createBaseReadArtifactResponse(): ReadArtifactResponse {
  return { $type: "anvilkit.control.v1.ReadArtifactResponse", transfer: undefined, download: undefined };
}

export const ReadArtifactResponse: MessageFns<ReadArtifactResponse, "anvilkit.control.v1.ReadArtifactResponse"> = {
  $type: "anvilkit.control.v1.ReadArtifactResponse" as const,

  encode(message: ReadArtifactResponse, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.transfer !== undefined) {
      Transfer.encode(message.transfer, writer.uint32(10).fork()).join();
    }
    if (message.download !== undefined) {
      TransferCapability.encode(message.download, writer.uint32(18).fork()).join();
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): ReadArtifactResponse {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const previousRecursionDepth = (reader as any).__tsProtoDecodeDepth ?? 0;
    if (previousRecursionDepth >= 100) {
      throw new globalThis.Error("protobuf decode recursion limit exceeded");
    }
    (reader as any).__tsProtoDecodeDepth = previousRecursionDepth + 1;
    try {
      const end = length === undefined ? reader.len : reader.pos + length;
      const message = createBaseReadArtifactResponse();
      while (reader.pos < end) {
        const tag = reader.uint32();
        switch (tag >>> 3) {
          case 1: {
            if (tag !== 10) {
              break;
            }

            message.transfer = Transfer.decode(reader, reader.uint32());
            continue;
          }
          case 2: {
            if (tag !== 18) {
              break;
            }

            message.download = TransferCapability.decode(reader, reader.uint32());
            continue;
          }
        }
        if ((tag & 7) === 4 || tag === 0) {
          break;
        }
        reader.skip(tag & 7);
      }
      return message;
    } finally {
      (reader as any).__tsProtoDecodeDepth = previousRecursionDepth;
    }
  },

  fromJSON(object: any): ReadArtifactResponse {
    return {
      $type: ReadArtifactResponse.$type,
      transfer: isSet(object.transfer) ? Transfer.fromJSON(object.transfer) : undefined,
      download: isSet(object.download) ? TransferCapability.fromJSON(object.download) : undefined,
    };
  },

  toJSON(message: ReadArtifactResponse): unknown {
    const obj: any = {};
    if (message.transfer !== undefined) {
      obj.transfer = Transfer.toJSON(message.transfer);
    }
    if (message.download !== undefined) {
      obj.download = TransferCapability.toJSON(message.download);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<ReadArtifactResponse>, I>>(base?: I): ReadArtifactResponse {
    return ReadArtifactResponse.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<ReadArtifactResponse>, I>>(object: I): ReadArtifactResponse {
    const message = createBaseReadArtifactResponse();
    message.transfer = (object.transfer !== undefined && object.transfer !== null)
      ? Transfer.fromPartial(object.transfer)
      : undefined;
    message.download = (object.download !== undefined && object.download !== null)
      ? TransferCapability.fromPartial(object.download)
      : undefined;
    return message;
  },
};

messageTypeRegistry.set(ReadArtifactResponse.$type, ReadArtifactResponse);

export type ArtifactServiceService = typeof ArtifactServiceService;
export const ArtifactServiceService = {
  beginTransfer: {
    path: "/anvilkit.control.v1.ArtifactService/BeginTransfer" as const,
    requestStream: false as const,
    responseStream: false as const,
    requestSerialize: (value: BeginTransferRequest): Buffer => Buffer.from(BeginTransferRequest.encode(value).finish()),
    requestDeserialize: (value: Buffer): BeginTransferRequest => BeginTransferRequest.decode(value),
    responseSerialize: (value: BeginTransferResponse): Buffer =>
      Buffer.from(BeginTransferResponse.encode(value).finish()),
    responseDeserialize: (value: Buffer): BeginTransferResponse => BeginTransferResponse.decode(value),
  },
  /** Resolves an opaque handle to a scoped capability for a trusted caller only. */
  resolveHandle: {
    path: "/anvilkit.control.v1.ArtifactService/ResolveHandle" as const,
    requestStream: false as const,
    responseStream: false as const,
    requestSerialize: (value: ResolveHandleRequest): Buffer => Buffer.from(ResolveHandleRequest.encode(value).finish()),
    requestDeserialize: (value: Buffer): ResolveHandleRequest => ResolveHandleRequest.decode(value),
    responseSerialize: (value: ResolveHandleResponse): Buffer =>
      Buffer.from(ResolveHandleResponse.encode(value).finish()),
    responseDeserialize: (value: Buffer): ResolveHandleResponse => ResolveHandleResponse.decode(value),
  },
  finalizeTransfer: {
    path: "/anvilkit.control.v1.ArtifactService/FinalizeTransfer" as const,
    requestStream: false as const,
    responseStream: false as const,
    requestSerialize: (value: FinalizeTransferRequest): Buffer =>
      Buffer.from(FinalizeTransferRequest.encode(value).finish()),
    requestDeserialize: (value: Buffer): FinalizeTransferRequest => FinalizeTransferRequest.decode(value),
    responseSerialize: (value: FinalizeTransferResponse): Buffer =>
      Buffer.from(FinalizeTransferResponse.encode(value).finish()),
    responseDeserialize: (value: Buffer): FinalizeTransferResponse => FinalizeTransferResponse.decode(value),
  },
  getTransfer: {
    path: "/anvilkit.control.v1.ArtifactService/GetTransfer" as const,
    requestStream: false as const,
    responseStream: false as const,
    requestSerialize: (value: GetTransferRequest): Buffer => Buffer.from(GetTransferRequest.encode(value).finish()),
    requestDeserialize: (value: Buffer): GetTransferRequest => GetTransferRequest.decode(value),
    responseSerialize: (value: GetTransferResponse): Buffer => Buffer.from(GetTransferResponse.encode(value).finish()),
    responseDeserialize: (value: Buffer): GetTransferResponse => GetTransferResponse.decode(value),
  },
  /**
   * Issues a trusted reader the scoped download capability of a finalized
   * artifact under an authorized relationship to the reading operation
   * (P13): the artifact is the operation's own prompt, an accepted answer,
   * the brief its subject binds, or an artifact bound by an accepted stage
   * of one of its attempts. A reading physical instance must be the
   * current one of an executing attempt of that operation. The capability
   * names the exact object version; the reader verifies the bytes against
   * the digest and size answered here. Candidates never see it.
   */
  readArtifact: {
    path: "/anvilkit.control.v1.ArtifactService/ReadArtifact" as const,
    requestStream: false as const,
    responseStream: false as const,
    requestSerialize: (value: ReadArtifactRequest): Buffer => Buffer.from(ReadArtifactRequest.encode(value).finish()),
    requestDeserialize: (value: Buffer): ReadArtifactRequest => ReadArtifactRequest.decode(value),
    responseSerialize: (value: ReadArtifactResponse): Buffer =>
      Buffer.from(ReadArtifactResponse.encode(value).finish()),
    responseDeserialize: (value: Buffer): ReadArtifactResponse => ReadArtifactResponse.decode(value),
  },
} as const;

export interface ArtifactServiceServer extends UntypedServiceImplementation {
  beginTransfer: handleUnaryCall<BeginTransferRequest, BeginTransferResponse>;
  /** Resolves an opaque handle to a scoped capability for a trusted caller only. */
  resolveHandle: handleUnaryCall<ResolveHandleRequest, ResolveHandleResponse>;
  finalizeTransfer: handleUnaryCall<FinalizeTransferRequest, FinalizeTransferResponse>;
  getTransfer: handleUnaryCall<GetTransferRequest, GetTransferResponse>;
  /**
   * Issues a trusted reader the scoped download capability of a finalized
   * artifact under an authorized relationship to the reading operation
   * (P13): the artifact is the operation's own prompt, an accepted answer,
   * the brief its subject binds, or an artifact bound by an accepted stage
   * of one of its attempts. A reading physical instance must be the
   * current one of an executing attempt of that operation. The capability
   * names the exact object version; the reader verifies the bytes against
   * the digest and size answered here. Candidates never see it.
   */
  readArtifact: handleUnaryCall<ReadArtifactRequest, ReadArtifactResponse>;
}

export interface ArtifactServiceClient extends Client {
  beginTransfer(
    request: BeginTransferRequest,
    callback: (error: ServiceError | null, response: BeginTransferResponse) => void,
  ): ClientUnaryCall;
  beginTransfer(
    request: BeginTransferRequest,
    metadata: Metadata,
    callback: (error: ServiceError | null, response: BeginTransferResponse) => void,
  ): ClientUnaryCall;
  beginTransfer(
    request: BeginTransferRequest,
    metadata: Metadata,
    options: Partial<CallOptions>,
    callback: (error: ServiceError | null, response: BeginTransferResponse) => void,
  ): ClientUnaryCall;
  /** Resolves an opaque handle to a scoped capability for a trusted caller only. */
  resolveHandle(
    request: ResolveHandleRequest,
    callback: (error: ServiceError | null, response: ResolveHandleResponse) => void,
  ): ClientUnaryCall;
  resolveHandle(
    request: ResolveHandleRequest,
    metadata: Metadata,
    callback: (error: ServiceError | null, response: ResolveHandleResponse) => void,
  ): ClientUnaryCall;
  resolveHandle(
    request: ResolveHandleRequest,
    metadata: Metadata,
    options: Partial<CallOptions>,
    callback: (error: ServiceError | null, response: ResolveHandleResponse) => void,
  ): ClientUnaryCall;
  finalizeTransfer(
    request: FinalizeTransferRequest,
    callback: (error: ServiceError | null, response: FinalizeTransferResponse) => void,
  ): ClientUnaryCall;
  finalizeTransfer(
    request: FinalizeTransferRequest,
    metadata: Metadata,
    callback: (error: ServiceError | null, response: FinalizeTransferResponse) => void,
  ): ClientUnaryCall;
  finalizeTransfer(
    request: FinalizeTransferRequest,
    metadata: Metadata,
    options: Partial<CallOptions>,
    callback: (error: ServiceError | null, response: FinalizeTransferResponse) => void,
  ): ClientUnaryCall;
  getTransfer(
    request: GetTransferRequest,
    callback: (error: ServiceError | null, response: GetTransferResponse) => void,
  ): ClientUnaryCall;
  getTransfer(
    request: GetTransferRequest,
    metadata: Metadata,
    callback: (error: ServiceError | null, response: GetTransferResponse) => void,
  ): ClientUnaryCall;
  getTransfer(
    request: GetTransferRequest,
    metadata: Metadata,
    options: Partial<CallOptions>,
    callback: (error: ServiceError | null, response: GetTransferResponse) => void,
  ): ClientUnaryCall;
  /**
   * Issues a trusted reader the scoped download capability of a finalized
   * artifact under an authorized relationship to the reading operation
   * (P13): the artifact is the operation's own prompt, an accepted answer,
   * the brief its subject binds, or an artifact bound by an accepted stage
   * of one of its attempts. A reading physical instance must be the
   * current one of an executing attempt of that operation. The capability
   * names the exact object version; the reader verifies the bytes against
   * the digest and size answered here. Candidates never see it.
   */
  readArtifact(
    request: ReadArtifactRequest,
    callback: (error: ServiceError | null, response: ReadArtifactResponse) => void,
  ): ClientUnaryCall;
  readArtifact(
    request: ReadArtifactRequest,
    metadata: Metadata,
    callback: (error: ServiceError | null, response: ReadArtifactResponse) => void,
  ): ClientUnaryCall;
  readArtifact(
    request: ReadArtifactRequest,
    metadata: Metadata,
    options: Partial<CallOptions>,
    callback: (error: ServiceError | null, response: ReadArtifactResponse) => void,
  ): ClientUnaryCall;
}

export const ArtifactServiceClient = makeGenericClientConstructor(
  ArtifactServiceService,
  "anvilkit.control.v1.ArtifactService",
) as unknown as {
  new (address: string, credentials: ChannelCredentials, options?: Partial<ClientOptions>): ArtifactServiceClient;
  service: typeof ArtifactServiceService;
  serviceName: string;
};

type Builtin = Date | Function | Uint8Array | string | number | boolean | undefined;

export type DeepPartial<T> = T extends Builtin ? T
  : T extends globalThis.Array<infer U> ? globalThis.Array<DeepPartial<U>>
  : T extends ReadonlyArray<infer U> ? ReadonlyArray<DeepPartial<U>>
  : T extends {} ? { [K in Exclude<keyof T, "$type">]?: DeepPartial<T[K]> }
  : Partial<T>;

type KeysOfUnion<T> = T extends T ? keyof T : never;
export type Exact<P, I extends P> = P extends Builtin ? P
  : P & { [K in keyof P]: Exact<P[K], I[K]> } & { [K in Exclude<keyof I, KeysOfUnion<P> | "$type">]: never };

function toTimestamp(date: Date): Timestamp {
  const seconds = Math.trunc(date.getTime() / 1_000);
  const nanos = (date.getTime() % 1_000) * 1_000_000;
  return { $type: "google.protobuf.Timestamp", seconds, nanos };
}

function fromTimestamp(t: Timestamp): Date {
  let millis = (t.seconds || 0) * 1_000;
  millis += (t.nanos || 0) / 1_000_000;
  return new globalThis.Date(millis);
}

function fromJsonTimestamp(o: any): Date {
  if (o instanceof globalThis.Date) {
    return o;
  } else if (typeof o === "string") {
    return new globalThis.Date(o);
  } else {
    return fromTimestamp(Timestamp.fromJSON(o));
  }
}

function isObject(value: any): boolean {
  return typeof value === "object" && value !== null;
}

function isSet(value: any): boolean {
  return value !== null && value !== undefined;
}

export interface MessageFns<T, V extends string> {
  readonly $type: V;
  encode(message: T, writer?: BinaryWriter): BinaryWriter;
  decode(input: BinaryReader | Uint8Array, length?: number): T;
  fromJSON(object: any): T;
  toJSON(message: T): unknown;
  create<I extends Exact<DeepPartial<T>, I>>(base?: I): T;
  fromPartial<I extends Exact<DeepPartial<T>, I>>(object: I): T;
}
