// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.12.3
//   protoc               unknown
// source: anvilkit/control/v1/preview.proto

/* eslint-disable */
import { BinaryReader, BinaryWriter } from "@bufbuild/protobuf/wire";
import {
  type CallOptions,
  type ChannelCredentials,
  Client,
  type ClientOptions,
  type ClientUnaryCall,
  type handleUnaryCall,
  makeGenericClientConstructor,
  type Metadata,
  type ServiceError,
  type UntypedServiceImplementation,
} from "@grpc/grpc-js";
import { Timestamp } from "../../../google/protobuf/timestamp.js";
import { messageTypeRegistry } from "../../../typeRegistry.js";
import { ArtifactReference, CommandIdentity } from "./control.js";

export const protobufPackage = "anvilkit.control.v1";

/**
 * Preview builds (DD-04 §5, DD-05 §1/§4, delivery.md P20): a preview_build
 * operation first saves the edited source under the expected source
 * revision through the source authority (a conflict keeps the caller's
 * edits and names the current revision), then builds exactly the saved
 * revision in an isolated Job under the build and host profiles. Control
 * keeps the committed projection the Workflow records and the API reads;
 * it never decides the next step. A result superseded by a newer saved
 * revision is stale: it stays readable as a diagnostic but never replaces
 * the current preview.
 */

export enum PreviewState {
  PREVIEW_STATE_UNSPECIFIED = 0,
  /** PREVIEW_STATE_SAVING - The conditional source save is in progress. */
  PREVIEW_STATE_SAVING = 1,
  /** PREVIEW_STATE_CONFLICT - The source authority refused the save: current_revision is newer. */
  PREVIEW_STATE_CONFLICT = 2,
  /** PREVIEW_STATE_BUILDING - The saved revision is being built. */
  PREVIEW_STATE_BUILDING = 3,
  /** PREVIEW_STATE_READY - The build of source_revision is available. */
  PREVIEW_STATE_READY = 4,
  /** PREVIEW_STATE_STALE - The build finished after a newer revision was saved. */
  PREVIEW_STATE_STALE = 5,
  /** PREVIEW_STATE_FAILED - Save or build failed (failure_code). */
  PREVIEW_STATE_FAILED = 6,
  UNRECOGNIZED = -1,
}

export function previewStateFromJSON(object: any): PreviewState {
  switch (object) {
    case 0:
    case "PREVIEW_STATE_UNSPECIFIED":
      return PreviewState.PREVIEW_STATE_UNSPECIFIED;
    case 1:
    case "PREVIEW_STATE_SAVING":
      return PreviewState.PREVIEW_STATE_SAVING;
    case 2:
    case "PREVIEW_STATE_CONFLICT":
      return PreviewState.PREVIEW_STATE_CONFLICT;
    case 3:
    case "PREVIEW_STATE_BUILDING":
      return PreviewState.PREVIEW_STATE_BUILDING;
    case 4:
    case "PREVIEW_STATE_READY":
      return PreviewState.PREVIEW_STATE_READY;
    case 5:
    case "PREVIEW_STATE_STALE":
      return PreviewState.PREVIEW_STATE_STALE;
    case 6:
    case "PREVIEW_STATE_FAILED":
      return PreviewState.PREVIEW_STATE_FAILED;
    case -1:
    case "UNRECOGNIZED":
    default:
      return PreviewState.UNRECOGNIZED;
  }
}

export function previewStateToJSON(object: PreviewState): string {
  switch (object) {
    case PreviewState.PREVIEW_STATE_UNSPECIFIED:
      return "PREVIEW_STATE_UNSPECIFIED";
    case PreviewState.PREVIEW_STATE_SAVING:
      return "PREVIEW_STATE_SAVING";
    case PreviewState.PREVIEW_STATE_CONFLICT:
      return "PREVIEW_STATE_CONFLICT";
    case PreviewState.PREVIEW_STATE_BUILDING:
      return "PREVIEW_STATE_BUILDING";
    case PreviewState.PREVIEW_STATE_READY:
      return "PREVIEW_STATE_READY";
    case PreviewState.PREVIEW_STATE_STALE:
      return "PREVIEW_STATE_STALE";
    case PreviewState.PREVIEW_STATE_FAILED:
      return "PREVIEW_STATE_FAILED";
    case PreviewState.UNRECOGNIZED:
    default:
      return "UNRECOGNIZED";
  }
}

export interface Preview {
  $type: "anvilkit.control.v1.Preview";
  operationId: string;
  tenantId: string;
  /** The component source lineage (the operation's subject digest). */
  subjectDigest: string;
  /** The revision the edit was based on (the operation's source revision). */
  baseRevision: string;
  state: PreviewState;
  /** The revision the save created (ready, stale, building). */
  sourceRevision?:
    | string
    | undefined;
  /** The source authority's current revision on a conflict or when stale. */
  currentRevision?:
    | string
    | undefined;
  /** The exact saved source bytes. */
  sourceDigest: string;
  /** The built browser module and its stylesheets (ready, stale). */
  module?: ArtifactReference | undefined;
  styles: ArtifactReference[];
  buildProfileId: string;
  hostProfileId: string;
  failureCode?:
    | string
    | undefined;
  /** Monotonic per operation; every recorded transition increments it. */
  revision: string;
  updatedAt: Date | undefined;
}

export interface RecordPreviewRequest {
  $type: "anvilkit.control.v1.RecordPreviewRequest";
  operationId: string;
  /** "0" for the first record. */
  expectedRevision: string;
  state: PreviewState;
  sourceRevision?: string | undefined;
  currentRevision?: string | undefined;
  sourceDigest: string;
  module?: ArtifactReference | undefined;
  styles: ArtifactReference[];
  buildProfileId: string;
  hostProfileId: string;
  failureCode?:
    | string
    | undefined;
  /**
   * The recording command: its tenant must be the operation's (another
   * tenant's operation is not found); the recorder is the caller's
   * workload identity (P0.2).
   */
  command: CommandIdentity | undefined;
}

export interface RecordPreviewResponse {
  $type: "anvilkit.control.v1.RecordPreviewResponse";
  preview: Preview | undefined;
  existing: boolean;
}

export interface GetPreviewRequest {
  $type: "anvilkit.control.v1.GetPreviewRequest";
  tenantId: string;
  operationId: string;
}

export interface GetPreviewResponse {
  $type: "anvilkit.control.v1.GetPreviewResponse";
  preview: Preview | undefined;
}

export interface GetSourceRequest {
  $type: "anvilkit.control.v1.GetSourceRequest";
  tenantId: string;
  operationId: string;
}

export interface GetSourceResponse {
  $type: "anvilkit.control.v1.GetSourceResponse";
  /** The source archive (class source). */
  source:
    | ArtifactReference
    | undefined;
  /** The component source lineage (the operation's subject digest). */
  lineage: string;
  /**
   * The source revision these bytes are, when the source authority named
   * one (a registered candidate, a saved preview); absent otherwise.
   */
  revision?: string | undefined;
}

function createBasePreview(): Preview {
  return {
    $type: "anvilkit.control.v1.Preview",
    operationId: "",
    tenantId: "",
    subjectDigest: "",
    baseRevision: "",
    state: 0,
    sourceRevision: undefined,
    currentRevision: undefined,
    sourceDigest: "",
    module: undefined,
    styles: [],
    buildProfileId: "",
    hostProfileId: "",
    failureCode: undefined,
    revision: "",
    updatedAt: undefined,
  };
}

export const Preview: MessageFns<Preview, "anvilkit.control.v1.Preview"> = {
  $type: "anvilkit.control.v1.Preview" as const,

  encode(message: Preview, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.operationId !== "") {
      writer.uint32(10).string(message.operationId);
    }
    if (message.tenantId !== "") {
      writer.uint32(18).string(message.tenantId);
    }
    if (message.subjectDigest !== "") {
      writer.uint32(26).string(message.subjectDigest);
    }
    if (message.baseRevision !== "") {
      writer.uint32(34).string(message.baseRevision);
    }
    if (message.state !== 0) {
      writer.uint32(40).int32(message.state);
    }
    if (message.sourceRevision !== undefined) {
      writer.uint32(50).string(message.sourceRevision);
    }
    if (message.currentRevision !== undefined) {
      writer.uint32(58).string(message.currentRevision);
    }
    if (message.sourceDigest !== "") {
      writer.uint32(66).string(message.sourceDigest);
    }
    if (message.module !== undefined) {
      ArtifactReference.encode(message.module, writer.uint32(74).fork()).join();
    }
    for (const v of message.styles) {
      ArtifactReference.encode(v!, writer.uint32(82).fork()).join();
    }
    if (message.buildProfileId !== "") {
      writer.uint32(90).string(message.buildProfileId);
    }
    if (message.hostProfileId !== "") {
      writer.uint32(98).string(message.hostProfileId);
    }
    if (message.failureCode !== undefined) {
      writer.uint32(106).string(message.failureCode);
    }
    if (message.revision !== "") {
      writer.uint32(114).string(message.revision);
    }
    if (message.updatedAt !== undefined) {
      Timestamp.encode(toTimestamp(message.updatedAt), writer.uint32(122).fork()).join();
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): Preview {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const previousRecursionDepth = (reader as any).__tsProtoDecodeDepth ?? 0;
    if (previousRecursionDepth >= 100) {
      throw new globalThis.Error("protobuf decode recursion limit exceeded");
    }
    (reader as any).__tsProtoDecodeDepth = previousRecursionDepth + 1;
    try {
      const end = length === undefined ? reader.len : reader.pos + length;
      const message = createBasePreview();
      while (reader.pos < end) {
        const tag = reader.uint32();
        switch (tag >>> 3) {
          case 1: {
            if (tag !== 10) {
              break;
            }

            message.operationId = reader.string();
            continue;
          }
          case 2: {
            if (tag !== 18) {
              break;
            }

            message.tenantId = reader.string();
            continue;
          }
          case 3: {
            if (tag !== 26) {
              break;
            }

            message.subjectDigest = reader.string();
            continue;
          }
          case 4: {
            if (tag !== 34) {
              break;
            }

            message.baseRevision = reader.string();
            continue;
          }
          case 5: {
            if (tag !== 40) {
              break;
            }

            message.state = reader.int32() as any;
            continue;
          }
          case 6: {
            if (tag !== 50) {
              break;
            }

            message.sourceRevision = reader.string();
            continue;
          }
          case 7: {
            if (tag !== 58) {
              break;
            }

            message.currentRevision = reader.string();
            continue;
          }
          case 8: {
            if (tag !== 66) {
              break;
            }

            message.sourceDigest = reader.string();
            continue;
          }
          case 9: {
            if (tag !== 74) {
              break;
            }

            message.module = ArtifactReference.decode(reader, reader.uint32());
            continue;
          }
          case 10: {
            if (tag !== 82) {
              break;
            }

            message.styles.push(ArtifactReference.decode(reader, reader.uint32()));
            continue;
          }
          case 11: {
            if (tag !== 90) {
              break;
            }

            message.buildProfileId = reader.string();
            continue;
          }
          case 12: {
            if (tag !== 98) {
              break;
            }

            message.hostProfileId = reader.string();
            continue;
          }
          case 13: {
            if (tag !== 106) {
              break;
            }

            message.failureCode = reader.string();
            continue;
          }
          case 14: {
            if (tag !== 114) {
              break;
            }

            message.revision = reader.string();
            continue;
          }
          case 15: {
            if (tag !== 122) {
              break;
            }

            message.updatedAt = fromTimestamp(Timestamp.decode(reader, reader.uint32()));
            continue;
          }
        }
        if ((tag & 7) === 4 || tag === 0) {
          break;
        }
        reader.skip(tag & 7);
      }
      return message;
    } finally {
      (reader as any).__tsProtoDecodeDepth = previousRecursionDepth;
    }
  },

  fromJSON(object: any): Preview {
    return {
      $type: Preview.$type,
      operationId: isSet(object.operationId)
        ? globalThis.String(object.operationId)
        : isSet(object.operation_id)
        ? globalThis.String(object.operation_id)
        : "",
      tenantId: isSet(object.tenantId)
        ? globalThis.String(object.tenantId)
        : isSet(object.tenant_id)
        ? globalThis.String(object.tenant_id)
        : "",
      subjectDigest: isSet(object.subjectDigest)
        ? globalThis.String(object.subjectDigest)
        : isSet(object.subject_digest)
        ? globalThis.String(object.subject_digest)
        : "",
      baseRevision: isSet(object.baseRevision)
        ? globalThis.String(object.baseRevision)
        : isSet(object.base_revision)
        ? globalThis.String(object.base_revision)
        : "",
      state: isSet(object.state) ? previewStateFromJSON(object.state) : 0,
      sourceRevision: isSet(object.sourceRevision)
        ? globalThis.String(object.sourceRevision)
        : isSet(object.source_revision)
        ? globalThis.String(object.source_revision)
        : undefined,
      currentRevision: isSet(object.currentRevision)
        ? globalThis.String(object.currentRevision)
        : isSet(object.current_revision)
        ? globalThis.String(object.current_revision)
        : undefined,
      sourceDigest: isSet(object.sourceDigest)
        ? globalThis.String(object.sourceDigest)
        : isSet(object.source_digest)
        ? globalThis.String(object.source_digest)
        : "",
      module: isSet(object.module) ? ArtifactReference.fromJSON(object.module) : undefined,
      styles: globalThis.Array.isArray(object?.styles)
        ? object.styles.map((e: any) => ArtifactReference.fromJSON(e))
        : [],
      buildProfileId: isSet(object.buildProfileId)
        ? globalThis.String(object.buildProfileId)
        : isSet(object.build_profile_id)
        ? globalThis.String(object.build_profile_id)
        : "",
      hostProfileId: isSet(object.hostProfileId)
        ? globalThis.String(object.hostProfileId)
        : isSet(object.host_profile_id)
        ? globalThis.String(object.host_profile_id)
        : "",
      failureCode: isSet(object.failureCode)
        ? globalThis.String(object.failureCode)
        : isSet(object.failure_code)
        ? globalThis.String(object.failure_code)
        : undefined,
      revision: isSet(object.revision) ? globalThis.String(object.revision) : "",
      updatedAt: isSet(object.updatedAt)
        ? fromJsonTimestamp(object.updatedAt)
        : isSet(object.updated_at)
        ? fromJsonTimestamp(object.updated_at)
        : undefined,
    };
  },

  toJSON(message: Preview): unknown {
    const obj: any = {};
    if (message.operationId !== "") {
      obj.operationId = message.operationId;
    }
    if (message.tenantId !== "") {
      obj.tenantId = message.tenantId;
    }
    if (message.subjectDigest !== "") {
      obj.subjectDigest = message.subjectDigest;
    }
    if (message.baseRevision !== "") {
      obj.baseRevision = message.baseRevision;
    }
    if (message.state !== 0) {
      obj.state = previewStateToJSON(message.state);
    }
    if (message.sourceRevision !== undefined) {
      obj.sourceRevision = message.sourceRevision;
    }
    if (message.currentRevision !== undefined) {
      obj.currentRevision = message.currentRevision;
    }
    if (message.sourceDigest !== "") {
      obj.sourceDigest = message.sourceDigest;
    }
    if (message.module !== undefined) {
      obj.module = ArtifactReference.toJSON(message.module);
    }
    if (message.styles?.length) {
      obj.styles = message.styles.map((e) => ArtifactReference.toJSON(e));
    }
    if (message.buildProfileId !== "") {
      obj.buildProfileId = message.buildProfileId;
    }
    if (message.hostProfileId !== "") {
      obj.hostProfileId = message.hostProfileId;
    }
    if (message.failureCode !== undefined) {
      obj.failureCode = message.failureCode;
    }
    if (message.revision !== "") {
      obj.revision = message.revision;
    }
    if (message.updatedAt !== undefined) {
      obj.updatedAt = message.updatedAt.toISOString();
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<Preview>, I>>(base?: I): Preview {
    return Preview.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<Preview>, I>>(object: I): Preview {
    const message = createBasePreview();
    message.operationId = object.operationId ?? "";
    message.tenantId = object.tenantId ?? "";
    message.subjectDigest = object.subjectDigest ?? "";
    message.baseRevision = object.baseRevision ?? "";
    message.state = object.state ?? 0;
    message.sourceRevision = object.sourceRevision ?? undefined;
    message.currentRevision = object.currentRevision ?? undefined;
    message.sourceDigest = object.sourceDigest ?? "";
    message.module = (object.module !== undefined && object.module !== null)
      ? ArtifactReference.fromPartial(object.module)
      : undefined;
    message.styles = object.styles?.map((e) => ArtifactReference.fromPartial(e)) || [];
    message.buildProfileId = object.buildProfileId ?? "";
    message.hostProfileId = object.hostProfileId ?? "";
    message.failureCode = object.failureCode ?? undefined;
    message.revision = object.revision ?? "";
    message.updatedAt = object.updatedAt ?? undefined;
    return message;
  },
};

messageTypeRegistry.set(Preview.$type, Preview);

function createBaseRecordPreviewRequest(): RecordPreviewRequest {
  return {
    $type: "anvilkit.control.v1.RecordPreviewRequest",
    operationId: "",
    expectedRevision: "",
    state: 0,
    sourceRevision: undefined,
    currentRevision: undefined,
    sourceDigest: "",
    module: undefined,
    styles: [],
    buildProfileId: "",
    hostProfileId: "",
    failureCode: undefined,
    command: undefined,
  };
}

export const RecordPreviewRequest: MessageFns<RecordPreviewRequest, "anvilkit.control.v1.RecordPreviewRequest"> = {
  $type: "anvilkit.control.v1.RecordPreviewRequest" as const,

  encode(message: RecordPreviewRequest, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.operationId !== "") {
      writer.uint32(10).string(message.operationId);
    }
    if (message.expectedRevision !== "") {
      writer.uint32(18).string(message.expectedRevision);
    }
    if (message.state !== 0) {
      writer.uint32(24).int32(message.state);
    }
    if (message.sourceRevision !== undefined) {
      writer.uint32(34).string(message.sourceRevision);
    }
    if (message.currentRevision !== undefined) {
      writer.uint32(42).string(message.currentRevision);
    }
    if (message.sourceDigest !== "") {
      writer.uint32(50).string(message.sourceDigest);
    }
    if (message.module !== undefined) {
      ArtifactReference.encode(message.module, writer.uint32(58).fork()).join();
    }
    for (const v of message.styles) {
      ArtifactReference.encode(v!, writer.uint32(66).fork()).join();
    }
    if (message.buildProfileId !== "") {
      writer.uint32(74).string(message.buildProfileId);
    }
    if (message.hostProfileId !== "") {
      writer.uint32(82).string(message.hostProfileId);
    }
    if (message.failureCode !== undefined) {
      writer.uint32(90).string(message.failureCode);
    }
    if (message.command !== undefined) {
      CommandIdentity.encode(message.command, writer.uint32(98).fork()).join();
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): RecordPreviewRequest {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const previousRecursionDepth = (reader as any).__tsProtoDecodeDepth ?? 0;
    if (previousRecursionDepth >= 100) {
      throw new globalThis.Error("protobuf decode recursion limit exceeded");
    }
    (reader as any).__tsProtoDecodeDepth = previousRecursionDepth + 1;
    try {
      const end = length === undefined ? reader.len : reader.pos + length;
      const message = createBaseRecordPreviewRequest();
      while (reader.pos < end) {
        const tag = reader.uint32();
        switch (tag >>> 3) {
          case 1: {
            if (tag !== 10) {
              break;
            }

            message.operationId = reader.string();
            continue;
          }
          case 2: {
            if (tag !== 18) {
              break;
            }

            message.expectedRevision = reader.string();
            continue;
          }
          case 3: {
            if (tag !== 24) {
              break;
            }

            message.state = reader.int32() as any;
            continue;
          }
          case 4: {
            if (tag !== 34) {
              break;
            }

            message.sourceRevision = reader.string();
            continue;
          }
          case 5: {
            if (tag !== 42) {
              break;
            }

            message.currentRevision = reader.string();
            continue;
          }
          case 6: {
            if (tag !== 50) {
              break;
            }

            message.sourceDigest = reader.string();
            continue;
          }
          case 7: {
            if (tag !== 58) {
              break;
            }

            message.module = ArtifactReference.decode(reader, reader.uint32());
            continue;
          }
          case 8: {
            if (tag !== 66) {
              break;
            }

            message.styles.push(ArtifactReference.decode(reader, reader.uint32()));
            continue;
          }
          case 9: {
            if (tag !== 74) {
              break;
            }

            message.buildProfileId = reader.string();
            continue;
          }
          case 10: {
            if (tag !== 82) {
              break;
            }

            message.hostProfileId = reader.string();
            continue;
          }
          case 11: {
            if (tag !== 90) {
              break;
            }

            message.failureCode = reader.string();
            continue;
          }
          case 12: {
            if (tag !== 98) {
              break;
            }

            message.command = CommandIdentity.decode(reader, reader.uint32());
            continue;
          }
        }
        if ((tag & 7) === 4 || tag === 0) {
          break;
        }
        reader.skip(tag & 7);
      }
      return message;
    } finally {
      (reader as any).__tsProtoDecodeDepth = previousRecursionDepth;
    }
  },

  fromJSON(object: any): RecordPreviewRequest {
    return {
      $type: RecordPreviewRequest.$type,
      operationId: isSet(object.operationId)
        ? globalThis.String(object.operationId)
        : isSet(object.operation_id)
        ? globalThis.String(object.operation_id)
        : "",
      expectedRevision: isSet(object.expectedRevision)
        ? globalThis.String(object.expectedRevision)
        : isSet(object.expected_revision)
        ? globalThis.String(object.expected_revision)
        : "",
      state: isSet(object.state) ? previewStateFromJSON(object.state) : 0,
      sourceRevision: isSet(object.sourceRevision)
        ? globalThis.String(object.sourceRevision)
        : isSet(object.source_revision)
        ? globalThis.String(object.source_revision)
        : undefined,
      currentRevision: isSet(object.currentRevision)
        ? globalThis.String(object.currentRevision)
        : isSet(object.current_revision)
        ? globalThis.String(object.current_revision)
        : undefined,
      sourceDigest: isSet(object.sourceDigest)
        ? globalThis.String(object.sourceDigest)
        : isSet(object.source_digest)
        ? globalThis.String(object.source_digest)
        : "",
      module: isSet(object.module) ? ArtifactReference.fromJSON(object.module) : undefined,
      styles: globalThis.Array.isArray(object?.styles)
        ? object.styles.map((e: any) => ArtifactReference.fromJSON(e))
        : [],
      buildProfileId: isSet(object.buildProfileId)
        ? globalThis.String(object.buildProfileId)
        : isSet(object.build_profile_id)
        ? globalThis.String(object.build_profile_id)
        : "",
      hostProfileId: isSet(object.hostProfileId)
        ? globalThis.String(object.hostProfileId)
        : isSet(object.host_profile_id)
        ? globalThis.String(object.host_profile_id)
        : "",
      failureCode: isSet(object.failureCode)
        ? globalThis.String(object.failureCode)
        : isSet(object.failure_code)
        ? globalThis.String(object.failure_code)
        : undefined,
      command: isSet(object.command) ? CommandIdentity.fromJSON(object.command) : undefined,
    };
  },

  toJSON(message: RecordPreviewRequest): unknown {
    const obj: any = {};
    if (message.operationId !== "") {
      obj.operationId = message.operationId;
    }
    if (message.expectedRevision !== "") {
      obj.expectedRevision = message.expectedRevision;
    }
    if (message.state !== 0) {
      obj.state = previewStateToJSON(message.state);
    }
    if (message.sourceRevision !== undefined) {
      obj.sourceRevision = message.sourceRevision;
    }
    if (message.currentRevision !== undefined) {
      obj.currentRevision = message.currentRevision;
    }
    if (message.sourceDigest !== "") {
      obj.sourceDigest = message.sourceDigest;
    }
    if (message.module !== undefined) {
      obj.module = ArtifactReference.toJSON(message.module);
    }
    if (message.styles?.length) {
      obj.styles = message.styles.map((e) => ArtifactReference.toJSON(e));
    }
    if (message.buildProfileId !== "") {
      obj.buildProfileId = message.buildProfileId;
    }
    if (message.hostProfileId !== "") {
      obj.hostProfileId = message.hostProfileId;
    }
    if (message.failureCode !== undefined) {
      obj.failureCode = message.failureCode;
    }
    if (message.command !== undefined) {
      obj.command = CommandIdentity.toJSON(message.command);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<RecordPreviewRequest>, I>>(base?: I): RecordPreviewRequest {
    return RecordPreviewRequest.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<RecordPreviewRequest>, I>>(object: I): RecordPreviewRequest {
    const message = createBaseRecordPreviewRequest();
    message.operationId = object.operationId ?? "";
    message.expectedRevision = object.expectedRevision ?? "";
    message.state = object.state ?? 0;
    message.sourceRevision = object.sourceRevision ?? undefined;
    message.currentRevision = object.currentRevision ?? undefined;
    message.sourceDigest = object.sourceDigest ?? "";
    message.module = (object.module !== undefined && object.module !== null)
      ? ArtifactReference.fromPartial(object.module)
      : undefined;
    message.styles = object.styles?.map((e) => ArtifactReference.fromPartial(e)) || [];
    message.buildProfileId = object.buildProfileId ?? "";
    message.hostProfileId = object.hostProfileId ?? "";
    message.failureCode = object.failureCode ?? undefined;
    message.command = (object.command !== undefined && object.command !== null)
      ? CommandIdentity.fromPartial(object.command)
      : undefined;
    return message;
  },
};

messageTypeRegistry.set(RecordPreviewRequest.$type, RecordPreviewRequest);

function createBaseRecordPreviewResponse(): RecordPreviewResponse {
  return { $type: "anvilkit.control.v1.RecordPreviewResponse", preview: undefined, existing: false };
}

export const RecordPreviewResponse: MessageFns<RecordPreviewResponse, "anvilkit.control.v1.RecordPreviewResponse"> = {
  $type: "anvilkit.control.v1.RecordPreviewResponse" as const,

  encode(message: RecordPreviewResponse, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.preview !== undefined) {
      Preview.encode(message.preview, writer.uint32(10).fork()).join();
    }
    if (message.existing !== false) {
      writer.uint32(16).bool(message.existing);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): RecordPreviewResponse {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const previousRecursionDepth = (reader as any).__tsProtoDecodeDepth ?? 0;
    if (previousRecursionDepth >= 100) {
      throw new globalThis.Error("protobuf decode recursion limit exceeded");
    }
    (reader as any).__tsProtoDecodeDepth = previousRecursionDepth + 1;
    try {
      const end = length === undefined ? reader.len : reader.pos + length;
      const message = createBaseRecordPreviewResponse();
      while (reader.pos < end) {
        const tag = reader.uint32();
        switch (tag >>> 3) {
          case 1: {
            if (tag !== 10) {
              break;
            }

            message.preview = Preview.decode(reader, reader.uint32());
            continue;
          }
          case 2: {
            if (tag !== 16) {
              break;
            }

            message.existing = reader.bool();
            continue;
          }
        }
        if ((tag & 7) === 4 || tag === 0) {
          break;
        }
        reader.skip(tag & 7);
      }
      return message;
    } finally {
      (reader as any).__tsProtoDecodeDepth = previousRecursionDepth;
    }
  },

  fromJSON(object: any): RecordPreviewResponse {
    return {
      $type: RecordPreviewResponse.$type,
      preview: isSet(object.preview) ? Preview.fromJSON(object.preview) : undefined,
      existing: isSet(object.existing) ? globalThis.Boolean(object.existing) : false,
    };
  },

  toJSON(message: RecordPreviewResponse): unknown {
    const obj: any = {};
    if (message.preview !== undefined) {
      obj.preview = Preview.toJSON(message.preview);
    }
    if (message.existing !== false) {
      obj.existing = message.existing;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<RecordPreviewResponse>, I>>(base?: I): RecordPreviewResponse {
    return RecordPreviewResponse.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<RecordPreviewResponse>, I>>(object: I): RecordPreviewResponse {
    const message = createBaseRecordPreviewResponse();
    message.preview = (object.preview !== undefined && object.preview !== null)
      ? Preview.fromPartial(object.preview)
      : undefined;
    message.existing = object.existing ?? false;
    return message;
  },
};

messageTypeRegistry.set(RecordPreviewResponse.$type, RecordPreviewResponse);

function createBaseGetPreviewRequest(): GetPreviewRequest {
  return { $type: "anvilkit.control.v1.GetPreviewRequest", tenantId: "", operationId: "" };
}

export const GetPreviewRequest: MessageFns<GetPreviewRequest, "anvilkit.control.v1.GetPreviewRequest"> = {
  $type: "anvilkit.control.v1.GetPreviewRequest" as const,

  encode(message: GetPreviewRequest, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.tenantId !== "") {
      writer.uint32(10).string(message.tenantId);
    }
    if (message.operationId !== "") {
      writer.uint32(18).string(message.operationId);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): GetPreviewRequest {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const previousRecursionDepth = (reader as any).__tsProtoDecodeDepth ?? 0;
    if (previousRecursionDepth >= 100) {
      throw new globalThis.Error("protobuf decode recursion limit exceeded");
    }
    (reader as any).__tsProtoDecodeDepth = previousRecursionDepth + 1;
    try {
      const end = length === undefined ? reader.len : reader.pos + length;
      const message = createBaseGetPreviewRequest();
      while (reader.pos < end) {
        const tag = reader.uint32();
        switch (tag >>> 3) {
          case 1: {
            if (tag !== 10) {
              break;
            }

            message.tenantId = reader.string();
            continue;
          }
          case 2: {
            if (tag !== 18) {
              break;
            }

            message.operationId = reader.string();
            continue;
          }
        }
        if ((tag & 7) === 4 || tag === 0) {
          break;
        }
        reader.skip(tag & 7);
      }
      return message;
    } finally {
      (reader as any).__tsProtoDecodeDepth = previousRecursionDepth;
    }
  },

  fromJSON(object: any): GetPreviewRequest {
    return {
      $type: GetPreviewRequest.$type,
      tenantId: isSet(object.tenantId)
        ? globalThis.String(object.tenantId)
        : isSet(object.tenant_id)
        ? globalThis.String(object.tenant_id)
        : "",
      operationId: isSet(object.operationId)
        ? globalThis.String(object.operationId)
        : isSet(object.operation_id)
        ? globalThis.String(object.operation_id)
        : "",
    };
  },

  toJSON(message: GetPreviewRequest): unknown {
    const obj: any = {};
    if (message.tenantId !== "") {
      obj.tenantId = message.tenantId;
    }
    if (message.operationId !== "") {
      obj.operationId = message.operationId;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<GetPreviewRequest>, I>>(base?: I): GetPreviewRequest {
    return GetPreviewRequest.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<GetPreviewRequest>, I>>(object: I): GetPreviewRequest {
    const message = createBaseGetPreviewRequest();
    message.tenantId = object.tenantId ?? "";
    message.operationId = object.operationId ?? "";
    return message;
  },
};

messageTypeRegistry.set(GetPreviewRequest.$type, GetPreviewRequest);

function createBaseGetPreviewResponse(): GetPreviewResponse {
  return { $type: "anvilkit.control.v1.GetPreviewResponse", preview: undefined };
}

export const GetPreviewResponse: MessageFns<GetPreviewResponse, "anvilkit.control.v1.GetPreviewResponse"> = {
  $type: "anvilkit.control.v1.GetPreviewResponse" as const,

  encode(message: GetPreviewResponse, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.preview !== undefined) {
      Preview.encode(message.preview, writer.uint32(10).fork()).join();
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): GetPreviewResponse {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const previousRecursionDepth = (reader as any).__tsProtoDecodeDepth ?? 0;
    if (previousRecursionDepth >= 100) {
      throw new globalThis.Error("protobuf decode recursion limit exceeded");
    }
    (reader as any).__tsProtoDecodeDepth = previousRecursionDepth + 1;
    try {
      const end = length === undefined ? reader.len : reader.pos + length;
      const message = createBaseGetPreviewResponse();
      while (reader.pos < end) {
        const tag = reader.uint32();
        switch (tag >>> 3) {
          case 1: {
            if (tag !== 10) {
              break;
            }

            message.preview = Preview.decode(reader, reader.uint32());
            continue;
          }
        }
        if ((tag & 7) === 4 || tag === 0) {
          break;
        }
        reader.skip(tag & 7);
      }
      return message;
    } finally {
      (reader as any).__tsProtoDecodeDepth = previousRecursionDepth;
    }
  },

  fromJSON(object: any): GetPreviewResponse {
    return {
      $type: GetPreviewResponse.$type,
      preview: isSet(object.preview) ? Preview.fromJSON(object.preview) : undefined,
    };
  },

  toJSON(message: GetPreviewResponse): unknown {
    const obj: any = {};
    if (message.preview !== undefined) {
      obj.preview = Preview.toJSON(message.preview);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<GetPreviewResponse>, I>>(base?: I): GetPreviewResponse {
    return GetPreviewResponse.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<GetPreviewResponse>, I>>(object: I): GetPreviewResponse {
    const message = createBaseGetPreviewResponse();
    message.preview = (object.preview !== undefined && object.preview !== null)
      ? Preview.fromPartial(object.preview)
      : undefined;
    return message;
  },
};

messageTypeRegistry.set(GetPreviewResponse.$type, GetPreviewResponse);

function createBaseGetSourceRequest(): GetSourceRequest {
  return { $type: "anvilkit.control.v1.GetSourceRequest", tenantId: "", operationId: "" };
}

export const GetSourceRequest: MessageFns<GetSourceRequest, "anvilkit.control.v1.GetSourceRequest"> = {
  $type: "anvilkit.control.v1.GetSourceRequest" as const,

  encode(message: GetSourceRequest, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.tenantId !== "") {
      writer.uint32(10).string(message.tenantId);
    }
    if (message.operationId !== "") {
      writer.uint32(18).string(message.operationId);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): GetSourceRequest {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const previousRecursionDepth = (reader as any).__tsProtoDecodeDepth ?? 0;
    if (previousRecursionDepth >= 100) {
      throw new globalThis.Error("protobuf decode recursion limit exceeded");
    }
    (reader as any).__tsProtoDecodeDepth = previousRecursionDepth + 1;
    try {
      const end = length === undefined ? reader.len : reader.pos + length;
      const message = createBaseGetSourceRequest();
      while (reader.pos < end) {
        const tag = reader.uint32();
        switch (tag >>> 3) {
          case 1: {
            if (tag !== 10) {
              break;
            }

            message.tenantId = reader.string();
            continue;
          }
          case 2: {
            if (tag !== 18) {
              break;
            }

            message.operationId = reader.string();
            continue;
          }
        }
        if ((tag & 7) === 4 || tag === 0) {
          break;
        }
        reader.skip(tag & 7);
      }
      return message;
    } finally {
      (reader as any).__tsProtoDecodeDepth = previousRecursionDepth;
    }
  },

  fromJSON(object: any): GetSourceRequest {
    return {
      $type: GetSourceRequest.$type,
      tenantId: isSet(object.tenantId)
        ? globalThis.String(object.tenantId)
        : isSet(object.tenant_id)
        ? globalThis.String(object.tenant_id)
        : "",
      operationId: isSet(object.operationId)
        ? globalThis.String(object.operationId)
        : isSet(object.operation_id)
        ? globalThis.String(object.operation_id)
        : "",
    };
  },

  toJSON(message: GetSourceRequest): unknown {
    const obj: any = {};
    if (message.tenantId !== "") {
      obj.tenantId = message.tenantId;
    }
    if (message.operationId !== "") {
      obj.operationId = message.operationId;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<GetSourceRequest>, I>>(base?: I): GetSourceRequest {
    return GetSourceRequest.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<GetSourceRequest>, I>>(object: I): GetSourceRequest {
    const message = createBaseGetSourceRequest();
    message.tenantId = object.tenantId ?? "";
    message.operationId = object.operationId ?? "";
    return message;
  },
};

messageTypeRegistry.set(GetSourceRequest.$type, GetSourceRequest);

function createBaseGetSourceResponse(): GetSourceResponse {
  return { $type: "anvilkit.control.v1.GetSourceResponse", source: undefined, lineage: "", revision: undefined };
}

export const GetSourceResponse: MessageFns<GetSourceResponse, "anvilkit.control.v1.GetSourceResponse"> = {
  $type: "anvilkit.control.v1.GetSourceResponse" as const,

  encode(message: GetSourceResponse, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.source !== undefined) {
      ArtifactReference.encode(message.source, writer.uint32(10).fork()).join();
    }
    if (message.lineage !== "") {
      writer.uint32(18).string(message.lineage);
    }
    if (message.revision !== undefined) {
      writer.uint32(26).string(message.revision);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): GetSourceResponse {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const previousRecursionDepth = (reader as any).__tsProtoDecodeDepth ?? 0;
    if (previousRecursionDepth >= 100) {
      throw new globalThis.Error("protobuf decode recursion limit exceeded");
    }
    (reader as any).__tsProtoDecodeDepth = previousRecursionDepth + 1;
    try {
      const end = length === undefined ? reader.len : reader.pos + length;
      const message = createBaseGetSourceResponse();
      while (reader.pos < end) {
        const tag = reader.uint32();
        switch (tag >>> 3) {
          case 1: {
            if (tag !== 10) {
              break;
            }

            message.source = ArtifactReference.decode(reader, reader.uint32());
            continue;
          }
          case 2: {
            if (tag !== 18) {
              break;
            }

            message.lineage = reader.string();
            continue;
          }
          case 3: {
            if (tag !== 26) {
              break;
            }

            message.revision = reader.string();
            continue;
          }
        }
        if ((tag & 7) === 4 || tag === 0) {
          break;
        }
        reader.skip(tag & 7);
      }
      return message;
    } finally {
      (reader as any).__tsProtoDecodeDepth = previousRecursionDepth;
    }
  },

  fromJSON(object: any): GetSourceResponse {
    return {
      $type: GetSourceResponse.$type,
      source: isSet(object.source) ? ArtifactReference.fromJSON(object.source) : undefined,
      lineage: isSet(object.lineage) ? globalThis.String(object.lineage) : "",
      revision: isSet(object.revision) ? globalThis.String(object.revision) : undefined,
    };
  },

  toJSON(message: GetSourceResponse): unknown {
    const obj: any = {};
    if (message.source !== undefined) {
      obj.source = ArtifactReference.toJSON(message.source);
    }
    if (message.lineage !== "") {
      obj.lineage = message.lineage;
    }
    if (message.revision !== undefined) {
      obj.revision = message.revision;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<GetSourceResponse>, I>>(base?: I): GetSourceResponse {
    return GetSourceResponse.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<GetSourceResponse>, I>>(object: I): GetSourceResponse {
    const message = createBaseGetSourceResponse();
    message.source = (object.source !== undefined && object.source !== null)
      ? ArtifactReference.fromPartial(object.source)
      : undefined;
    message.lineage = object.lineage ?? "";
    message.revision = object.revision ?? undefined;
    return message;
  },
};

messageTypeRegistry.set(GetSourceResponse.$type, GetSourceResponse);

export type PreviewServiceService = typeof PreviewServiceService;
export const PreviewServiceService = {
  /**
   * The Workflow records a transition under the expected projection
   * revision; the same transition repeated answers the recorded one.
   */
  recordPreview: {
    path: "/anvilkit.control.v1.PreviewService/RecordPreview" as const,
    requestStream: false as const,
    responseStream: false as const,
    requestSerialize: (value: RecordPreviewRequest): Buffer => Buffer.from(RecordPreviewRequest.encode(value).finish()),
    requestDeserialize: (value: Buffer): RecordPreviewRequest => RecordPreviewRequest.decode(value),
    responseSerialize: (value: RecordPreviewResponse): Buffer =>
      Buffer.from(RecordPreviewResponse.encode(value).finish()),
    responseDeserialize: (value: Buffer): RecordPreviewResponse => RecordPreviewResponse.decode(value),
  },
  /** The committed projection of a preview_build operation of the tenant. */
  getPreview: {
    path: "/anvilkit.control.v1.PreviewService/GetPreview" as const,
    requestStream: false as const,
    responseStream: false as const,
    requestSerialize: (value: GetPreviewRequest): Buffer => Buffer.from(GetPreviewRequest.encode(value).finish()),
    requestDeserialize: (value: Buffer): GetPreviewRequest => GetPreviewRequest.decode(value),
    responseSerialize: (value: GetPreviewResponse): Buffer => Buffer.from(GetPreviewResponse.encode(value).finish()),
    responseDeserialize: (value: Buffer): GetPreviewResponse => GetPreviewResponse.decode(value),
  },
  /**
   * The source the workbench edits: a generation's certified source (with
   * the revision its candidate registration answered) or a preview build's
   * edited source (with the revision its save created, else its base).
   */
  getSource: {
    path: "/anvilkit.control.v1.PreviewService/GetSource" as const,
    requestStream: false as const,
    responseStream: false as const,
    requestSerialize: (value: GetSourceRequest): Buffer => Buffer.from(GetSourceRequest.encode(value).finish()),
    requestDeserialize: (value: Buffer): GetSourceRequest => GetSourceRequest.decode(value),
    responseSerialize: (value: GetSourceResponse): Buffer => Buffer.from(GetSourceResponse.encode(value).finish()),
    responseDeserialize: (value: Buffer): GetSourceResponse => GetSourceResponse.decode(value),
  },
} as const;

export interface PreviewServiceServer extends UntypedServiceImplementation {
  /**
   * The Workflow records a transition under the expected projection
   * revision; the same transition repeated answers the recorded one.
   */
  recordPreview: handleUnaryCall<RecordPreviewRequest, RecordPreviewResponse>;
  /** The committed projection of a preview_build operation of the tenant. */
  getPreview: handleUnaryCall<GetPreviewRequest, GetPreviewResponse>;
  /**
   * The source the workbench edits: a generation's certified source (with
   * the revision its candidate registration answered) or a preview build's
   * edited source (with the revision its save created, else its base).
   */
  getSource: handleUnaryCall<GetSourceRequest, GetSourceResponse>;
}

export interface PreviewServiceClient extends Client {
  /**
   * The Workflow records a transition under the expected projection
   * revision; the same transition repeated answers the recorded one.
   */
  recordPreview(
    request: RecordPreviewRequest,
    callback: (error: ServiceError | null, response: RecordPreviewResponse) => void,
  ): ClientUnaryCall;
  recordPreview(
    request: RecordPreviewRequest,
    metadata: Metadata,
    callback: (error: ServiceError | null, response: RecordPreviewResponse) => void,
  ): ClientUnaryCall;
  recordPreview(
    request: RecordPreviewRequest,
    metadata: Metadata,
    options: Partial<CallOptions>,
    callback: (error: ServiceError | null, response: RecordPreviewResponse) => void,
  ): ClientUnaryCall;
  /** The committed projection of a preview_build operation of the tenant. */
  getPreview(
    request: GetPreviewRequest,
    callback: (error: ServiceError | null, response: GetPreviewResponse) => void,
  ): ClientUnaryCall;
  getPreview(
    request: GetPreviewRequest,
    metadata: Metadata,
    callback: (error: ServiceError | null, response: GetPreviewResponse) => void,
  ): ClientUnaryCall;
  getPreview(
    request: GetPreviewRequest,
    metadata: Metadata,
    options: Partial<CallOptions>,
    callback: (error: ServiceError | null, response: GetPreviewResponse) => void,
  ): ClientUnaryCall;
  /**
   * The source the workbench edits: a generation's certified source (with
   * the revision its candidate registration answered) or a preview build's
   * edited source (with the revision its save created, else its base).
   */
  getSource(
    request: GetSourceRequest,
    callback: (error: ServiceError | null, response: GetSourceResponse) => void,
  ): ClientUnaryCall;
  getSource(
    request: GetSourceRequest,
    metadata: Metadata,
    callback: (error: ServiceError | null, response: GetSourceResponse) => void,
  ): ClientUnaryCall;
  getSource(
    request: GetSourceRequest,
    metadata: Metadata,
    options: Partial<CallOptions>,
    callback: (error: ServiceError | null, response: GetSourceResponse) => void,
  ): ClientUnaryCall;
}

export const PreviewServiceClient = makeGenericClientConstructor(
  PreviewServiceService,
  "anvilkit.control.v1.PreviewService",
) as unknown as {
  new (address: string, credentials: ChannelCredentials, options?: Partial<ClientOptions>): PreviewServiceClient;
  service: typeof PreviewServiceService;
  serviceName: string;
};

type Builtin = Date | Function | Uint8Array | string | number | boolean | undefined;

export type DeepPartial<T> = T extends Builtin ? T
  : T extends globalThis.Array<infer U> ? globalThis.Array<DeepPartial<U>>
  : T extends ReadonlyArray<infer U> ? ReadonlyArray<DeepPartial<U>>
  : T extends {} ? { [K in Exclude<keyof T, "$type">]?: DeepPartial<T[K]> }
  : Partial<T>;

type KeysOfUnion<T> = T extends T ? keyof T : never;
export type Exact<P, I extends P> = P extends Builtin ? P
  : P & { [K in keyof P]: Exact<P[K], I[K]> } & { [K in Exclude<keyof I, KeysOfUnion<P> | "$type">]: never };

function toTimestamp(date: Date): Timestamp {
  const seconds = Math.trunc(date.getTime() / 1_000);
  const nanos = (date.getTime() % 1_000) * 1_000_000;
  return { $type: "google.protobuf.Timestamp", seconds, nanos };
}

function fromTimestamp(t: Timestamp): Date {
  let millis = (t.seconds || 0) * 1_000;
  millis += (t.nanos || 0) / 1_000_000;
  return new globalThis.Date(millis);
}

function fromJsonTimestamp(o: any): Date {
  if (o instanceof globalThis.Date) {
    return o;
  } else if (typeof o === "string") {
    return new globalThis.Date(o);
  } else {
    return fromTimestamp(Timestamp.fromJSON(o));
  }
}

function isSet(value: any): boolean {
  return value !== null && value !== undefined;
}

export interface MessageFns<T, V extends string> {
  readonly $type: V;
  encode(message: T, writer?: BinaryWriter): BinaryWriter;
  decode(input: BinaryReader | Uint8Array, length?: number): T;
  fromJSON(object: any): T;
  toJSON(message: T): unknown;
  create<I extends Exact<DeepPartial<T>, I>>(base?: I): T;
  fromPartial<I extends Exact<DeepPartial<T>, I>>(object: I): T;
}
